### ISSUE TITLE
It doesn't detect ninja-build as a valid alternative command for ninja

### ISSUE THREAD

**Issue by astitcher** [vector-of-bool/vscode-cmake-tools#1]
Some Linux distributions (including Fedora) use "ninja-build" as the command to invoke ninja due to a pre-existing command called ninja.

**Comment by vector-of-bool** [comment]
Thanks for the info. It is simple enough to detect ``ninja-build`` as an alternative to ``ninja``.

I want to rework the automatic generator-detection code to be smarter, as it doesn't consider the case where the ``ninja`` command isn't actually the Ninja that's expected.
