### ISSUE TITLE
spawn ctest NOENT

### ISSUE THREAD

**Issue by unjello** [vector-of-bool/vscode-cmake-tools#101]
I have a CMake project (with Catch as UT framework), CTest from command line runs just fine, but from vscode "CMake Run Tests" does the following:
[vscode] Executing command: ctest -j6 -C Debug -T test --output-on-failure
[vscode] ctest exited with return code -2

and a warning/error tab pops up at the top with "spawn ctest NOENT"

vscode: 1.8.1
cmake-tools: 0.8.7

**Comment by vector-of-bool** [comment]
Interesting... I'm seeing this too. I'll have to take a look, CTest is pretty important.
