### ISSUE TITLE
after installing 0.9.1 can't launch build with NMake

### ISSUE THREAD

**Issue by josesimoes** [vector-of-bool/vscode-cmake-tools#108]
Don't know what's causing it, nor what should I do to investigate the root cause.

**Comment by vector-of-bool** [comment]
Sorry, I'm not quite sure what the issue is. Did you mean "_can't_ launch build with NMake"?

**Comment by vector-of-bool** [comment]
Ah. I'll look into it.

**Comment by josesimoes** [comment]
You are correct. I miss type it...

After hitting the build icon I get:
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO"

I went and run CMake with ```cmake --debug-trycompile``` and the error was "...does not appear to contain CMakeLists.txt"

Just revert to v0.9.0 and its working again, so I'm pretty sure it has to do with the update.

**Comment by vector-of-bool** [comment]
Have you tried clearing out your build directory? Could I see the outupt from `CMakeFiles/CMakeError.log`?

**Comment by josesimoes** [comment]
I did clean the build directory.
I don't have the log anymore... everything wiped...

**Comment by vector-of-bool** [comment]
Is the error occurring during configuration, or during build?

**Comment by josesimoes** [comment]
Config goes fine. That error shows only after hitting the build icon.

**Comment by vector-of-bool** [comment]
Sorry to be so long on this. I was at a loss for what could be going on here. I realized that I recently broke the way that environment variable are passed to child processes, but it was non-deterministically broken. I only realized it was going wrong when I started getting similar issues on my own machine. Does this issue still occur in 0.9.2?

**Comment by josesimoes** [comment]
I confirm that this has been corrected with 0.9.2.
Thanks for the great work with this extension. 👍
