### ISSUE TITLE
SDK version

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#109]
hi
please remind - is there ability to specify which WinSDK is current in the use?

**Comment by amigo421** [comment]
by the way - do I understand this right, cmaketools currently doesn't support auto-detect VS2017/VCBuildTools2017 toolchains?

**Comment by vector-of-bool** [comment]
At the moment, it will just call `vsvarsall.bat` to discover all the environment variables required for the build toolchain. There is no support ATM for specifying what version of the Windows SDK to use. I'd be open to pull requests if you have an idea of how that could be done (I'm not entirely sure how it would fit into the current environment selection framework).

As for VS2017: No, I have not yet added the detection support for those toolchains yet. It is probably a trivial change, I just haven't gotten around to doing it yet. I'll definitely get it in for RTM, at the latest. Again, PRs are welcome.

**Comment by amigo421** [comment]
do you know what this can mean :



![image](https://cloud.githubusercontent.com/assets/3259933/22709073/97a97e68-ed89-11e6-80b6-7d20f3720234.png)

**Comment by vector-of-bool** [comment]
I wouldn't know without seeing more output and logs.

**Comment by amigo421** [comment]
I'm going to close - was something wrong with a few VC toolchains. re-intstall VC build tools and works fine
