### ISSUE TITLE
Can't move on after stopped

### ISSUE THREAD

**Issue by hueyke** [vector-of-bool/vscode-cmake-tools#112]
Hi, I tried to debug on a simple helloworld cmake project on mac and it works perfectly. However, when I try to work with my code (with fftw and gsl), it can't move on(step over/step into) nor stop debugging.  I have to terminate "lldb-mi" with Activity Monitor then terminate the execution. Do you have any idea what causes this situation?

**Comment by vector-of-bool** [comment]
I'm sorry, but I wouldn't be of much help. This extension does not implement a debugger, it only delegates to the cpptools debugger. I'd recommend opening up an issue on [their GitHub page](https://github.com/Microsoft/vscode-cpptools/issues), but make sure you try it with manually specifying the content of your `launch.json`.

**Comment by hueyke** [comment]
Thank you for your quick reply. I'll open an issue on cpptools.
