### ISSUE TITLE
0.9.2 doesn't seem to pass/override environment variables

### ISSUE THREAD

**Issue by napcode** [vector-of-bool/vscode-cmake-tools#113]
I have a few crucial environment variables set in OSX. For a certain project I override them manually in the VS code config 
```
{
    "cmake.environment": {
        "MYVAR": "/some/value"
    }
}
```

Using something like `message(STATUS $ENV{MYVAR})` does not print "/some/value" now. The project settings are being ignored. This used to work as expected before the update to 0.9.2. Did the behaviour change? Can only non-existing variables be set from these configurations or is there a bug?

**Comment by vector-of-bool** [comment]
This is a bug. In 0.9.2 I fixed a bug with environment variables on Windows, and apparently re-broke environment variables on OSX.

I don't have an OSX system to test for myself, so I have a few quick questions that might help diagnose this:

1. Are you able to see environment variables at all within CMake?
2. Is it just ignoring config and passing down environment variables from the surrounding environments? ie. If you overwrite `FOO` in the config, and `FOO` is defined outside the environment, are you seeing `FOO` as it is defined outside the environment?
3. If you define an environment variable that is not defined in the outside environment, are you able to see it?

**Comment by napcode** [comment]
I just tested this on Linux as well. The behaviour is the same. 

> Are you able to see environment variables at all within CMake?
Yes.

> Is it just ignoring config and passing down environment variables from the surrounding environments? ie. If you overwrite FOO in the config, and FOO is defined outside the environment, are you seeing FOO as it is defined outside the environment?
Correct. CMake sees env variables and it doesn't matter where they are defined. I'm unable to override variables via the config if they exist outside of the environment as well.

> If you define an environment variable that is not defined in the outside environment, are you able to see it?
Yes. 

Thank you for working on this and the cmake-tools in general! I really appreciate it.

**Comment by vector-of-bool** [comment]
Thanks for the info. I'm not in a position to fix this at the moment, but I'll get on my Linux dev box and see about writing up some test cases to catch this, and hopefully not break Windows again in the process.

**Comment by vector-of-bool** [comment]
The code is getting kind of hairy. With "real life" getting in the way, I'm not sure when I'll be able to get to reworking some of it, although I really want to get around to it. Hopefully, this issue won't crop up again for a while. This should be fixed in the next release, but tell me if it still is bothering you. Thanks for the issue report!

**Comment by napcode** [comment]
Thanks for the fix!
