### ISSUE TITLE
CMake Cache Editor: all boolean options in file show as ticked

### ISSUE THREAD

**Issue by sg-brcm** [vector-of-bool/vscode-cmake-tools#114]
I was interested to find the cmake cache editor in the latest versions. However all the boolean entries in my cache file are populated in the editor window as "ticked" even though many of them should be "false/off". 

I can see nothing unusual about the entries in the CMakeCache.txt file itself.

I assume it isn't supposed to be like this...

**Comment by vector-of-bool** [comment]
Cache editor is still experimental. I'm not surprised that it is misbehaving. I've found trouble with boolean checkbox options as well.

**Comment by sg-brcm** [comment]
Thanks for the response. I did see the experimental tag, but thought I would give it a go and see where it was at. It would be nice to eventually replace cmake-gui :-)
