### ISSUE TITLE
Add build directory customization to cmake-variants.json?

### ISSUE THREAD

**Issue by ashtuchkin** [vector-of-bool/vscode-cmake-tools#116]
Hey, wonderful project, thanks for working on it!

I recently found out I can customize the build variants with `cmake-variants.json` and it makes my life a lot easier. One feature I'm missing, though, is ability to switch build directories as well. For example, having debug configuration in one build directory and release in another. Do you think it's possible / easy to add?

My particular use case is a bit more complex - I have a cross-compiled project for an arm processor and would like to add unit testing to be run on host machine. I'm still researching how to do it better, but for now I'm passing a setting to cmake for test configuration and do a bunch of if/else statements to choose the toolchain. This works fine, but with every switch I need to delete the whole build folder and recreate it from scratch. Having two build directories would be a much smoother experience.

Thanks!

**Comment by vector-of-bool** [comment]
I'll look into it, probably useful.

**Comment by ashtuchkin** [comment]
Thanks!

**Comment by vector-of-bool** [comment]
I know it's been a while, but I'm doing a triage over all my open issues.

As a possible solution that doesn't require any additional changes in the extension: Have you tried using the `${var}` style substitution in the `cmake.buildDirectory` option?

It supports `${buildType}`, `${workspaceRoot}`, `${workspaceRootFolderName}`, and `${toolset}`.

In theory, each variant gets a different `${buildType}`, and would work to create unique build directories:

```json
"cmake.buildDirectory": "build/${buildType}"
```

**Comment by ashtuchkin** [comment]
That should work for me. I don't have access to my laptop now to check it,
will try when I return from a trip in a week. Thanks for the suggestion!

--
Alexander Shtuchkin

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
