### ISSUE TITLE
Using CMake Tools without Developer Command-prompt on Windows

### ISSUE THREAD

**Issue by MathiasMagnus** [vector-of-bool/vscode-cmake-tools#117]
Hi!

I was trying to use the extension without having to launch the editor from a dev cmd prompt (to speed up Code launch and pay for env setup only when the extension is active). I have created a minimalistic PowerShell script that extracts the env vars that change when invoking vcvars64.bat.
```Powershell
$oldenv = ls env:
Import-CmdEnvironment 'C:\Kellekek\Microsoft\Visual Studio\15RC\VC\Auxiliary\Build\vcvars64.bat'
$newenv = ls env:
$newenv | foreach {if (!$oldenv.Contains($_)) {Write-Host -Separator "" '"'$_.Name'": "'$_.Value.Replace('\','\\')'",'}}
```
[Import-CmdEnvironment](http://poshcode.org/3547) is a cmdlet that dot sources (in Linux terms) whatever its given. For each env var that is not found in the old environment, it is printed to the console in a copy-paste friendly manner. One can simply change the formatting (for "/" instead of "\\" for eg.). Then I insert it into `cmake.environment": {}` for CMake Tools to use.

I have also set
```JSON
"cmake.preferredGenerators": [
    "NMake Makefiles"
    ]
```
to create output that resembles GNU Make the most, however CMake Tools ALWAYS uses the VS 15 generator for some reason.
```
[vscode] Executing command: C:/Kellekek/Kitware/CMake/3.8.0/bin/cmake.exe -Cc:\Users\Matty\OneDrive\Develop\Tests\CMake\VSCode_test\build\CMakeTools\InitializeCache.cmake -Hc:/users/matty/onedrive/develop/tests/cmake/vscode_test -Bc:/users/matty/onedrive/develop/tests/cmake/vscode_test/build
loading initial cache file c:\Users\Matty\OneDrive\Develop\Tests\CMake\VSCode_test\build\CMakeTools\InitializeCache.cmake
-- Building for: Visual Studio 15 2017
```
Even though I have instructed it to use my 3.8.0-rc1 installation of CMake instead of the cmake found within VS 15 (which drives their own CMake experience) by setting
```JSON
"cmake.cmakePath": "C:/Kellekek/Kitware/CMake/3.8.0/bin/cmake.exe"
```
which can also be seen in the invocation of cmake.exe.

What is the problem? Why won't CMake Tools pickup my generator? With and without CMake Server mode the extension messes up in different ways. Failing to use NMake is without; with server mode it fails to find cmake.build alltogether and cannot even configure.

**Comment by vector-of-bool** [comment]
Probably having trouble detecting that NMake is available. Does it work if you set `cmake.generator` to `NMake Makefiles`? The generator detection code is somewhat brittle, unfortunately.

**Comment by MathiasMagnus** [comment]
Setting `cmake.generator` does indeed force using the desired generator, however it does not work. It very much seems as if the environment variables are not set. (I know it's a recurring struggle to get this right in a crossplat manner.) I even tried dumping my entire environment after invoking vcvars64.bat into the user settings and not just the delta. (Just remove the if clause and have {...} be the clause of the foreach)

Do you have an environment where you can test this? Invoke the PS script I mentioned and dump the result into user settings?

**Comment by MathiasMagnus** [comment]
Is there anything else I can do to help with this issue?

**Comment by vector-of-bool** [comment]
I recently added some fixes for some environment variable misbehavior. I assume this issue is still occurring?

Also, what values for any of the `environment` configuration options do you have set? Are you using the build-environment feature at all? Those two features may not interact nicely.

**Comment by MathiasMagnus** [comment]
This is the roughly the only CMake Tools setting I set (beside Ninja/NMake):
```JSON
"cmake.environment": {
        "__DOTNET_ADD_64BIT": "1",
        "__DOTNET_PREFERRED_BITNESS": "64",
        "__VSCMD_PREINIT_PATH": "C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Kellekek\\AMD APP SDK\\3.0\\bin\\x86_64;C:\\Kellekek\\AMD APP SDK\\3.0\\bin\\x86;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Kellekek\\Git\\2.8.1\\cmd;C:\\Kellekek\\MathWorks\\MATLAB\\R2016a\\bin;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\dotnet\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Kellekek\\Git\\2.8.1\\cmd;C:\\WINDOWS\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Kellekek\\AMD\\clFFT\\2.10.1\\bin;C:\\Chocolatey\\bin;C:\\Users\\Matty\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Kellekek\\Jom\\1.1.1;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Bin;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Lib\\x64;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Include;C:\\Kellekek\\AMD\\clBLAS\\2.10\\bin;C:\\Kellekek\\Microsoft\\Visual Studio\\Code\\bin;C:\\Kellekek\\Ninja\\1.7.2\\bin;C:\\Kellekek\\Kitware\\CMake\\3.8.0\\bin",
        "CommandPromptType": "Native",
        "DevEnvDir": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\IDE\\",
        "ExtensionSdkDir": "C:\\Program Files (x86)\\Microsoft SDKs\\Windows Kits\\10\\ExtensionSDKs",
        "Framework40Version": "v4.0",
        "FrameworkDir": "C:\\Windows\\Microsoft.NET\\Framework64\\",
        "FrameworkDir64": "C:\\Windows\\Microsoft.NET\\Framework64\\",
        "FrameworkVersion": "v4.0.30319",
        "FrameworkVersion64": "v4.0.30319",
        "INCLUDE": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\Tools\\MSVC\\14.10.24930\\include;C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.14393.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.14393.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.14393.0\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.14393.0\\winrt;",
        "LIB": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\Tools\\MSVC\\14.10.24930\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.14393.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.14393.0\\um\\x64;",
        "LIBPATH": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\Tools\\MSVC\\14.10.24930\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata;C:\\Program Files (x86)\\Windows Kits\\10\\References;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;",
        "NETFXSDKDir": "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\",
        "Path": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\Tools\\MSVC\\14.10.24930\\bin\\HostX64\\x64;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\IDE\\VC\\VCPackages;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\MSBuild\\15.0\\bin\\Roslyn;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Team Tools\\Performance Tools;C:\\Kellekek\\Microsoft\\Visual Studio\\15Preview\\Common\\VSPerfCollectionTools\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\;C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.1\\Framework\\v4.0\\;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.14393.0\\x64;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\\\MSBuild\\15.0\\bin;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\IDE\\;C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\Tools\\;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Kellekek\\AMD APP SDK\\3.0\\bin\\x86_64;C:\\Kellekek\\AMD APP SDK\\3.0\\bin\\x86;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Kellekek\\Git\\2.8.1\\cmd;C:\\Kellekek\\MathWorks\\MATLAB\\R2016a\\bin;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\dotnet\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Kellekek\\Git\\2.8.1\\cmd;C:\\WINDOWS\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Kellekek\\AMD\\clFFT\\2.10.1\\bin;C:\\Chocolatey\\bin;C:\\Users\\Matty\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Kellekek\\Jom\\1.1.1;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Bin;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Lib\\x64;C:\\Kellekek\\Microsoft\\MPI\\7.1.12437.25\\Include;C:\\Kellekek\\AMD\\clBLAS\\2.10\\bin;C:\\Kellekek\\Microsoft\\Visual Studio\\Code\\bin;C:\\Kellekek\\Ninja\\1.7.2\\bin;C:\\Kellekek\\Kitware\\CMake\\3.8.0\\bin",
        "Platform": "x64",
        "PROMPT": "$P$G",
        "UCRTVersion": "10.0.14393.0",
        "UniversalCRTSdkDir": "C:\\Program Files (x86)\\Windows Kits\\10\\",
        "VCIDEInstallDir": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\IDE\\VC\\",
        "VCINSTALLDIR": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\",
        "VCToolsInstallDir": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\Tools\\MSVC\\14.10.24930\\",
        "VCToolsRedistDir": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\VC\\Redist\\MSVC\\14.10.24930\\",
        "VisualStudioVersion": "15.0",
        "VS150COMNTOOLS": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\Common7\\Tools\\",
        "VSCMD_ARG_app_plat": "Desktop",
        "VSCMD_ARG_HOST_ARCH": "x64",
        "VSCMD_ARG_TGT_ARCH": "x64",
        "VSCMD_VER": "15.0.26206.0",
        "VSINSTALLDIR": "C:\\Kellekek\\Microsoft\\Visual Studio\\15RC\\",
        "WindowsLibPath": "C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata;C:\\Program Files (x86)\\Windows Kits\\10\\References",
        "WindowsSDK_ExecutablePath_x64": "C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\x64\\",
        "WindowsSDK_ExecutablePath_x86": "C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\",
        "WindowsSdkBinPath": "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\",
        "WindowsSdkDir": "C:\\Program Files (x86)\\Windows Kits\\10\\",
        "WindowsSDKLibVersion": "10.0.14393.0\\",
        "WindowsSdkVerBinPath": "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.14393.0\\",
        "WindowsSDKVersion": "10.0.14393.0\\"
    }
```
It doesn't matter if I do double\ (to have valid .json) or simply /. None of them work. Is there something wrong with the formatting? I can easily change that with the PS script that created it. It's strange that two entries are not colored properly by Github, and one is Path.

**Comment by vector-of-bool** [comment]
Are you make use of build environments?

**Comment by MathiasMagnus** [comment]
I think I found the problem. I created a dummy project, only so that I can print environmental variables that CMake invocation see.
```CMake
cmake_minimum_required(VERSION 3.0.0)
project(VSCode_test LANGUAGES NONE VERSION 0.0.0)

message(STATUS "VALUE: $ENV{VCINSTALLDIR}")

add_custom_target(print ALL COMMAND "echo %PATH%")
```
All the env vars are set, except for `Path`. It fails to overwrite the original one. The NEW env vars I set are visible and working ok, but it cannot overwrite an existing one, and because `vcvarsall.bat` appends to Path, it cannot find `cl.exe`. My PowerShell script correctly recognized that Path has changes, dumped it onto the console, and even though I put it in the `settings.json`, it still sees the old value.

If you can patch this up, I think it will work. Either overwrite or append to existing ones (doesn't matter, just document your choice), and we'll all be happy. For my case, overwriting is better, as I won't have to go and filter only the diff of before/after invoking `vcvarsall.bat`, but it might not be the ideal behavior for most people.

**Comment by vector-of-bool** [comment]
Are you making use of the build environment selector in VSCode using CMake Tools? That will override certain environment variables with the ones set by the `vcvarsall` scripts, and is probably what is going on here.

Automatically appending to environment variables is tricky business, because it can vary between platforms, and I have to make sure I am aware of all the list-like variables (`PATH`, `LIB`, `INCLUDE`, etc.).

**Comment by MathiasMagnus** [comment]
I do not. It doesn't even show (at least I recall there should be a button on the Status Bar, but I don't see any toolchain selection button there).

**Comment by MathiasMagnus** [comment]
I have revisited the issue several times now, but could not solve the issue. Where is the build environment selector? I have VS 2017 and VS 2017 Preview installed both in non-standard locations. I am aware that VS 2017 [wildly altered](https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/) the way the SDK is laid out and detected. The [msvs-com-helper](https://github.com/node4good/msvs-com-helper) repo might help in detecting VS 2017 installations and above. I am using this repo from PowerShell Core as
```Powershell
PS C:\Users\Matty\Source\Repos\msvs-com-helper> Add-Type -Path .\GetVS2017Configuration.cs
PS C:\Users\Matty\Source\Repos\msvs-com-helper> Import-CmdEnvironment ([VisualStudioConfiguration.ComSurrogate]::QueryEx()[0].VCAuxiliaryBuildPath + 'vcvars64.bat')
PS C:\Users\Matty\Source\Repos\msvs-com-helper> cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25303 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```
(This code assumes that the built-in query feature returns VS instances in descending version order.)

**Comment by vector-of-bool** [comment]
@MathiasMagnus, sorry for disappearing like I did. "Real life" and all that.

VS 2017 is not yet supported for the environment selector, and it may take a bit of work to get it working correctly since they radically changed the install for that version. If there are no available environments, CMake Tools will not display an environment selector. Would it be alright if this issue were closed and defer to #130?

**Comment by MathiasMagnus** [comment]
No worries. With two little girls at home, I have some degree of experience what it's like when "real life" puts "professional life" to pause.

Fine by me. Don't know which is better, enable the tinker way of setting up the build env, or the automated way (in which case people have to wait for support). I'm not too happy with the new dev env detection, but at least if they stick to it, zero code update will have this feature working til VS2030.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
