### ISSUE TITLE
Warning parsing breaks when using templates

### ISSUE THREAD

**Issue by NOhs** [vector-of-bool/vscode-cmake-tools#118]
I have the following MWE:

    #include <iostream>

    template<typename T>
    T myFunc(int v)
    {
        return T();
    }

    int main()
    {
        std::cout << myFunc<int>(12);
    }

which produces:
![image](https://cloud.githubusercontent.com/assets/20553080/23137130/99b67802-f7a0-11e6-9c72-ae1a689a6647.png)

Without templates, I correctly get (replace T with int and T() with 0):

![image](https://cloud.githubusercontent.com/assets/20553080/23137152/b86a89a0-f7a0-11e6-9169-95fbfa9d71ff.png)

**Comment by vector-of-bool** [comment]
Good observation, perhaps related to #94?

**Comment by vector-of-bool** [comment]
Looks like the parser was tripped up by the template instantiation traceback, and not for any reason I can exactly discern. I want to rework the parser eventually: It's been fairly problematic for a while.

I've found a somewhat viable fix, should be in the next release.

**Comment by NOhs** [comment]
Well, don't we all get confused by the template output sometimes? I don't blame the parser ;). Good to see that this plugin is maintained actively. I use it a lot. Keep up the good work!
