### ISSUE TITLE
User Feedback Survey

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/vscode-cmake-tools#119]
[Click here to take the survey](https://goo.gl/forms/q0dxdZiZi5dM2ypy1).

Rather than figuring out how to insert telemetry or set up any fancy dashboards required for such things, I've created an informal, anonymous Google Forms survey.

The feedback collected therein will be used to steer future project changes.

**Comment by mkotlyar** [comment]
I am happy so far, will let you know when I have something particular to say.
Keep doing the great job!

**Comment by mkotlyar** [comment]
Yes, I do have a suggestion. It would be nice to have _colorful_ output from `cmake` in the OUTPUT window.

**Comment by vector-of-bool** [comment]
@mkotlyar, I've always wanted to be able to provide richer output than what is available in VSCode's current `OutputChannel` API. There are a few open feature requests on VSCode relating to this ([#564](https://github.com/Microsoft/vscode/issues/564), [#571](https://github.com/Microsoft/vscode/issues/571), and [#11005](https://github.com/Microsoft/vscode/issues/11005)). We'll have to see where they go.

**Comment by bkeys** [comment]
This is an awesome plugin! It works really well with vscode and makes the IDE so much more usable. Thanks you for this contribution!

**Comment by papahabla** [comment]
When executing the command "CMake: Build a target", it would be nice to have a list of available targets displayed, such as when executing "CMake: Select a target to debug". Currently, the target must be manually entered.

**Comment by andyreimann** [comment]
Like the plugin.

You think it's possible to extract all include paths from a cmake project and use them for locating files in include statements?

**Comment by vector-of-bool** [comment]
@andyreimann, that's been brought up frequently. Even my own coworkers are hounding me about it. @maddouri has made an extension to do just that, and it may be merged into this codebase in the future.

**Comment by dhicksNTIA** [comment]
I love the plugin. Great time saver. The only complaint is that I would like the debugger to allow for LLDB in Linux. When I tried to switch the 'MIMode' to 'lldb' it did not work stating '/usr/bin/lldb: unrecognized option '--interpreter=mi''.

**Comment by debojyoti-majumder** [comment]
I like it very much. Keep up the good work. Thanks for building such a good tool

**Comment by Randshot** [comment]
@vector-of-bool If you still have a need for the survey, I would suggest placing the link in your README.md instead, since here it is pretty much invisible for most users.
I will close this one for now.
