### ISSUE TITLE
Compiler errors are shown as [Link] in the PROBLEMS window

### ISSUE THREAD

**Issue by mkotlyar** [vector-of-bool/vscode-cmake-tools#120]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/8616371/23307973/d2e93a36-faa9-11e6-9d0d-71d2ab83fe6f.png)

Clicking on an error pops up a window like this one:
![image](https://cloud.githubusercontent.com/assets/8616371/23308058/2370960c-faaa-11e6-87e6-be8bc3b629c6.png)

The "unable to open" files do exist.

This behavior is observed when `g++ 6.2.0` is selected as a compiler. With `clang++ 3.8.1` the PROBLEMS window works as expected.

**Comment by vector-of-bool** [comment]
This is probably a dup of #118: The parser chokes on GCC's template tracebacks. I'll have a possible fix in the next release.

**Comment by vector-of-bool** [comment]
It's been too long, but this should now be fixed in `0.9.4`. Tell me if you're still seeing this problem.
