### ISSUE TITLE
Passing command line arguments to a debug target

### ISSUE THREAD

**Issue by mkotlyar** [vector-of-bool/vscode-cmake-tools#121]
To would be nice to have an option to pass command line arguments to a debug target which is selected in CMakeTools and launched on Ctrl+F5

**Comment by vector-of-bool** [comment]
It seems like the `cmake.debugConfig` setting entry is broken, as VSCode offers no help regarding its existence. I've noticed this in the past few days, but options _should_ be settable using that config option. I'll have to play around and see why it isn't working. Until then, you can try setting `cmake.debugConfig` without any VSCode help. [See this doc](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md#configuring-the-debugger).

**Comment by vector-of-bool** [comment]
Are you unable to see `cmake.debugConfig` in the latest release?

Also, see the release notes regarding `cmake.debugTargetProgramPath`, which may be better suited for what you need.

**Comment by vector-of-bool** [comment]
Were you able to find a workable solution?

**Comment by agurz** [comment]
JFTR: I was able to pass arguments to a debug target using `cmake.debugConfig` adding a `settings.json` file inside `.vscode` folder with this content:

```json
{
    "cmake.debugConfig": {
        "args": [
            "myFirstArgument"
        ]
    }
}
```

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by industriousonesoft** [comment]
> JFTR: I was able to pass arguments to a debug target using `cmake.debugConfig` adding a `settings.json` file inside `.vscode` folder with this content:
> 
> ```json
> {
>     "cmake.debugConfig": {
>         "args": [
>             "myFirstArgument"
>         ]
>     }
> }
> ```

Thx, That's work for me.

**Comment by oridong** [comment]
> JFTR: I was able to pass arguments to a debug target using `cmake.debugConfig` adding a `settings.json` file inside `.vscode` folder with this content:
> 
> ```json
> {
>     "cmake.debugConfig": {
>         "args": [
>             "myFirstArgument"
>         ]
>     }
> }
> ```

it works for me. but how do this when run without debugger ? I read [cmake-tools](https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html#running-targets-without-a-debugger) , but it doesn't works for me,  pass of args fails.

**Comment by liwei46** [comment]
hello, why setting "args" in launch.json not working?

**Comment by andreeis** [comment]
@liwei46, launch.json is not consumed by the CMake Tools debugging or running feature, but by F5. Are you F5-ing and your binary is not receiving the args defined in launch.json?
To use arguments via the cmake.Debug command (same as status bar debug icon), define in settings cmake.debugConfig.args as 2 comments above.

**Comment by Nugrud** [comment]
"cmake.debugConfig": { "args": ["-c /path/to/cfgfile"] } in settings.json
doesn't work for me with ctrl+f5

**Comment by bobbrow** [comment]
I believe it should be one arg per string.  Can you try:
```
"cmake.debugConfig": {
  "args": [
    "-c",
    "/path/to/cfgfile"
  ]
}
```

**Comment by Tibalt** [comment]
tested with 
![image](https://user-images.githubusercontent.com/1047435/143207514-68e01e0c-cfe9-428a-ae7f-5380bd930352.png)

```
 "cmake.debugConfig": {
        "args": [
            "-c",
            "localhost:61498"
        ]
  },
```
and
```
 "cmake.debugConfig": {
        "args": [
            "-c localhost:61498"
        ]
  },
```
both failed. :(
