### ISSUE TITLE
does cmake.environment setting work? 

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#122]
do I use wrong syntax of this setting? but it doesn't work for me:
this is an adding vcpkg folders into environment variable to make this accessible for vc compiler/linker
```
    "cmake.environment": {
        "INCLUDE" : "%INCLUDE%;C:/dev/cxx/vcpkg/installed/x64-windows/include",
        "LIB" : "%LIB%;C:/dev/cxx/vcpkg/installed/x64-windows/lib",
        "PATH" : "%PATH%;C:/dev/cxx/vcpkg/installed/x64-windows/bin"
    },

```
so one of the libraries there is CatchLib (header only - catch.hpp, it is really there double checked)
but building process returns:

> 
fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory

**Comment by vector-of-bool** [comment]
Two things will prevent this from working as you probably intend it to:

1. If you are using the build environment selection feature, the active environment will override the environment variables that influence VC++ behavior, including `PATH`, `LIB`, and `INCLUDE`.
2. Environment expansion will not occur in these strings, so `%INCLUDE%;foo` will _not_ append `;foo` to the prior value for `INCLUDE`, rather the variable will literally be set to the string `%INCLUDE%;foo`.

To get the behavior you want, I recommend using CMake's `find_*` functions along with the `HINTS` option. For example:

```cmake
find_path(CATCH_INCLUDE_DIR catch.hpp HINTS C:/dev/cxx/vcpkg/installed/x64-windows/include)
```

Then you can add `${CATCH_INCLUDE_DIR}` to your `target_include_directories` when you build your target. This is preferable for more reliable cross-platform building.

**Comment by amigo421** [comment]
yeah, I'm currently using cmake's find_xxx operations,
just thou that can do this outside of cmake scripts.
but okay, thank you
