### ISSUE TITLE
debug target

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#123]
how do you think - what can be a reason of no debug target available in status line?

this is in cmakelists and user settings: 
`
cmake_minimum_required (VERSION 3.7.2)
`
`
    "cmake.experimental.useCMakeServer": true,
`
helper script does no present in cmakelists however

however I could set this from command palette via set/debug target
I mean status bar was empty initially, after selecting from command palette this was reflected in status line too

it can be easily reproduced by deleting your extension's settings json

**Comment by amigo421** [comment]
got the reason of the problem.

firstly , need to add that added debug target from command palette, didn't work because of "can't find "...\my.exe".

actually , this was not my project and I've looked at the cmakelists with more attention just now and find this:

```
set(CMAKE_BINARY_DIR ${CMAKE_SOURCE_DIR}/Build)
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)
set(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/lib)

```

you see - script sets the folders manually, but the extension looks for the exe in Build folder specified in own settings:

`            "buildDirectory": "C:/dev/workspace/Restweb/build",
`

correct? 

is it possible (for the extension) to check CMAKE variables which contain those paths?

**Comment by vector-of-bool** [comment]
That's peculiar... It should be able to find the output file, no matter what settings are used to set its path.

Setting `CMAKE_BINARY_DIR` looks extremely fishy... I'm not sure what CMake will even do in that case.

**Comment by amigo421** [comment]
for the settings above, when CMAKE_BINARY_DIR refers to the same folder as an extension setting, 
cmake did exactly what is described in cmakelists: 
 - various build files were placed into Build folder
 - exe - into Build/bin subfolder.
but debug target does still refer to unexisting exe in Build folder

**Comment by amigo421** [comment]
I suggest to close this type of issues, due the problem is in cmake

**Comment by vector-of-bool** [comment]
This problem should be fixed in the latest release.
