### ISSUE TITLE
CMake: unconfigured project

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#124]
please look at the screenshot : 
![image](https://cloud.githubusercontent.com/assets/3259933/23626309/75761f1a-02bd-11e7-914e-8dd8f9f2c39a.png)
you see that configuring and generating is done but "Unconfigured project:Debug" is there.
I suppose that "Debug" only should be there because I've selected debug configuration. 
I didn't look at this previously, but tried to load a couple more projects: all ones show the same.
also tried to delete cache , reconfigure and even the deletion whole Build folder, the same

by the way, you see generating was finished but message is still there, looks like it was not updated

please comment

**Comment by amigo421** [comment]
ah, man, I was wrong - "Unconfigured" refers to "Cmake", but "Debug" refers t "Project" isn't it?
just please explain why all this line is a single button and what means  "cmake: unconfigured', please?

> "CMake: Unconfigured Project: Debug: Ready"

**Comment by vector-of-bool** [comment]
I think this may be a problem with cmake-server support. I'm seeing it as well on my local system.

**Comment by maddouri** [comment]
I am having the same issue when `cmake.experimental.useCMakeServer` is set to `true`

**Comment by amigo421** [comment]
for sure, it happens on windows box only for me
