### ISSUE TITLE
Platform selection support

### ISSUE THREAD

**Issue by seanmiddleditch** [vector-of-bool/vscode-cmake-tools#126]
I'm not seeing anyway of passing the equivalent of CMake's `-A` option during generation.

The standard generator-based way of doing this has various drawbacks. For one, specifying it explicitly requiring overriding the generator auto-selection (I want Win64 but I want auto-selection to choose between Visual Studio 14 2013 or Visual Studio 15 2015 as normal). For two, the generator approach doesn't play nicely with alternative platforms that VS might support (mobile, game console SDKs, etc.).

I'd like to be able to set a `cmake.platform` variable or similar, which should be overridable on a per-configuration basis (e.g., any configuration overrides for generator or toolset would need to also allow platform).

**Comment by vector-of-bool** [comment]
There a `cmake.toolset` option, so I don't see why I can't add a `cmake.platform` option as well. I'll look into it.
