### ISSUE TITLE
Incorrect debug path

### ISSUE THREAD

**Issue by seanmiddleditch** [vector-of-bool/vscode-cmake-tools#127]
I have overridden the variable `CMAKE_RUNTIME_OUTPUT_DIRECTORY` but when using vscode-cmake-tools to launch a debug session, it seems to be searching for the target binary in the default CMake build directory location.

Looking in the `cmaketools.json` it looks like its just concatenating `fullName` with `buildDirectory`. The correct location of the executable only shows up under `artifacts` (along with the PDB and for some reason a LIB file).

I'm not clear on if this is a problem with the cmake-server itself or with the cmake-tools usage thereof.

**Comment by vector-of-bool** [comment]
Same issue as #123. It appears that `cmake-server` doesn't properly name the output file path as I expected it to. I may open a PR to CMake upstream to get something like a `primaryArtifact` attribute that does what I want.

**Comment by ngladitz** [comment]
Doesn't the first entry in "artifacts" already match that use case?

**Comment by vector-of-bool** [comment]
It possibly does, I'll take a closer look when I get the chance. (Sorry for the delay on this issue.)

**Comment by seanmiddleditch** [comment]
My only concern there is whether the first entry of `artifacts` is guaranteed to be the correct path or if it just happens to be what we're looking for in the common cases. It might be a decent fallback for now, but I'm not sure it sure be trusted as the definitive solution.

**Comment by ngladitz** [comment]
FWIW "artifacts" are documented to be ordered by "importance". From what I can tell Tobias Hunger who implemented this in CMake's server code also seems to use it for the same purpose in QtCreator.
