### ISSUE TITLE
Duplicate cmakePath variables in default settings

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#13]
Hello,
VSCode is currently giving me a warning that there is "duplicate object key" in the /settings.json. Note that this is the defaults, not my user or my workspace settings. I am not actually sure whether this exists as a real file, or is somehow generated by VSCode? If I click on the warning, I see these lines:

    // The preferred CMake generator(s) to use when configuring (tried in order of listing)
    "cmake.preferredGenerators": [
        "Ninja",
        "Unix Makefiles",
        "MinGW Makefiles",
        "NMake Makefiles"
    ],

    // The path to CMake generator executable
    "cmake.cmakePath": "cmake",

    //-------- CMake configuration --------

    // The path to CMake generator executable
    "cmake.cmakePath": "cmake",

However I can't edit this 'file', so I can't remove the duplicates. Any ideas?

**Comment by vector-of-bool** [comment]
The issue looks like a conflict between my extension and @twxs's extension, as both have that config key. I've had both extensions installed for a while, but never seen an actual warning about it...

Where is the warning appearing? A popup? A log message? Also, what version of VSCode are you running?

**Comment by spinicist** [comment]
Ah, that makes sense. I have @twxs's extension installed too.

I'm running 1.1.1. In the blue bar at the bottom of the editor, there is a group of three icons - a cross in a circle, a triangle with a ! and a circle with an upside down !. When I click on it a dialog pops-up and the Duplicate Object Key is the first warning listed. I only discovered this pop-up today!

**Comment by twxs** [comment]
I'm running 1.1.1 (on Windows) too and have both extension installed but I never noticed the warning until I opened the `User Settings` the warning comes from the generated `Default Settings`.

You can safely ignore the warning as the both extensions perform the same things with that key config.

When I have added that key config I feared that it could happen... But it should be really annoying to add another object key for the same thing... @vector-of-bool have you any idea to share this option between our two extensions?

**Comment by vector-of-bool** [comment]
I honestly doubt anyone would install my own extension without also installing yours for working with CMake code. It would probably be safe enough for me to simply remove the option from my ``package.json`` but still use the setting and leave it documented.

**Comment by twxs** [comment]
Another option would be to create a third extension and use `extensionDependencies` to share some of our config keys.

For now the CMake executable  is the only key we shared but I'm working on a CMake parser to provide some additional features like code format, CMake linter, code refactoring and I certainly need in a near future the path to the `CMakeCache.txt`.

I can also add a dependency to your extension...

**Comment by vector-of-bool** [comment]
Sorry for the delay.

I think it would be best if I added your extension as a dep rather than vice versa. It seems to make more sense that way.

Or perhaps some sort of merge...?

**Comment by neumannrf** [comment]
Hi @vector-of-bool and @twxs, besides congratulating you on the nice extensions, I ask: do we have a solution/workaround for this?

**Comment by vector-of-bool** [comment]
I think my best option is to add @twxs's extension as a dep.

**Comment by twxs** [comment]
Yes, It seems to be the easiest solution if we want to remove this warning shortly.

Again, as our 2 extensions use that key to store the same property, the warning can be safely ignored... 

> Or perhaps some sort of merge...?

It could nice to "merge" the 2 extensions as they are complementary to each other. 
But I've started a big feature on my side and I think it won't be a good idea merge before it will be finished.
But I remain open....

**Comment by neumannrf** [comment]
@vector-of-bool, regarding your suggestion, is that something I can do locally editing some sort of `settings.json` file or something to be done in the extension source itself?

**Comment by vector-of-bool** [comment]
Unfortunately, no. I don't see any viable workaround for users. I'll have to update my own dependencies. That change should come soon. Until then, the warning is fairly benign.

**Comment by vector-of-bool** [comment]
Ouch! I seem to have let this one last a while... Next release will finally fix this warning fixed. I've added a dep on the CMake language extension, finally.

**Comment by vector-of-bool** [comment]
Not a surprise, actually. I'm preparing for multi-root workspaces and it required that I pull in the definition of that setting. The txws.cmake setting is incompatible with multi-root workspaces.

**Comment by twxs** [comment]
Hi, really busy here, but if this warning is really annoying I could look to rename the  setting on my side...

**Comment by webbnh** [comment]
The problem is that it's hard to maintain a zero-warnings approach when I've always got a non-zero number of warnings (due to stuff that I cannot fix).  It's not a _critical_ issue, but it is kind of serious....
