### ISSUE TITLE
How to write debugconfig for pass command line arguments

### ISSUE THREAD

**Issue by lxq** [vector-of-bool/vscode-cmake-tools#131]
I've read some docs, but I'm confused. I do not understand how to set for passing arguments , when debuggin.

**Comment by vector-of-bool** [comment]
Sorry for being slow to respond, I've been busy with "real life" stuff.

I'm not entirely happy with the way target debugging works ATM. I think that I can make it much simpler, and it is especially frustrating that configuring the debugger is so far separated from the regular way to set up other CMake debug configurations.

Have you looked at the documentation for the C/C++ extension's debugger setup?

**Comment by vector-of-bool** [comment]
To follow up with this:

You can now use `launch.json` to setup your debugger. Use the string `${command:cmakeDebugTargetProgramPath}` (Soon to be changed to `${command:cmakeLaunchTargetProgramPath}`)

VSCode will ask CMake to provide the path to the active target, and CMake Tools will build that target before launching the debugger.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
