### ISSUE TITLE
CMake server: Unable to determine CMake Generator to use

### ISSUE THREAD

**Issue by letmaik** [vector-of-bool/vscode-cmake-tools#132]
After upgrading my cmake install to 3.7.2, enabling the cmake server option in the vs code settings, and restarting vs code, I get the message: "Unable to determine CMake Generator to use". When I click on the "cmake: ..." in the status bar it says "command 'cmake.setBuildType' not found". I'm using cmake tools 0.9.3.

**Comment by vector-of-bool** [comment]
Sorry for the delay. "Real life" gets in the way sometimes.

What platform/toolchain are you using where you are seeing this problem?

**Comment by letmaik** [comment]
I just tried it again (same error) with cmake tools 0.9.4, cmake 3.7.2, Windows 10, and vs code 1.10.2.

**Comment by ytimenkov** [comment]
As a work-around it's possible to add "cmake.generator" setting, look at cmake.preferredGenerators for examples.

**Comment by kirbysayshi** [comment]
I tried adding "Unix Makefiles" to the list of preferredGenerators, but clicking on the toolbar buttons in order gives the following error messages:

![screenshot 2017-04-13 18 45 50](https://cloud.githubusercontent.com/assets/90831/25027292/7c043cfc-2079-11e7-9cb9-fb694a421aab.png)

**Comment by ytimenkov** [comment]
@kirbysayshi You should change "cmake.generator" instead. My Workspace settings look like:
```
// Place your settings in this file to overwrite default and user settings.
{
    "cmake.generator": "Ninja",
    "cmake.configureSettings": {
        "CMAKE_MAKE_PROGRAM": "L:/tools/ninja.exe"
    }
}
```
(I don't have ninja in my path by default)

**Comment by kirbysayshi** [comment]
@ytimenkov setting `cmake.generator: "Xcode"` does work, but shouldn't the plugin use preferredGenerators without throwing an error?

To be clear:

- `"cmake.generator": "Xcode"` succeeds
- `"cmake.preferredGenerators": ["Xcode"],` (without `cmake.generator` set) throws an error "Unknown CMake generator "Xcode"".

**Comment by kirbysayshi** [comment]
In addition, at least on my computer, ninja also fails:

```
$ ninja --version
1.7.2
$ which ninja
/usr/local/bin/ninja
```

`"cmake.generator": "Ninja"` -> click "CMake: Unconfigured Project: Debug: Ready" -> throws "command 'cmake.setBuildType' not found"

**Comment by vector-of-bool** [comment]
Sorry for disappearing again.

The "command `cmake.foo` not found" is an error relating to extension startup.

`Xcode` should work as a generator in the next version.

**Comment by vector-of-bool** [comment]
There's a ticket in for improving error messages when extension startup fails. Until then, could I get more platform and environment info, as well as basic project details? (ie, projects, tests, settings)

**Comment by vector-of-bool** [comment]
Does the most recent version fix this issue? Does it provide any more helpful error messages?

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by logicle** [comment]
Even with 0.11.0-beta4, I cannot get the VS2017 generator working. 

My user settings include:
	"cmake.generator": "Visual Studio 15 2017",
	"cmake.preferredGenerators": [
		"Visual Studio 15 2017"
	  ],

Just trying to get the simplest "Hello world" project going to see how CMake integration works, but it is blowing up on the launchpad for me. When I build, I get:
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Unable to determine CMake Generator to use {}

I can build everything from the command line (generate a VS2017 project, build it using cmake, run the program, etc..)

**Comment by vector-of-bool** [comment]
@logicle, have you tried the beta5? I just pushed it out a few days ago, and I believe it addresses this problem (contrary to what the closing comment says).

**Comment by bessszilard** [comment]
The error occured, for me also. I use:
Cmake 3.7.2
CMake Tools 1.1.3
VS Code 1.35.0
Windows 10, WSL

With Cmake 3.5.1 worked fine, which I installed with apt-get. I updated to 3.7.2 version, and error appeared. Further more, the project Configuration stucks at "Saving open files".
