### ISSUE TITLE
nmake path problem

### ISSUE THREAD

**Issue by techcap** [vector-of-bool/vscode-cmake-tools#135]
I'm using CMake Tools v0.9.3.

I used setttings.json
``
{
    "cmake.generator": "NMake Makefiles",
    "files.associations": {
        "xlocale": "cpp"
    }
}
``

When I build on vscode, it says like this
``
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "all"
``

If I run "nmake /NOLOGO all" in command prompt, it works properly.
I added nmake path to system variable path. 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

But Vscode still cannot detect nmake.

Any suggestion?

**Comment by vector-of-bool** [comment]
There have been recurring problems with environment variables, and my guess is that this is one of those instances. Do you have any settings related to environment variables? Are you using the build environment selector?

**Comment by techcap** [comment]
I added nmake path to user environment variable path.
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
I don't know the build environment selector.

**Comment by vector-of-bool** [comment]
The environment selector is a statusbar button on the bottom right to the left of the line/column indicator. Do you have any environments active? Those will alter environment variables. Adding VC++ toolchains to your path is unusual, I believe. The environment selector _should_ let you work with VC++ without needing to alter any environment variables manually.

**Comment by techcap** [comment]
I chose the build environment selector. After this, it works!
Thank you very much~~~^^
