### ISSUE TITLE
Configured debug type 'cppdbg' is not supported.

### ISSUE THREAD

**Issue by bkeys** [vector-of-bool/vscode-cmake-tools#139]
I get this error when I do not have the proprietary C++ extension installed. I looked and the relevant files are cmake.js and common.js
Could you please fix this so that the add on is more usable without relying on proprietary add ons?

**Comment by vector-of-bool** [comment]
I can look into this. There are a few changes I've been looking into making in the way the debugging works. I'll see what I can do.

**Comment by bkeys** [comment]
Thank you, if there is anyway I can help (development wise) feel free to let me know. I am really eager to get this working.
It would also be really nice if I could run my program without a debugger at all.

**Comment by vector-of-bool** [comment]
I added a command `cmake.debugTargetProgramPath` that can be used in `launch.json` (see the latest release notes for more info).

It isn't as built-in as the current debug button, but it may be sufficient. What do you think?

**Comment by bkeys** [comment]
I can already launch the program via the built in debugger in vscode; ideally you would have something like this bar
![selection_346](https://cloud.githubusercontent.com/assets/12195202/24390343/e5a4be54-134d-11e7-94b2-4d39dc05a632.png)
However I cannot get it working; you should document which version of the dependency works because it does not appear to work on all versions.

**Comment by vector-of-bool** [comment]
What version/platform are you working on? What does your `launch.json` look like?

**Comment by bkeys** [comment]
I used your release on vscode 1.10, when I use your extension directly it seems to break with the other cmake addon you depend on
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "gdb",
      "request": "launch",
      "name": "Server",
      "target": "./build/dmux-server",
      "cwd": "${workspaceRoot}"
    },
    {
      "name": "Client",
      "type": "gdb",
      "request": "launch",
      "target": "./build/dmux",
      "cwd": "${workspaceRoot}"
    }
  ]
}
```

**Comment by vector-of-bool** [comment]
How does it break? What kind of errors are you seeing?

**Comment by bkeys** [comment]
Configured debug type 'gdb' is not supported.
Keep in mind this is with the built in debugger; your cmake plugin broke due to incompatibility with the other cmake extension

**Comment by vector-of-bool** [comment]
What kind of incompatibility are you seeing? I'm unable to see anything wrong on my local install.

**Comment by bkeys** [comment]
Are you using your most recent release? Could you tell me which version of both add ons you are using?

**Comment by vector-of-bool** [comment]
I have VSCode 1.10.2, CMake extension 0.0.17, CMake Tools 0.9.4

**Comment by bkeys** [comment]
Tried it out on a fresh install and it seems to no longer be broken.
However, I do not see any option to debug anymore
How do you debug? I cannot seem to get any launch configuration going in the built in debugging GUI

**Comment by vector-of-bool** [comment]
The status-bar button is still hard-coded to use MS's cpptools ext, so I just hid it if that ext is missing.

The `${command:cmake.debugTargetProgramPath}` is mostly there to help get the binary path and switch between executables without having too many `launch.json` entries.

**Comment by bkeys** [comment]
I just gave a path to my project's binary and I get a 
"Debug adapter process has terminated unexpectedly"
message. Here is my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceRoot}/build/dmux",
            "args": [],
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

**Comment by bkeys** [comment]
Ideally it would be nice if the button was there and the extension did not depend at all on MS's tools; and if it gave me the option of whether or not to run my CMake target in a debugger that would be nice too. This is really the last thing I need out of vscode before I jump completely into using it

**Comment by vector-of-bool** [comment]
Odd... Is that executable built? I don't think that this case is related to CMake Tools specifically, though.

**Comment by bkeys** [comment]
Yes the executable is indeed there
Would it be possible to not use launch.json at all and just use the CMake targets?

**Comment by vector-of-bool** [comment]
I'm still wanting to get more into better debugger support besides cpptools, but I just wanted to get a few issues cleared out of the way today. I'll definitely take a look at more debuggers in the future, and I'm hoping that better extensions that cpptools will become available going forward.

Launching a debugger requires generating the debugger config on-the-fly, which requires knowledge of the schema of a debugger's config options (what goes into the `launch.json`). At the moment, CMake Tools only generates cpptools' config object. Adding other extensions is definitely possible, just not something I've put much time into.

**Comment by bkeys** [comment]
Mmhm, how difficult would it be to launch the project without any debugger at all?

**Comment by vector-of-bool** [comment]
That wouldn't be too difficult. It could even be launched using the terminal API to get proper TTY behavior. That's also something to look into.

**Comment by bkeys** [comment]
Yeah ideally for me I would have the option to invoke the debugger or not, and would have the choice of which CMake target to launch. I dunno how this would tie into actually implementing it. I wish there was more I could do to help.

**Comment by vector-of-bool** [comment]
Should be able to launch without a debugger in next update.

**Comment by ytimenkov** [comment]
There are also documentation improvements in CMake Tools 0.10.0. Shall this issue be closed?

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by vladipus** [comment]
Seems like the command is now ${command:cmake.launchTargetPath} that can be used in the launch.json file like so:
```json
{
      "name": "Cmake Debug Target",
      "type": "lldb",
      "request": "launch",
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "cwd": "${workspaceFolder}"
}
```
This can also be set in your workspace settings like so:
```json
"cmake.debugConfig": {
      "name": "Cmake Debug Target",
      "type": "lldb",
      "request": "launch",
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "cwd": "${workspaceFolder}"
    }
```
