### ISSUE TITLE
cmake.platform seemingly ignored

### ISSUE THREAD

**Issue by seanmiddleditch** [vector-of-bool/vscode-cmake-tools#141]
The fix for #126 does not seem to be working for me. vscode 1.10.2, cmake-tools 0.9.4, cmake 3.8.0rc2, Visual Studio 25 2017, Windows 10.  I've verified that everything works if I manually invoke cmake with the -A option after setting the correct environment variables. My `settings.json` has:

```
{
    "files.associations": {},
    "cmake.sourceDirectory": "${workspaceRoot}/source",
    "cmake.buildDirectory": "${workspaceRoot}/build/win64",
    "cmake.generator": "Visual Studio 15 2017",
    "cmake.platform": "x64",
    "cmake.buildToolArgs": [
        "/verbosity:minimal"
    ]
}
```

Note that I've tried a platform of `Win64` too but neither works.

The configuration output:

```
-- The C compiler identification is MSVC 19.10.25017.0
-- The CXX compiler identification is MSVC 19.10.25017.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
```

Note that it's using `HostX86/x86/cl.exe`.

The only way I can force a Win64 build is to use the general Visual Studio 15 2017 Win64.

I'm suspicious of the code around https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/environment.ts#L59 or some of the logic around https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/environment.ts#L182 but I don't know if those are to fault.

**Comment by seanmiddleditch** [comment]
Hmm, I'm thinking this might be a setup problem on my end. After rebooting I'm getting lots of cmake errors in general from cmake-tools (not being able to find commands and such).

**Comment by vector-of-bool** [comment]
The two lines you highlighted are related specifically to build environment selection. I suppose if the wrong version of `cl` is found on the path, the `-A` argument may not have the desired effect. I myself have never used the `-A` argument, so I'm not sure how it should interact or what kind of effects it should have.

**Comment by seanmiddleditch** [comment]
Reinstalling VS 2017 seems to have fixed the general cmake issues I mentioned in my previous comment. However, the core bug here is the same: the `cmake.platform` is definitely not working still.

There are no modifications to my `PATH` concerning the VS compilers and I have a stock bare-bones VS2017 15.1, VSCode 1.11.2, and CMake 3.8.0 installs. Howevever cmake-tools is even finding the compiler is unrelated to the `PATH` so far as I can tell.

Further, I note that out-of-the-box, the following `build.bat` file successfully builds as x64:

cmake -Bbuild/win64 -Hsource -A x64
cmake --build build/win64 -- %*

I don't even need to specify a generator for it to work correctly, as the default seems to be correct for CMake. Early output to show that it works correctly:

```
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
```

So far as I can tell, it's only inside of VSCode with cmake-tools that the target platform selection is failing to work correctly.

**Comment by vector-of-bool** [comment]
Sorry for the absence. I've been preoccupied.

Are you making use of the build-environment selection? That feature will set environment variables when it needs to execute commands.

**Comment by seanmiddleditch** [comment]
> Are you making use of the build-environment selection? 

I don't know the answer to that question. :) What are you referring to? I'm just using stock VSCode and stock cmake-tools plugin, with the configuration I provided above.

**Comment by vector-of-bool** [comment]
I've been away for a while, but I'm back now.

I'm inclined to attribute this to a strange interaction between environment vars, generators, etc.

As a solution that's "not-a-solution", does the build environments selector work in place of setting the platform? The build environment selector is in the bottom right side of the statusbar, currently only visible on Windows.

**Comment by seanmiddleditch** [comment]
@vector-of-bool - "build environments selector" ? what's that and how to do I activate it?

This seems to continue to be a problem. I have to very explicitly ask for the right CMake generator to get anything to work. May be unrelated, but all of the default behavior of the box seems to also be broken on my machine; logs indicate that cmake-tools knows I'm using VS 2017 Community but it's seemingly not passing the right args and CMake fails to detect the compiler.

This all might be a lot easier to debug if there was a log I could grab and inspect about what cmake-tools is doing and why. Does such a log exist already? The CMake logs just indicate that it's not getting the right settings or env. variables.

**Comment by vector-of-bool** [comment]
Recent changes have added some more logging (to the output channel), which may add some helpful information. You can enable more verbose logging by setting `cmake.loggingLevel` to `verbose`. All the logs will go to the `CMake/Build` output channel in the "Output" pane.

The "build environments selector" (I really need a better name for it) is in the bottom right-hand corner of the window and shows up if CMake Tools is able to detect environments in which one can compile programs, such as Visual Studio(s) and MinGW. The logging about VS 2017 is related to the environment detector finding your 2017 installation. It won't actually make use of the environment unless you request it. You can force the dialog to appear with the command palette: `CMake: Select active build environments`.

Some pending updates will fix issues with interactions between the environment detection and Visual Studio generators.

Sorry to take so long on this: The Visual Studio Generators/environments/craziness are all very convoluted and strange. I only ever use Ninja on Windows and just set the environment to use the platform I want, so I haven't had to deal with my own extension's flaky Visual Studio/MSBuild support.

**Comment by extratype** [comment]
Does this have something to do with the leading blank of vsMatch[2] at
https://github.com/vector-of-bool/vscode-cmake-tools/blob/06916228bc4a1abda3f7385797e1943160bd7f1e/src/common.ts#L283
?

**Comment by vector-of-bool** [comment]
@extratype, not sure what you are referring to?

@seanmiddleditch, I have to apologize for letting this issue sit stale. I have no leads on it, and no one else is really using the platform option and having the same issue. The Visual Studio generators are the saddest part of CMake, and often lead to strangeness like this. I know it's not a real solution, but have you tried Ninja?

Were you able to make any discoveries since my last comment?

**Comment by extratype** [comment]
For example,
```javascript
gen.name: 'Visual Studio 15 2017 Win64'
vsMatch[1]: 'Visual Studio 15 2017'
vsMatch[2]: ' Win64'
```

**Comment by extratype** [comment]
I was able to build successfully with VS2017 x64 generator.
```json
    "cmake.generator": "Visual Studio 15 2017",
    "cmake.platform": "x64",
```
This configuration worked. I guess my last comment is related to `cmake.preferredGenerators` option which didn't work.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
