### ISSUE TITLE
Is xcode supported as a generator?

### ISSUE THREAD

**Issue by kirbysayshi** [vector-of-bool/vscode-cmake-tools#146]
As far as I can tell from the code, Xcode is rejected as a cmake generator. Using `Xcode` in the list of preferredGenerators throws an `Unknown CMake generator "Xcode"` error.

**Comment by vector-of-bool** [comment]
All generators should be supported. If you aren't able to use one, that's a bug. Thanks for notifying me. I don't have any macOS systems to work with, so this isn't something that's come up for me.

**Comment by Dids** [comment]
Also seeing this. Using `Xcode` as the `cmake.generator` works (apart from https://github.com/vector-of-bool/vscode-cmake-tools/issues/147), but having `Xcode` under `cmake.preferredGenerators` _before_ including `Unix Makefiles`produces the error above.

**Comment by vector-of-bool** [comment]
Sorry to take so long on this. I've been busy IRL.
