### ISSUE TITLE
All target incorrect for Xcode

### ISSUE THREAD

**Issue by BJMH** [vector-of-bool/vscode-cmake-tools#147]
I'm not sure if this is the case across-the-board, but in my experience so far the default 'all' target for Xcode projects produced by CMake is `ALL_BUILD`, just like with Visual Studio. However on common.ts the function 'get allTargetName()' only returns `ALL_BUILD `for VS and `all `otherwise, with:

`return (gen && /Visual Studio/.test(gen)) ? 'ALL_BUILD' : 'all';`

Perhaps this needs an OR with `/Xcode/.test(gen)` or however the extension refers to Xcode?

**Comment by vector-of-bool** [comment]
So sorry for the delay! I've been busy.

Thanks for investigating this issue. I'll get on it as soon as possible.

**Comment by BJMH** [comment]
Thanks so much, I really appreciate your work.

**Comment by Dids** [comment]
Also seeing this. Xcode project definitely has `ALL_BUILD` instead of `all` as the target.

```
xcodebuild: error: The project 'hello-vsc.xcodeproj' does not contain a target named 'all'.
```
