### ISSUE TITLE
Cannot debug: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by endorph-soft** [vector-of-bool/vscode-cmake-tools#148]
I'm having an issue setting up debugging using CMake Tools.

Every time I try and debug, I get the following error:

    Cannot read property 'Symbol(Symbol.iterator)' of undefined

I have followed the instructions [here](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md), and added the following line to my CMake file:

    include(CMakeToolsHelpers OPTIONAL)

Have I missed something?

Environment:
* Ubuntu 16.04
* CMake 3.5.1
* VS Code 1.11.2
* Extensions: C/C++ (Microsoft, 0.10.5), CMake (twxs, 0.0.17), CMake Tools (vector-of-bool, 0.9.4)

**Comment by endorph-soft** [comment]
I also have the same issue under Windows 10, with Visual Studio 2017.

Here's the output of developer tools:


    
    undefined
    [Extension Host] Execute cmake with arguments: ["-C{redacted}\build\CMakeTools\InitializeCache.cmake", "-H{redacted}", "-B{redacted}/build"]
    [Extension Host] [cmake output]: loading initial cache file {redacted}\build\CMakeTools\InitializeCache.cmake
    [Extension Host] [cmake output]: Windows Host Detected
    [Extension Host] [cmake output]: 32 bit compiler detected
    [Extension Host] [cmake output]: -- Configuring done
    [Extension Host] [cmake output]: -- Generating done
    [Extension Host] [cmake output]: -- Build files have been written to: {redacted}/build
    [Extension Host] cmake exited with return code 0
    Cannot read property 'Symbol(Symbol.iterator)' of undefined
    Cannot read property 'Symbol(Symbol.iterator)' of undefined: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
        at CMakeTools.<anonymous> (C:\Users\{redacted}\.vscode\extensions\vector-of-bool.cmake-tools-0.9.4\out\src\legacy.js:151:51)
        at next (<anonymous>)
        at fulfilled (C:\Users\{redacted}\.vscode\extensions\vector-of-bool.cmake-tools-0.9.4\out\src\legacy.js:4:58)
    WARNING: Promise with no error callback:88
    Object {exception: null, error: Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
        at CMakeTools.<anonymous> (C:…, promise: n.C…s.d…e._oncancel, handler: undefined, id: 88…}error: Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
        at CMakeTools.<anonymous> (C:\Users\{redacted}\.vscode\extensions\vector-of-bool.cmake-tools-0.9.4\out\src\legacy.js:151:51)
        at next (<anonymous>)
        at fulfilled (C:\Users\{redacted}\.vscode\extensions\vector-of-bool.cmake-tools-0.9.4\out\src\legacy.js:4:58)exception: nullhandler: undefinedid: 88parent: undefinedpromise: n.Class.derive._oncancel__proto__: Object

**Comment by pvaibhav** [comment]
Just adding another data point: latest VScode on macOS and CMake 3.8 has the same error.

**Comment by vector-of-bool** [comment]
So sorry for the delay.

I'll take a look: the traceback will be useful.

This only happens when trying to debug?

**Comment by endorph-soft** [comment]
No worries about the delay. I've been involved in these sort of projects before, and I'm aware that sometimes other stuff gets in the way.

It seems to also happen on builds, when I press F7. If you want any other details, let me know.

**Comment by DavidPeicho** [comment]
Hi, just to let you know that the bug is also on Ubuntu 16.04

**Comment by dwarburt** [comment]
I think it happens when the CMakeToolsMeta-Debug.txt file is empty, at least that was it for me.  PR incoming.
