### ISSUE TITLE
Request: Load/Show subdirectories added to the project with add_subdirectory 

### ISSUE THREAD

**Issue by heretique** [vector-of-bool/vscode-cmake-tools#149]
Hi,

I've used VSCode with Cmake Tools and I'm starting to love it. Actually the only reason stopping me from switching from QtCreator is the lack of this feature. If possible would be nice to have this feature. QtCreator loads also the Cmake files for the sub-projects and builds them if necessary. The attached image shows how QtCreator displays them.

Thanks,
Catalin

<img width="334" alt="screen shot 2017-04-23 at 12 04 39 pm" src="https://cloud.githubusercontent.com/assets/139596/25312288/61882d1e-281e-11e7-8c2c-d812b94eab37.png">

**Comment by vector-of-bool** [comment]
Thanks for your patience. I haven't had the opportunity to check back for a while.

This particular use case is one that I'm wanting to implement but will require support from VSCode upstream. They have an unstable/proposed API for custom tree views, and I'm hoping that it will get merged specifically so I can support project tree-views just like this. [The API is currently in-development](https://github.com/Microsoft/vscode/issues/15485). This type of use-case will be the first thing I look at when (if) it gets merged.

**Comment by heretique** [comment]
This is great news, I can hardly wait :D

**Comment by vector-of-bool** [comment]
Good news: The May update should finally publicize a new custom-tree-explorer API. Should see this implemented in CMakeTools soon after. (Depending on how long it takes to get sorted)

**Comment by glaure** [comment]
Any news on this?
I am in the same situation as heretique. Lot of subprojects in parent directories ...

**Comment by vector-of-bool** [comment]
I was able to get a simple tree view for cmake projects started, but I never got the whole thing worked out. I'm hoping to address this after a current refactor.

**Comment by vector-of-bool** [comment]
Hey! I've actually got a PR open for this now! Should see it done in 1.1.0.
