### ISSUE TITLE
Notification when the default build target is changed

### ISSUE THREAD

**Issue by maddouri** [vector-of-bool/vscode-cmake-tools#155]
Hi,

First of all, THANK YOU for this extension. It really saved me a lot of trouble when using VSCode :)

After reading #22 and https://github.com/Microsoft/vscode-cpptools/issues/156, I wanted to code a small extension that would use CMake Tools in order to add the includes/defines to `c_cpp_properties.json` automatically. (and use it until the better approaches are implemented and available ;)

So far, I have implemented an `update c_cpp_properties` action that achieves my basic goal. (mainly thanks to CMake Tools' exported `CMakeToolsWrapper`) I have even managed to get Microsoft's cpptools extension to use the currently selected CMake target+configuration.

However, I still need to launch the `update c_cpp_properties` action manually each time I change the active CMake target -- i.e. each time I use CMake Tools' `setDefaultTarget`, I also have to manually execute my extension's `update c_cpp_properties`.

I think that it would prove useful if CMake Tools provided an event (e.g. `onDefaultTargetChange`) that other extensions could listen to. Basically, such an event would allow me to implement something like:

```typescript
// called once (e.g. during my extension's activation)
registerBuildTargetListener() {
    let cmakeTools = vscode.extensions.getExtension("vector-of-bool.cmake-tools");
    cmakeTools.exports.onBuildTargetChange(newTargetName => {
        // use newTargetName...
    });
}
```

I am aware that the value that I am looking for is in `CommonCMakeToolsBase.defaultBuildTarget`. I can read it using something like:

```typescript
let cmakeTools = vscode.extensions.getExtension("vector-of-bool.cmake-tools");
cmakeTools.exports._impl.then(cmakeToolsWrapper => {
    const activeTargetName = cmakeToolsWrapper.defaultBuildTarget;
    // use activeTargetName...
});
```

but I couldn't find a way to "listen" to this value's changes. (disclaimer: I am a total beginner in TypeScript. If there is actually a way to listen to such values' changes without requiring special support from CMake Tools' side, feel to correct met, I'll gladly use it :)

In general, it might prove useful for other extensions (that depend on CMake Tools) to be notified by any changes to the project, (e.g. on build type change, on target change, on CMakeLists.txt change, etc.) but for now, getting notified by the change of the default build target would be a nice addition to this (already feature-rich) extension.

Thanks in advance for considering this request.

**Comment by maddouri** [comment]
Quick followup: I managed to hack something using [proxy-observe](https://www.npmjs.com/package/proxy-observe) on the status bar object since it is:
1. An object (required for proxy-observe)
2. Is updated when the target name changes

The code is available here https://github.com/maddouri/vscode-cmake-tools-helper/blob/0.0.3/src/state.ts#L30)

**Comment by vector-of-bool** [comment]
Sorry for the delay. I've been busy with real life. Although I will still be predisposed for a while longer, I feel this is a question I should address.

You've seen #22, the oldest open issue I have. I was waiting for the cpptools extension to finally integrate with the API I already have for CMake Server access. I'm a bit irked that I still haven't received any word or response for this. At this point, I'm tired of waiting for this to be added to their extension.

I can add an API endpoint that emits an event on target change, then you can use the official API to do what you need, rather than reach down into the internal guts.

Alternatively, how would you feel about merging this work into the CMakeTools extension proper, closing #22? That way there is no fussing with API changes or incompatibilities, and all users will automatically get these improvements for free.

**Comment by maddouri** [comment]
Thanks for taking the time to reply.

I share your frustration with the current state of cpptools (and other C++ tools in VSCode in general... but I understand that everyone is doing their best though ;) which is why published CMake Tools Helper.

I know that my initial request is for notifications about target changes, but if you are open to consider it, may I suggest that you also add API endpoints for when:
* A target changes (initial request, avoids the need to "reach down into the internal guts")
* A configuration (Debug, Release, etc) changes (avoids the need to place a file watcher on `.cmaketools.json`)
* A generator (`cmake -G`) and/or a toolset (`cmake -T`) changes (might changes the include paths and/or defines)

It would be really nice to have the feature integrated in CMake Tools directly. However, wouldn't that add some (loose) "coupling" with cpptools? (i.e. generating cpptools-specific json file) I would like to still have a choice in the (hopefully near) future between using cpptools or [clangd](https://clang.llvm.org/extra/clangd.html) ([this exension](https://reviews.llvm.org/diffusion/L/browse/clang-tools-extra/trunk/clangd/clients/clangd-vscode/)) without CMake Tools generating files that are not needed.

What do you think?

**Comment by vector-of-bool** [comment]
I wouldn't mind adding such loose coupling with that extension. (The debugger launch code is already more tightly written against the cpptools ext).

Adding notification APIs isn't difficult. Also, take a look at `src/api.ts` for a proper API to this extension. It may not be in its final state, but its a start.

**Comment by maddouri** [comment]
Thanks for the info. I'll see what I can do.

In the mean time, I played a little bit with the API to get a feel of how things work and how I could implement the notification I wanted: You seem to export a `wrapper.CMakeToolsWrapper`. (which implements `api.CMakeToolsAPI`)

I have noticed the presence of the "reconfigured" event in the API, so I tried to use it instead of the file watcher on  `.cmaketools.json`:

```typescript
let cmakeTools = vscode.extensions.getExtension("vector-of-bool.cmake-tools");

cmakeTools.exports.reconfigured(() => {
    vscode.window.showInformationMessage('reconfigured from exports');
});

cmakeTools.exports._impl.then(impl => {
    impl.reconfigured(() => {
        vscode.window.showInformationMessage('reconfigured from _impl');
    });
});
```

When I reconfigre a CMake project, the only message that is shown is the second one: (i.e. `'reconfigured from _impl'`)

Is that the expected behavior?

(again, TypeScript noob here, but I assumed that [`wrapper.ts:163`](https://github.com/vector-of-bool/vscode-cmake-tools/blob/0.9.4/src/wrapper.ts#L163) would have the effect of "forwarding" `CMakeToolsWrapper._impl.reconfigured` to `CMakeToolsWrapper.reconfigured`, which would cause my code to display both messages)

**Comment by vector-of-bool** [comment]
The API has been there for a while, but been unused. If there are bugs, I'm not surprised.

Good news is my time has been freed up, so I should be able to get back to the large bug backlog.

**Comment by maddouri** [comment]
Great new, thanks!

I took the liberty of submitting a PR for solving the initial issue (getting notified when the build target changes)

Regarding merging the work (ugly workaround/hack IMHO) that allows cpptools to take into consideration the includes and defines found by CMake Tools: I am definitely for it! Let's talk about it in https://github.com/maddouri/vscode-cmake-tools-helper/issues/2
