### ISSUE TITLE
Cmake command line options

### ISSUE THREAD

**Issue by simon-p-r** [vector-of-bool/vscode-cmake-tools#16]
Hello
Thanks for this nice module!

How can I pass command line parameters to CMake?  I see property cmake.initialBuildType which I want to configure different build types to different keys, is it possible to map this to a keybinding?  Sorry very new to visual code!

Thanks
Simon

**Comment by vector-of-bool** [comment]
It depends on what you are trying to pass on the command line. Do you want to set the build type? Do you want to set CMake options via ``-D``?

To change the build type quickly, you can click on the project name next to the *Build* button on the bottom bar (This quickly changes the ``-DCMAKE_BUILD_TYPE=...`` option on the CMake command line).

To set ``-D`` options, set ``cmake.configureSettings`` in ``settings.json`` to be a map between options and values:

~~~json
{
  "cmake.configureSettings": {
    "BUILD_TESTING": true,
    "SOME_OPTION": "Cats",
    "OTHER_OPTION": "Dogs"
  }
}
~~~

**Note**: Do *not* set ``CMAKE_BUILD_TYPE`` in ``cmake.configureSettings``. Rather, use the status bar button to change the build type, or invoke the *CMake: Set build type* command from the command palette.

**Comment by vector-of-bool** [comment]
@simon-p-r, do you have any further questions? May I close this issue?

**Comment by simon-p-r** [comment]
Close if you want, sorry I have had time to try your suggestions yet. I started using cmake-js which works better than plain cmake.
