### ISSUE TITLE
all build target missing?

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#162]
Hello,
As part of diagnosing #94, I updated my CMake to 3.8.2. I assume this means that I am now using CMake Server.

The ```all``` target is no longer listed as something I can build. Similarly, ```clean``` and ```install``` only seem to be available from the relevant commands/key-bindings.

I preferred having all of the above available as build targets to pick (saves on key-bindings too!)

**Comment by vector-of-bool** [comment]
I obtain the target list straight from CMake-server. This is likely a side-effect of doing that.

**Comment by spinicist** [comment]
I guessed that might be the case. Would you like me to file an issue at https://gitlab.kitware.com/cmake/cmake/issues?

In the meantime - maybe expose ```all``` for a key-binding the same as ```clean``` and ```install```?

Thanks!
