### ISSUE TITLE
API: Export the list of per-target compilation info

### ISSUE THREAD

**Issue by maddouri** [vector-of-bool/vscode-cmake-tools#164]
Currently, the codeModel property (i.e. the data structure containing the per-target compilation info... among other things...) is only generated by the "client" (i.e. CMake Server client) version of the API wrapper's `_impl` proprety.

The "legacy" (i.e. non-CMake-Server-based) version of the API wrapper's `_impl` proprety has a "compilation database" which provides a per-file compilation info.

Would it possible to provide unified, per-target, compilation info in the API?

**Comment by vector-of-bool** [comment]
The difficulty is that CMake stores compilation info in a few disparate locations: Global Flags, Directory Flags, Target Flags (which includes directory and global flags), and on source files individually.

The compilation database only provides them per-file, and it's not possible to find out what target a file belongs to without CMake Server's help.

In an ideal world, cpptools would respect that individual files may (and often do) have different compilation flags. Until then, your best bet might be to just grab all flags from all files and merge them together.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
