### ISSUE TITLE
Debug Button still invisible after Build

### ISSUE THREAD

**Issue by jessehao** [vector-of-bool/vscode-cmake-tools#166]
After Build the project. the debug buttons still invisible.
![1704151-17331ef7f920259d](https://user-images.githubusercontent.com/5467890/26864868-dc21807a-4b8c-11e7-95a6-ccca4b1a9080.png)
after restart vscode. they're appeared.
![1704151-67b3db806fd578be](https://user-images.githubusercontent.com/5467890/26864873-dfccf916-4b8c-11e7-8f93-a31ebd832b5d.png)

**Comment by vector-of-bool** [comment]
What CMake Version are you using? What configuration do you have for CMake Tools?

**Comment by jessehao** [comment]
1. CMake Version: `n 3.9.0-rc1`
2. CMake Tools Settings: 
```
"cmake.debugConfig": {
    "miDebuggerPath": "gdb.exe",
    "externalConsole": true,
    "stopAtEntry": true
}
```
3. Build Type: `Debug`
