### ISSUE TITLE
Build fails with "`.rodata' can not be used when making a shared object"

### ISSUE THREAD

**Issue by Arman92** [vector-of-bool/vscode-cmake-tools#179]
I used to build and debug my project totally fine, but after updating to newer version of vscode and cmake-tools extension, the build process will break at linking stage.

Here is the linking error:
```
***/external/freetype2/prebuilt/linux/64-bit/libfreetype.a(ftbase.linux64.o): relocation R_X86_64_32 against ".rodata" can not be used when making a shared object; recompile with -fPIC
```

No, I'm not making a shared object, so I don't need to re-compile freetype with -fPIC flag.
I tried both "make" and "Ninja" tools, both will fail.
Interesting part is, when I manually do a cmake like this:
```
mkdir build
cd build
cmake ../
make
```

It will compile and link just fine. I tried with Ninja tool, it works too. I don't know if the cmake-tools extension is adding a wrong flag to makefile that makes the linker think this is a shared-library-project...

**Comment by vector-of-bool** [comment]
What does your `add_library()` call look like?

**Comment by Arman92** [comment]
Actually my project is Cocos2d-x game, there are lots of nested CMake files. I tried to find something useful for you but that's just too complicated.
Would it help if I include the build.ninja files? (The one that I manually created and compiles, and the one created with cmake-tool which fails)

**Comment by Arman92** [comment]
Strangely, I got it working by commenting the 
```
include(CMakeToolsHelpers OPTIONAL)
```
and adding : 
```
include(CMakeToolsHelpers OPTIONAL)
```
at the top of my main CMakeLists.txt file.

**Comment by vector-of-bool** [comment]
Search your CMakeCache.txt for `BUILD_SHARED_LIBS`, both with and without using CMake Tools

**Comment by vector-of-bool** [comment]
@Arman92, I'm curious, what `cmake_minimum_required(VERSION)` do you have specified? If it's at least `2.6.0`, that policy should be set.

**Comment by ArtBlnd** [comment]
this isn't a CMake-Tools issue,
you can fix it just adding  `-fPIC` option CXXFLAGS

**Comment by vector-of-bool** [comment]
It's a CMake Tools issue in that the behavior differs from the behavior when running CMake from the command line.

**Comment by Arman92** [comment]
Sorry to vanish like this,
It's set to cmake_minimum_required(VERSION 3.4.1)
I didn't know if that policy is required, because my project was working fine before updating the CMake Tools extension

**Comment by vector-of-bool** [comment]
What about `BUILD_SHARED_LIBS`? Is that variable set in the cache? What is it set to when you run with and without CMake tools?

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
