### ISSUE TITLE
Eternal "Enabling cmake-server support requires that VSCode be restarted"

### ISSUE THREAD

**Issue by Axel-Naumann** [vector-of-bool/vscode-cmake-tools#180]
Hi,

Thank you for this fantastic extension!

After updating from VSCode 1.13 to 1.13.1 I get an info box saying "Enabling cmake-server support requires that VSCode be restarted". Restarting VSCode doesn't help - it will just show up again. Likely side-effect: I can configure my project using the "CMake: " button, but I never get a build "button" next to it.

That's on Linux with VSCode
```
Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

What can I provide to help debug this?

Axel.

**Comment by ytimenkov** [comment]
@Axel-Naumann It is likely dup of #173 if your CMake version is < 3.7.2
Either update CMake version (to have nice Server Mode support) or temporary set `cmake.useCMakeServer` to false to get rid of the message.

**Comment by Axel-Naumann** [comment]
Darn, I should have found that one (but expected an open issue)! You're right, it's 3.7.1! It would've been nice to be told differently than "pleas restart" :-) but that's still an error on my side; your doc clearly states the limitation. Thanks & apologies for the bogus ticket!
