### ISSUE TITLE
CMake & Debian Stretch not working

### ISSUE THREAD

**Issue by Moerten** [vector-of-bool/vscode-cmake-tools#184]
Hi, i have upgraded to Debian Stretch today and cmake isn't working any more as it seems.
See the log below:

/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Starting CMake Tools backend
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake output]: cmake version 3.7.2
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake output]: 
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake output]: CMake suite maintained and supported by Kitware (kitware.com/cmake).
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] cmake exited with return code 0
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Loading environments
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Loading CMake Tools from /media/user/Path/To/My/App/MyApplication/MyApplication/.vscode/.cmaketools.json
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Environments loaded
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Started new CMake Server instance with PID 2832
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake-server] CMake Error: Internal Error with /media/user/Path/To/My/App/MyApplication/MyApplication/build/.cmserver.2776: EADDRINUSE
d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake-server] 

d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] rejected promise not handled within 1 second
d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Invalid backend promise: Error: Invalid backend promise
    at new CMakeToolsWrapper (/home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.0/out/src/wrapper.js:46:40)
    at /home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.0/out/src/extension.js:17:23
    at Generator.next (<anonymous>)
    at /home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.0/out/src/extension.js:7:65
    at __awaiter (/home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.0/out/src/extension.js:3:12)
    at activate (/home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.0/out/src/extension.js:15:12)
    at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:418399)
    at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:418184)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:417959
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:39252)
e.onUnexpectedError @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
extensionHost.ts:293 [Extension Host] (node:2776) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
d.logExtensionHostMessage @ extensionHost.ts:293
(anonymous) @ extensionHost.ts:147
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

**Comment by Moerten** [comment]
Are there any plans to fix these issues? This addon doesn't work any more. Otherwise i would change back to an other IDE. I also tried to install the older Version 0.9.7 manually but this doesn't work too. I lost more than 2 weeks of development already.

**Comment by ytimenkov** [comment]
@Moerten This sounds serious!
EADDRINUSE may be caused by stale cmake instance. Need to take a look if I get to my Linux box.

As a temporary workaround I recommend set `cmake.useCMakeServer` to `false`. At least you will be able to load extension and build your project. Although target debugging requires some [tricks.](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md#enabling-target-debugging-for-cmake-versions--372)

**Comment by ytimenkov** [comment]
@Moerten Unfortunately I couldn't reproduce this on my OpenSUSE box (I don't have Debian if it matters).
Please find out who uses this socket by running `lsof -U | grep cmserver`.

**Comment by vector-of-bool** [comment]
@Moerten, sorry to take so long on responding here!

After upgrading to Stretch, did the CMake version change as well? I'm wondering if a CMake update may be related to this breaking.

As @ytimenkov said, this is probably a stale cmake-server instance running in the background. I can't readily identify in the code any potential issues with improper shutdowns.

**Comment by Moerten** [comment]
@ytimenkov
I read about this setting on the main page before. But there is no additional info beside that it has to be placed in the "settings.json". Nothing was said about the section. I have only a "files.associations" section there. So where should it be placed to? Not everyone knows the interals like you guys :).

The command

> lsof -U | grep cmserver

showed no output on the terminal.

@vector-of-bool
Yes stretch changed cmake version to 3.7.2 as could be seen at the log above.

Thanks for your support.

**Comment by vector-of-bool** [comment]
`3.7.2` is the first version of CMake with a good `cmake-server` backend, which means that CMake Tools automatically switched to using it.

Did you run the `lsof` command immediately after trying to run VSCode with the CMake Tools extension?

The `cmake.useCMakeServer` option goes into `settings.json`. It will force the extension to use the old backend, which should work around your problem until it can be better fixed. It's undocumented ATM because I'm wanting to see if I can remove the option without completely breaking the extension for some people (apparently not).

**Comment by Moerten** [comment]
I called the command about a dozen times after vscode startup. Can you provide an example settings.json file. I still do not know where to place the "cmake.useCMakeServer" entry.
Thats what my "settings.json" is looking like:

> 
> {
>     "files.associations": {
>         "array": "cpp",
>         "functional": "cpp",
>         "tuple": "cpp",
>         "type_traits": "cpp",
>         "utility": "cpp",
>         "iosfwd": "cpp",
>         "initializer_list": "cpp",
>         "cctype": "cpp",
>         "clocale": "cpp",
>         "cstdint": "cpp",
>         "cstdio": "cpp",
>         "cwchar": "cpp",
>         "cwctype": "cpp",
>         "exception": "cpp",
>         "new": "cpp",
>         "typeinfo": "cpp",
>         "list": "cpp",
>         "istream": "cpp",
>         "string": "cpp",
>         "unordered_map": "cpp",
>         "system_error": "cpp"
>     }
> }

**Comment by s-martin** [comment]
Just start typing in the settings.json, it supports auto-complete. The setting should have the prefix "cmake."

**Comment by vector-of-bool** [comment]
@Moerten, I just had this happen to me on my Ubuntu 16.04 box. It looks like two instances of CMake Server tried to start at the same moment, but I can't be sure why... I'll play around to see if I can reliably recreate the problem.

**Comment by vector-of-bool** [comment]
Found probably cause:
Certain things can trigger a restart of CMake-Server, but there is no guard to make sure that we don't restart _while already restarting_.
