### ISSUE TITLE
Feature: Use Visual Studio generator Windows if available

### ISSUE THREAD

**Issue by ytimenkov** [vector-of-bool/vscode-cmake-tools#186]
Current implementation of CMake Tools suggest using either Ninja or NMake Makefiles generators on Windows. Unfortunately if only Visual Studio is installed none of them available by default: Ninja requires manual installation, NMake is usually not in the default PATH.

This especially hurts when CMake runs in Server mode because in Legacy mode CMake may run without generator at all and pick first available on the system (usually falling back to VS family which it detects via registry), however Server Mode requires generator to be specified.

## Proposal ##
 1. Add ability to EnvironmentManager to provide extra generators suitable for particular environment. This includes Visual Studio family and MinGW Makefiles.
 1. When detecting the availability of MAKE_PROGRAM, tests should be performed in modified environment (i.e. merged with Active Environment).

This should reduce cases when extension fails to initialize.

**Comment by vector-of-bool** [comment]
Did this issues get finished with your PR?

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
