### ISSUE TITLE
Run without building

### ISSUE THREAD

**Issue by NathanW2** [vector-of-bool/vscode-cmake-tools#188]
I suspect this might be an option I overlooked but is it possible to run a target without doing a build first?

**Comment by ytimenkov** [comment]
Yes, https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md#running-program-from-launchjson
However it will run in the debugger (see note at the end of the section).

If you need to run without build and without debugger then you have to create a task, and for this you need to specify path to the built executable. VS Code doesn't allow `${command:}` substitutions in tasks.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
