### ISSUE TITLE
Add support for build type variable substitution in settings

### ISSUE THREAD

**Issue by rtbo** [vector-of-bool/vscode-cmake-tools#19]
Not relevant for every setting entry, but would allow to write
```json
"cmake.buildDirectory": "${workspaceRoot}/build/${buildType}"
```
which would substitute `${buildType}` to either `Debug` or `Release` and allow to use different build trees.

**Comment by rtbo** [comment]
this is relevant only for generators that do not support multiple configurations. (visual studio)
For such, a warning should come to the user saying `${buildType}` makes no sense in `buildDirectory`.

**Comment by vector-of-bool** [comment]
Done!
