### ISSUE TITLE
Still linux problems

### ISSUE THREAD

**Issue by Moerten** [vector-of-bool/vscode-cmake-tools#197]
#184 Hi, sorry for this issue again. But I am still experiencing errors on linux with cmake-tools 0.10.1. Two days ago I installed fedora for testing and had the same issues as with debian.
Maybe someone else having linux running can check wether he has the same problems. At the end its only my machine? Do I need internet for the new cmake-server functionality? Or could it be a problem having a firewall activated?

/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Starting CMake Tools backend
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake output]: cmake version 3.7.2
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake output]: 
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake output]: CMake suite maintained and supported by Kitware (kitware.com/cmake).
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] cmake exited with return code 0
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Loading environments
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Loading CMake Tools from /Path/To/My/App//MyApplication/MyApplication/.vscode/.cmaketools.json
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Environments loaded
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Started new CMake Server instance with PID 14868
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake-server] CMake Error: Internal Error with /Path/To/My/App//MyApplication/MyApplication/build/.cmserver.14819: EADDRINUSE
d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [cmake-server] 

d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] rejected promise not handled within 1 second
d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Invalid backend promise: Error: Invalid backend promise
    at new CMakeToolsWrapper (/home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/wrapper.js:46:40)
    at /home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:17:23
    at Generator.next (<anonymous>)
    at /home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:7:65
    at __awaiter (/home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:3:12)
    at activate (/home/user/.vscode/extensions/vector-of-bool.cmake-tools-0.10.1/out/src/extension.js:15:12)
    at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:418399)
    at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:418184)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:417959
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:39252)
e.onUnexpectedError @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] (node:14819) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
d.logExtensionHostMessage @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 launch: program '/Path/To/My/App//MyApplication/MyApplication/build/MyApplication' does not exist
e.doShow @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28

**Comment by vector-of-bool** [comment]
CMake Server only communicates over a named pipe, the filename of which is deterministic. Internet access should have no effect on the behavior here. There's a way that I can work around this issue in the code, but I'd rather "get it right" and find out _why_ it does this.

Does this issue _always_ occur when using CMake Tools? Or is it intermittent?

**Comment by Moerten** [comment]
Without having cmake-tools installed the dev console is empty.

**Comment by dcourtois** [comment]
Does this path exist `/Path/To/My/App//MyApplication/MyApplication/build/` on your hardrive, and do you have privileges to write to it ? It looks like a dummy test path, but CMake seems to be configured to try to use it. It's trying to create files there (see this error in the logs: `CMake Error: Internal Error with /Path/To/My/App//MyApplication/MyApplication/build/.cmserver.14819: EADDRINUSE`)

It looks like you forgot to configure some stuff.

**Comment by ytimenkov** [comment]
That I was also thinking about: what else may cause EADDRINUSE in Linux?
 1. Is it possible that the filesystem (where /home is mounted) doesn't support Unix Sockets? E.g. Network or mounted with some flags, like nodev?
 1. Internal issues with fork()'ing process? E.g. if socket was open before fork/exec?

**Comment by Moerten** [comment]
Yes, thats the path to my application (ok there was an "/" to much from copy & paste):

/Path/To/My/App/MyApplication/MyApplication/build/

The build folder gets created from cmake-(tools) automatically.
One other thing I have noticed. As soon as I install the camke-tools addon there gets an mystical "b" file created without extension. When I open it a message "For the file type 'Socket' no application was installed". If i try to open it as root with an editor it can not be opened. It seems that's a hell of a bug :D.

**Comment by vector-of-bool** [comment]
Sorry to disappear. Any discoveries on this bug?

Regarding a strange `b` file: Where is it created? Does it appear at a certain phase in the configuration process?

Being a socket file (A named pipe), it's possibly related to the `EADDRINUSE` error. If more that one program tries to create a named pipe with the same name, you see `EADDRINUSE`.

**Comment by ytimenkov** [comment]
@Moerten I suspect that you hit some kind of length limit. What is the length of your build directory?
(e.g. cd there and run `pwd | wc -m`).

If you can make symlink to some shorter path and run from there, do you still experience such issues?

**Comment by Moerten** [comment]
@ytimenkov 
That's it. My path is 106 Chracters long. When i copy the project directly to the root folder of my hdd it works again.

@vector-of-bool 
The "b" file is created in the project folder.

**Comment by ytimenkov** [comment]
Sounds like 100-char limit somewhere in CMake (arg parsing, path limit in the lib they use, e.g. some static buffer...)
then `b` could be leftover from **long_path/b** *uild/.cmserver.1234*

**Comment by ItachiSan** [comment]
I also have the same *b* problem.
Should I open a separate issue? @ytimenkov @vector-of-bool

**Comment by vector-of-bool** [comment]
I'd open a new issue since it seems to be something different.

**Comment by Moerten** [comment]
For me it looks like the same problem. Before the cmake server changes every thing worked fine. So I assume it's a problem with this plugin.
My solution so far:
Install Atom Editor and plugins like build, build-cmake...

**Comment by vector-of-bool** [comment]
@Moerten, have you tried disabling cmake-server functionality in the ext? I forgot to ask, but that usually is a good enough workaround for most cases.

**Comment by Moerten** [comment]
No, that doesn't help.

**Comment by ANaumann85** [comment]
Is there a way to spawn the cmake server process with another working directory? This way, you could shorten the pipe argument

**Comment by vector-of-bool** [comment]
It's been a while, but I've changed the way I open the cmake-server pipe. Can anyone reproduce this issue in a new version

**Comment by ANaumann85** [comment]
On my system, the problem is went away after updating today.


Am 27.06.2018 um 05:20 schrieb vector-of-bool:

**Comment by ItachiSan** [comment]
Seems that I don't have the problem anymore too.
