### ISSUE TITLE
Compilation fails on Linux when using a custom buildDirectory

### ISSUE THREAD

**Issue by jdumas** [vector-of-bool/vscode-cmake-tools#199]
I'm trying to use CMake Tools with the following setting:

```json
    "cmake.buildDirectory": "${workspaceRoot}/build/${buildType}",
```

However, it fails with the following message:
```
Execute cmake with arguments: --build,/home/jdumas/downloads/cmake_test/build/Debug,--target,all,--config,Debug,--,-j,14
[vscode] Executing command: cmake --build /home/jdumas/downloads/cmake_test/build/Debug --target all --config Debug -- -j 14
Error: could not load cache
[vscode] cmake exited with return code 1
```

I'm not sure exactly what's happening here, but I remember it was working fine before you switched to `cmake-server`. I'm running an up-to-date version of archlinux (cmake 3.8.2, clang 4.0.1 and gcc 7.1.1). It fails even on a simple hello world on my computer:

```cmake
cmake_minimum_required(VERSION 3.3)
project(hello)
add_executable(${PROJECT_NAME} main.cpp)
```

**Comment by vector-of-bool** [comment]
So sorry for the delay. Got caught up in life.

I'll take a look at this.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
