### ISSUE TITLE
Add support for install

### ISSUE THREAD

**Issue by rtbo** [vector-of-bool/vscode-cmake-tools#20]
My `CMakeLists` scripts use the install directive to group all necessary DLLs and executables in the same folder, ready for deployment.
I also need this to run my product (project with exe and multiple dlls) as windows won't find the dlls in the build tree.
Install command in vscode along with `${cmake.installPrefix}` setting would be very handy.

**Comment by vector-of-bool** [comment]
Sorry to be slow to respond. Would invoking the ``install`` target be insufficient?

**Comment by MinnieTheMoocher** [comment]
nearly.
what is needed is also a configuration setting
`"cmake.buildDirectory": "${workspaceRoot}/install",`
analogously to
"cmake.buildDirectory": "${workspaceRoot}/build",

That setting should have the effect of adding the cmake command line option
-DCMAKE_INSTALL_PREFIX=...
with the "..."'s replaced by the contents of that configuration variable

**Comment by rtbo** [comment]
This is exactly what I did in the pull-request #21 (see last commit 2bbbc27d03cee340b1a2030f16fabbd6f62a399e)

**Comment by rtbo** [comment]
in fact I used `cmake.installPrefix` for consistency with `-DCMAKE_INSTALL_PREFIX`. I can replace by `cmake.installDirectory` for consistency with `cmake.buildDirectory`. I have no preference for this concern.

**Comment by vector-of-bool** [comment]
Finished!

**Comment by MinnieTheMoocher** [comment]
`cmake.installPrefix` is fine. the analogy to the cmake command line is good this way.
