### ISSUE TITLE
per-environment build dirs

### ISSUE THREAD

**Issue by vvuk** [vector-of-bool/vscode-cmake-tools#206]
It would be nice if you could specify a different build directory name per environment, to make it possible to quickly switch between them for testing different build scenarios.  For example, on Windows I have a project that I want to build in four different environments:

- VS2017 x64
- VS2017 x86
- Emscripten
- mingw gcc

Each has slightly different issues so I need to frequently run builds in all 4 to make sure changes work.  Right now this is a pretty manual process, usually leaving vscode configured for one of them and running the others from the command line.  One option would be to expose something like "${buildEnvSuffix}" and allow each environment to define it (e.g. "-vs2017-x64", "-mingw-gcc"), so that it can be used in $cmake.buildDir.

This is sort of related to #195, but in this case I'd like entirely separate build environments, not just the configuration.

**Comment by vector-of-bool** [comment]
I'll look into this. Might be easy -- hard to say.

**Comment by Randshot** [comment]
@vvuk In the latest 0.11.0-beta4, you can use the `cmake-kits.json` file to define your kits. You can alter the `cmakeSettings` field for every kit separately and then use variable substitution when defining the build directory. I will close this for now.

**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
