### ISSUE TITLE
Visual 14.0 generator : missing INSTALL and other META targets

### ISSUE THREAD

**Issue by gagbo** [vector-of-bool/vscode-cmake-tools#207]
It's possibly related to #162, but I'm not sure I understood what the issue was.

I have a project in which I want to access an install target (the install target works just fine when I compile running Linux). Therefore : 
- I change the settings.json of my project to add `"BUILD_INSTALL": true` in the `cmake.configureSettings` object. (Note : I also added manually the VS generator to the generator list)
- I save the settings.json, triggering a restart of the CMake server (by the way, there's a missing closing double quote at the end of environment) : 
    ```
    Loading CMake Tools from ${edited workspace Root}\.vscode\.cmaketools.json`
    Detected available environment "Visual C++ 14.0 - x86
    Detected available environment "Visual C++ 14.0 - amd64
    Detected available environment "Visual C++ 14.0 - amd64_arm
    Started new CMake Server Instace with PID xxx
   ```
- I click the build configuration selector, and then choose `Release`, triggering the configuration (all works)
- And finally, I click the target selector button to (hopefully) choose install.
    - Expected behaviour : 
        - Since the CMakeCache is correctly configured, VS generator creates in the build subdirectory 3 sets of vcxproj files (corresponding to `META` targets if I understand correctly)
        - All defined META targets are picked up and proposed (e.g. `ALL_BUILD`, `INSTALL`, `RUN_TESTS`)
    - Actual behaviour : 
        - VS generator did create all the corresponding vcxproj files corresponding to the `META` targets (responding to `BUILD_TESTS` and `BUILD_INSTALL` CMake variables in CMakeLists)
        - Clicking on target selector only proposes `ALL_BUILD` as a `META` target. Completion doesn't work either (trying to type `INSTALL` in the text field)

I hope this was clear enough, and if it is actually the same problem as #162, I'll gladly get the issue number on their tracker to see how it goes.

**Comment by vector-of-bool** [comment]
Looks like it's the same issue as #162. Bleh. Will have to workaround it. Not sure if CMake Server is supposed to expose those META targets or not.

**Comment by MathiasMagnus** [comment]
I had a question about this on the CMake users mailing list, but nobody answered. I wanted to build the target `doc` (a custom_target of mine) to build LaTeX docs using kmorels useLATEX.cmake scripts. Apparently CMake does not expose custom_commands in the compile_commands.json file, and it seems neither does it expose the custom targets.

**Comment by gagbo** [comment]
I won't be able to test this any time soon (moved to Visual 15 generator, and also full blown Visual Studio instead of only VSCode at work, and also very little time these weeks), sorry :(

As far as I'm concerned, if you think it's fixed you should close it, and there's this reference if someone else is able to reproduce.
