### ISSUE TITLE
Non-default CMake version throws

### ISSUE THREAD

**Issue by invexed** [vector-of-bool/vscode-cmake-tools#210]
I'm trying to get CMake 3.8.2 to work with VS Code in CentOS 7.3. I have set `cmake.cmakePath` to `"/opt/cmake_3_8_2/bin/cmake"` but I get the following error in the output window:

```
Started new CMake Server instance with PID 5947
[cmake-server] terminate called after throwing an instance of 'std::logic_error'

[cmake-server]   what():  basic_string::_M_construct null not valid

The connection to cmake-server was terminated unexpectedly
cmake-server exited with status null (SIGABRT)
```

**Comment by vector-of-bool** [comment]
This would be an error in CMake itself. I can't be certain what's going on here. Any chance you could get a debug build of CMake and a relevant core dump?

**Comment by yamcenutzer** [comment]
doesn't work with a new cmake 3.9 (on fedora).
I don't get any output at all. 
It simply does nothing.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by lrineau** [comment]
The bug was in CMake itself. See https://github.com/Kitware/CMake/pull/311.

**Comment by Randshot** [comment]
@lrineau Thank you for the notice, I closed this one because it was stale and, like you already said, not related to this extension.
