### ISSUE TITLE
Unable to step out. Operation failed with error code 0x80004004.

### ISSUE THREAD

**Issue by donproc** [vector-of-bool/vscode-cmake-tools#215]
I can debug with 'Step Over', But can not 'Step Out'. And it tell Error 'Unable to step out. Operation failed with error code 0x80004004.' if 'Step Out' Any one can help? I didn't find similar issues.

And when debug is over, will meet error:
Unable to open 'libc-start.c': File not found (/build/glibc-t3gR2i/glibc-2.23/csu/libc-start.c).

**Comment by dcourtois** [comment]
Sorry for not being of much help, but this is an issue with cpptools extension, not CMake Tools.
You might want to take this issue to https://github.com/Microsoft/vscode-cpptools/issues and close this one here as CMake Tools extension has nothing to do with debugging.

**Comment by vector-of-bool** [comment]
Sorry @donproc, he's right. On the bright side, they're fairly responsive over there. You'll probably get help with your issue on the cpptools issue tracker.
