### ISSUE TITLE
Compiling a selected cpp-file

### ISSUE THREAD

**Issue by mkotlyar** [vector-of-bool/vscode-cmake-tools#217]
It would be nice to have an option to compile and individual file from a project:
 - The .cpp-file currently open in the editor
 - A selected .cpp-file from the file explorer

**Comment by dcourtois** [comment]
That would indeed be very nice, but unfortunately, I don't any way this is going to be feasible. CMake only support building targets (see https://cmake.org/cmake/help/v3.9/manual/cmake.1.html#build-tool-mode)

To build a single file, that would require at least these steps

1. Scan the CMake cache to extract the compiler path and general compiler options
2. Try to locate the target the file is used in
3. Extract all defines / compiler flags / whatever from that target
4. Manually invoke the compile command

Problem being: none of those steps are reliable. CMake server makes step 3 somewhat reliable (depends on the CMakeLists.txt to be fair) but step 2 is definitely not: if your file is used in multiple targets, each using different set of defines / options, you don't have any way of knowing which to use.

Finally, even if we take the "make it work for simple use cases" approach, it's still an awfull lot of dirty hacky code to write (and later maintain, which is the worst in those kind of things), unfortunately :/

**Comment by mkotlyar** [comment]
@dcourtois good points. Regarding the (2): `cmake-tools` has an active build target, I think it is natural to use this one.

**Comment by vector-of-bool** [comment]
Actually, this may be close to trivial using the compilation database. This is a feature I've wanted to add, but never gotten around to it.

**Comment by vector-of-bool** [comment]
It's been quite a while, but this feature is now available in 1.1.0!
