### ISSUE TITLE
Reset to "All" target

### ISSUE THREAD

**Issue by decimad** [vector-of-bool/vscode-cmake-tools#219]
Hello, I'm witnessing that the CMake-Tools will sometimes fall back to the "All" target. Is there somewhere a list of the circumstances leading to this fallback?

**Comment by vector-of-bool** [comment]
Sorry for the delay.

This happens when CMake Server needs to be restarted. I don't maintain the active target between restarts. This can be fixed if the target is stored in the filesystem. That would also help preserve between VSCode runs.

**Comment by britalmeida** [comment]
+1 to persist both the active build target and the target for debugging ^^

**Comment by vector-of-bool** [comment]
This issue should be fixed in the 0.11.0 beta release. Have you given that a try? It also includes a lot of other enhancements and fixes, including persisting the debug target.

**Comment by britalmeida** [comment]
I will give it a try on my next free weekend! Thank you for the fast reply :)

**Comment by vector-of-bool** [comment]
I'm closing this, but feel free to re-open if you feel it is not solved to your satisfaction with the 0.11.0 [beta] release.

**Comment by britalmeida** [comment]
I have switched to the 0.11.0 version and it now remembers the targets without problem. Thank you!
