### ISSUE TITLE
"undefined - x86" environment, bad vswhere/vcenv parsing

### ISSUE THREAD

**Issue by vvuk** [vector-of-bool/vscode-cmake-tools#221]
The tools run `vswhere` like this: `"c:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -products * -format json -legacy`.  But the `-legacy` param causes it to list older versions of VS that don't follow the new layout/installer/etc. conventions.  In my output, I have:
```
  {
    "instanceId": "VisualStudio.14.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\",
    "installationVersion": "14.0"
  },
```
(and similar for 12.0 and 10.0, along with the full block for 2017)

This causes a bunch of `undefined - x86` and similar environments to show up, because  `tryCreateNewVCEnvironment` returns a largely empty env block.  `where.displayName` doesn't exist, but `collectDevBatVars` succeeds.

I'd suggest just bailing if `where.displayName` isn't defined, but I suspect these environments might actually work... in which case, name could just be `"Visual Studio " + where.installationVersion` or similar.  Or, just skip passing `-legacy` to `vswhere` -- I'm not sure if the intent is to try to make these work or not.

**Comment by vector-of-bool** [comment]
Sorry for the delay. I'll take a look at how to fix this.

**Comment by Randshot** [comment]
This is fixed in beta4.
