### ISSUE TITLE
Configuring CMake Project freezes on Ubuntu

### ISSUE THREAD

**Issue by HerrVey** [vector-of-bool/vscode-cmake-tools#225]
When I configure a CMake project(Ctrl+Shift+P -> Cmake Configure) , I have the following output in VSCode 
`Loading CMake Tools from /home/herve/Documents/C++/.vscode/.cmaketools.json `
`Started new CMake Server instance with PID 3947 `
`[vscode] Configuring using the "Ninja" CMake generator`
but nothing else happens. At the top of the screen, VSCode displays `Error: You do not have a CMakeLists.txt` which is weird because I actually have one in my project. Besides, I can build it using `cmake -G Ninja` in Linux console. Any idea why I'm getting this error ? Any help would be appreciated, thanks!

I'm working with:
- Ubuntu 16.04.3
- Visual Studio Code 1.15.1 with extensions : cpptools 0.12.3, cmake 0.0.17, cmaketools 0.10.12
- CMake 3.9.1

N.B. : I followed this [tutorial ](https://www.codeproject.com/Articles/1184735/Quick-Start-to-Use-Visual-Studio-Code-for-Cplusplu):

**Comment by vector-of-bool** [comment]
Almost one month later...

Sorry that this has sat for so long. I've been busy IRL, but I want to do some serious refactors and feature improvements based on some feedback I've been getting for a few months.

Are you still experiencing this issue?

I'm curious about the layout of your project that would cause it to fail to find your `CMakeLists.txt`.

**Comment by HerrVey** [comment]
I tried again to configure my CMake project two weeks after I posted this issue and it worked very well but I don't know why. Maybe I did something differently but I can't say what.
