### ISSUE TITLE
Add support to define parallelJobs for CTest only

### ISSUE THREAD

**Issue by s-martin** [vector-of-bool/vscode-cmake-tools#23]
I would like to be able to define the no. of parallel jobs (i.e. -j) for CTest only.

My unit tests don't finish, if I run them in parallel, nevertheless for building I would like to have parallel jobs.

So "cmake.parallelJobs" doens't offer the required granularity for me.

**Comment by vector-of-bool** [comment]
Should be in the nest release as ``cmake.test.parallelJobs``. As a side note, have you seen [this CMake property?](https://cmake.org/cmake/help/latest/prop_test/RESOURCE_LOCK.html) It might be useful to you.
