### ISSUE TITLE
Keep the output console once a target has stopped

### ISSUE THREAD

**Issue by meuter** [vector-of-bool/vscode-cmake-tools#230]
Hi, 

This is a small thing, but for usability it's rather annoying. When you press F5 to run the current target, the stdout and stderr are displayed in new debug console. But once the program stops, the console disappears. I would suggest to keep this debug console open once the program is finished, maybe with the exit status of the program, just like the output of the compiler when you build.

Thanks for a great plugin btw!

-Cédric

EDIT: I just realised that this has already been submitted => [here](https://github.com/vector-of-bool/vscode-cmake-tools/issues/223)

**Comment by vector-of-bool** [comment]
Moving to #223.
