### ISSUE TITLE
cmake.buildToolArgs doesn't support replacing of VS Code vars (eg ${workspaceRoot})

### ISSUE THREAD

**Issue by jmorrill** [vector-of-bool/vscode-cmake-tools#232]
This may be an oversight or by design, but the cmake.buildToolArgs doesn't support using vars like ${workspaceRoot}.

My CMake project has some .NET projects in it, so I need to pass additional arguments and it would be nice to do something like this:

"cmake.buildToolArgs": [
        "-p:Platform=x86",
        "-p:Configuration=Release",
        "-p:SolutionDir=${workspaceRoot}"
    ]

Right now I must hard code the "p:SolutionDir" value.

**Comment by vector-of-bool** [comment]
Good call

**Comment by Randshot** [comment]
PR #317 merged.
