### ISSUE TITLE
cmake-tool can not init

### ISSUE THREAD

**Issue by jinzt** [vector-of-bool/vscode-cmake-tools#234]
after upgrade c/c++ 0.13.0 extension ,cmake-tool extesion get a error   "CMakeTools extension was unable to initialize: Error: Unable to determine CMake Generator to use [See output window for more details]"

**Comment by vector-of-bool** [comment]
Do you see anything in the output window of interest?

Upgrading the c/c++ ext should have no effect, but I'd be interested to see what's going on here.

**Comment by drinkmystery** [comment]
My cmake-tool also can not init.
I do not know if it is the same bug. So i did not create a new issue.

Vscode version 1.17.0-insider
extension verison
1. ms-vscode.cpptools 0.13.0
2. vector-of-bool.cmake-tools 0.10.2
3. maddouri.cmake-tools-helper 0.1.1

When I open a folder which contains CMakeLists.txt,  
the status bar is "CMake:Unconfigured Project: Unconfigured: Ready".
I click it, then get a error "CMakeTools extension was unable to initialize: TypeError: Reduce of empty array with no initial value".  
The output window's message is "Loading CMake Tools from c:\Users\drink\Documents\project\fmt\.vscode\.cmaketools.json".

Not such file in the .vscode folder.

**Comment by vector-of-bool** [comment]
@drinkmystery, what compilers etc. do you have installed? The same error message occurs [here](https://github.com/vector-of-bool/vscode-cmake-tools/issues/235).

**Comment by drinkmystery** [comment]
@vector-of-bool, i am using a preview version of Visual Studio 2017. Yes, I think it is the same error. THX.

**Comment by promethe42** [comment]
I have the exact same issue.
I don't see anything in the output window.

Yet if I open `cmd.exe` in my project's `build` folder and simply run `cmake ..` I get:

```
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.15063.0 to target Windows 10.0.16299.
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/jeanm/Projects/embedb/build
```

I have both VS2017 and VS2015 installed.

**Comment by yeyingsitan** [comment]
I have the same problem.

the status bar is "CMake:Unconfigured Project: UnitTest: Ready".
I click it, then get a error "CMakeTools extension was unable to initialize: TypeError: Reduce of empty array with no initial value".
The output window's message is "Loading CMake Tools from c:\swept\msys64\home\YEY2HZ\Panda1221\.vscode\.cmaketools.json

In my system, I only have VSCODE 1.18.1

**Comment by vector-of-bool** [comment]
@yeyingsitan, sorry for the delay. I'm still perplexed by this one and haven't an idea of what might be going wrong. Could you give the beta release a try and tell me if you have better results?

**Comment by decimad** [comment]
Hey, upgrading to 0.11.0 beta 4 helped with this issue. However we work on a Project that uses cmake toolchain files to set up a cross Compiler toolchain and now I'm left without a so-called "kit" and can't configure the CMake Projects anymore.

**Comment by yeyingsitan** [comment]
I have installed the 0.11.0-beta4. The extension bar shows reload, but after I reloaded several times (both click reload and restart ),the mark is still there.  :-(

发自我的 iPhone

**Comment by yeyingsitan** [comment]
I have made a mistake before. It’s no longer an issue! THX!

发自我的 iPhone

**Comment by bbosnjak** [comment]
I had problem with free space on my computer and decided to uninstall VisualStudio! After this action I get error (CMake Tools 0,10,4):
"CMakeTools extension was unable to initialize: TypeError: Reduce of empty array with no initial value [See output window for more details]"

There is reduce on empty array in one of getEnvironments() in environment.ts. Following fix is working for me (empty array as InitalValue for reduce):
      const all_promices = installs
        .map((where) => archs.map((arch) => tryCreateNewVCEnvironment(where, arch)))
        .reduce((acc, proms) => acc.concat(proms), []);

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
