### ISSUE TITLE
Can you expose a setting to enable configuring CMake with a preview version of Visual Studio 2017?

### ISSUE THREAD

**Issue by bobbrow** [vector-of-bool/vscode-cmake-tools#235]
I just spent a few hours scratching my head as to why the CMake extension didn't work on a new Windows machine I set up.  I finally cloned the source and debugged the extension and it landed me here:

**environment.ts:**
```
      const vswhere_res = await async.execute(vswhere, ['-all', '-format', 'json', '-products', '*', '-legacy']);
```

It would be nice if you could expose a setting that lets the extension select a preview installation of Visual Studio since that's all I have on some of my PCs - though I can understand why you might not want to enable this by default.  The flag you need to pass in to `vswhere` is `-prerelease`.

Otherwise, there an obscure error pops up in VS Code when a version of Visual Studio can't be found.

![image](https://user-images.githubusercontent.com/12818240/30991801-7e984eb6-a45b-11e7-8766-e511cbb90366.png)

And there is no information in the Output window.

**Comment by vector-of-bool** [comment]
I'll look into this.

**Comment by bobbrow** [comment]
no rush, I can edit the .js directly to force this in the meantime.

**Comment by MathiasMagnus** [comment]
I added PR #238 to address this. It does look grim though that there are PRs more than 7 months old. @vector-of-book does an awesome job, but he's but one man. I suggest he looks into giving a few more interested people write permissions to the repo.

**Comment by vector-of-bool** [comment]
Sorry about the slow responses. I'm in the middle of a big refactor and hope to address a lot of long-waiting issues once I'm done and have a cleaner codebase.

**Comment by vector-of-bool** [comment]
Sorry for the slow. Is this still an issue?

**Comment by MathiasMagnus** [comment]
I believe not. #238 solved it.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
