### ISSUE TITLE
Show result

### ISSUE THREAD

**Issue by kangliangc** [vector-of-bool/vscode-cmake-tools#236]
Hi,

I am a beginner currently learning C++ on VS code and it might be a stupid and simple question, but I wonder it is possible to output the result of the program rather than running the program separately. 

e.g. 
cout << something << endl;
I want to see the output of something rather than calling the program. 

Many thanks in advance. 

Best regards

**Comment by vector-of-bool** [comment]
This seems somewhat outside the scope of the extension, but I might be able to help.

How are you executing the program where you cannot see the output?

**Comment by kangliangc** [comment]
I press F7 for building CMAKE project first, then press F5 to debug it. I think relevant extensions are C/C++ by MS and yours.  Thans a lot.

**Comment by vector-of-bool** [comment]
The debug window only opens temporarily. The easiest way is to set a breakpoint right after the print statement. You can do that by clicking in the left gutter of the editor on the line you want to set a breakpoint. It should appear as a red dot in the gutter. The debugger will pause on that line when you run it.

**Comment by kangliangc** [comment]
Thank you for the reply. But is there a way to run the program automatically after MAKE? In many IDE I could directly see the output rather than run the program separately.

**Comment by vector-of-bool** [comment]
Somewhat... You can use `add_custom_command` to run the execute after building it. You'd add something like this to you `CMakeLists.txt`:

```cmake 

add_custom_target(
    TARGET my-executable
    POST_BUILD
    COMMAND $<TARGET_FILE:my-executable>
)
```

**Comment by kangliangc** [comment]
THANK YOU!!!! It is exactly what I am looking for. YOU ARE A LEGEND!
