### ISSUE TITLE
configuration variable cmake.initialBuildType is without effect

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#24]
I currently tried to change the configuration variable
`"cmake.initialBuildType": "Debug"`
to
`"cmake.initialBuildType": "Release"`
in my VSCode user settings.

However, doing that had no effect. Still "Debug" was built when doing a clean build,
i.e., first deleting the build results folder, then running CMake: configure

Expected:
The commandline supplied to cmake should have contained the option
`-DCMAKE_BUILD_TYPE=Release`

**Comment by vector-of-bool** [comment]
What CMake generator were you using?

**Comment by vector-of-bool** [comment]
This should be fixed in the 0.4.0 release. Could you check?

**Comment by MinnieTheMoocher** [comment]
confirmed. bug is gone with 0.4.0
