### ISSUE TITLE
Don't create .bat files on startup in .vscode

### ISSUE THREAD

**Issue by letmaik** [vector-of-bool/vscode-cmake-tools#240]
When I open a CMake project then I can see a lot of .bat files appearing and disappearing in the .vscode folder which not only makes VS Code's git extension react on that but other extensions as well which had registered a workspace file change listener.
The screenshot below is the result of this extension sometimes not even cleaning up the generated .bat files.
Is it really necessary to persist those .bat files to disk to fetch the relevant values? If yes, it would be better to store them in the system temp folder instead of .vscode to prevent any mess.

![image](https://user-images.githubusercontent.com/530988/31401472-dad9e25a-adea-11e7-9733-89b2a895b63c.png)
The file content is something like:
```bat
@echo off
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat" -no_logo -arch=arm || exit
echo CL := %CL%
echo _CL_ := %_CL_%
echo INCLUDE := %INCLUDE%
echo LIBPATH := %LIBPATH%
echo LINK := %LINK%
echo _LINK_ := %_LINK_%
echo LIB := %LIB%
echo PATH := %PATH%
echo TMP := %TMP%
echo FRAMEWORKDIR := %FRAMEWORKDIR%
echo FRAMEWORKDIR64 := %FRAMEWORKDIR64%
echo FRAMEWORKVERSION := %FRAMEWORKVERSION%
echo FRAMEWORKVERSION64 := %FRAMEWORKVERSION64%
echo UCRTCONTEXTROOT := %UCRTCONTEXTROOT%
...
```

**Comment by vector-of-bool** [comment]
That's for environment detection. I can move those to a different directory.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
