### ISSUE TITLE
change directory

### ISSUE THREAD

**Issue by huoyushi** [vector-of-bool/vscode-cmake-tools#241]
Sorry for my pool English. I will try my best to describe my question.  I have quick started a project in a directory just such as /User/huoyushi/GUGAODAQ. but when I move the direcory GUGAODAQ to /User/huoyushi/Documents/ ,then the project directory becomes /User/huoyushi/Documents/GUGAODAQ,and then  i build the project ，but get the error "The current CMakeCache.txt directory /home/huoyushi/Documents/GUGAODAQ/build/CMakeCache.txt is different than the directory /Users/huoyushi/GUGAODAQ/build where CMakeCache.txt was created". so I think that when someone start or init a project the directory that should be relative and once the project direcory move to another it should build correctly just like vs solutions and projects

**Comment by vector-of-bool** [comment]
This is a limitation of CMake itself. You can get it working using "Clean configure"

**Comment by huoyushi** [comment]
Thanks ,I try to delete .cmaketoos.json and then use cmake tools to rebuild ,it works.
