### ISSUE TITLE
Support multiple CMake configurations

### ISSUE THREAD

**Issue by zjturner** [vector-of-bool/vscode-cmake-tools#246]
For my project, I have several different CMake build directories, each of which have their own configuration.  Some might use a different generator, one might be debug while another is release, some might have different CMake command line options.

Does this extension support this use case at all?  After an install and a little searching, it seems like it assumes there can only be one CMake output directory.  This is because everything is stored as a global setting in `settings.json`.  For example, there is a `cmake.buildDirectory` where the output files will go to, and a generator, etc.  

I feel like this this needs a `tasks.json` style configuration, where you can define separate configurations, one can be set as the default, and each have entirely different sets of variables.

Has anything like this ever been considered?  Or is there, perhaps, some kind of workaround that would allow me to achieve this?

**Comment by zjturner** [comment]
Hi perhaps this is indeed what I need.  Or more generally, the whole idea of the `cmake-variants.json` file.   

Perhaps some hints about this file should be left in the configuration setting comments.  There was a link in the configuration settings that took me to the [Configuration Settings](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/configuration.md) page, but neither that page, the comments of the default `settings.json`, nor the `README.md` on the github homepage link to the page about build variants, so it was not obvious this feature even existed.  The only way you would know about it is if you manually browsed the `docs/` folder.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
