### ISSUE TITLE
Document the .cmaketools.json file

### ISSUE THREAD

**Issue by zjturner** [vector-of-bool/vscode-cmake-tools#247]
This file showed up in my `.vscode` folder, but there is no indication of what it is used for and what can appear in it.  Should users be editing this, or is it purely for internal use?  If it's the former, it should be documented.  If it's the latter, can a comment be injected into it that indicates that users should not modify it?

**Comment by vector-of-bool** [comment]
Sorry about that. The file is used internally, and I really need to find a better place to store that kind of data. I'm working on a refactor that should get the file out of there.

**Comment by arnonm** [comment]
Actually, this is useful to see what is generated. All I would do is add a comment that it is autogenerated and leave it at that

**Comment by vector-of-bool** [comment]
In the 0.11.0 release, the file is no longer used. Context information is instead stored in a VSCode memento.
