### ISSUE TITLE
${workspaceRoot} is not "normalized" if is used in "cmake.configureSettings"

### ISSUE THREAD

**Issue by bbosnjak** [vector-of-bool/vscode-cmake-tools#249]
Windows Example.
If  `${workspaceRoot}` is `C:\_test\myproject` and `cmake.configureSettings` is:
```
  "cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE":  "${workspaceRoot}/toolchain/toolchain.cmake"
  },
```
`CMakeTools/InitializeCache.cmake` will have backslashes in variable string value:
```
set(CMAKE_TOOLCHAIN_FILE "c:\_test\myproject/toolchain/toolchain.cmake" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)
```

**Comment by vector-of-bool** [comment]
Good catch.

**Comment by vector-of-bool** [comment]
Good catch

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
