### ISSUE TITLE
strange cmake configuration variable setting BUILD_TESTING

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#25]
I just did a test build of a minimalistic cmake project,
using "Visual Studio 14 2015" as cmake generator, i.e.

`"cmake.preferredGenerators": [
        "Visual Studio 14 2015"
    ]`

I noticed that I received a warning about the unused configuration setting BUILD_TESTING,
i.e., it was set on the cmake command line but never evaluated during the build.
I checked but found no documentation about that variable.
I suppose that that variable is only used by some special build backends (e.g. Ninja or similar).

However, it anyway gets set by the default option

`"cmake.configureSettings": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": true,
        "BUILD_TESTING": true
}`

I tried to customize the default setting of cmake.configureSettings by overwriting
it in my VSCode user settings, but that did not work due to #26 
, so there is no way for me to get rid of the unwanted BUILD_TESTING setting currently.

Could you please fix either #26, so I can remove it from the default settings,
or drop it from the default settings?

**Comment by vector-of-bool** [comment]
For reference, ``BUILD_TESTING`` is something related to CTest: [See this doc](https://cmake.org/cmake/help/v3.5/module/CTest.html). It is basically the standard way to enable/disable the building of test executables, rather than defining your own equivalent.

It is probably reasonable to remove this option as a default. I'll get on that soon.

**Comment by vector-of-bool** [comment]
PS: The reason you see this is because you are probably not running ``include(CTest)`` in your CMake config, which is a perfectly reasonable thing to do. It is probably unrelated to the generator you are using. Perhaps you only ``include(CTest)`` when not using VS?
