### ISSUE TITLE
"CMake: Debug Target" fails with "command 'vscode.startDebug' not found" error

### ISSUE THREAD

**Issue by alex-bermishev** [vector-of-bool/vscode-cmake-tools#253]
vscode v1.18.0
CMake Tools v0.10.2

**Comment by caux** [comment]
vscode.startDebug was removed:

https://code.visualstudio.com/updates/v1_17#_debug-api-updates

**Comment by vector-of-bool** [comment]
I need to pay better attention to those release notes... :-/
