### ISSUE TITLE
CMakeTools extension was unable to initialize

### ISSUE THREAD

**Issue by stigrs** [vector-of-bool/vscode-cmake-tools#255]
I get this error when I try to initialize CMake from VSCode on Windows 7 (64-bit): 
Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMakein\cmake.exe ENOENT

CMake is working from the command line, so that should not be the problem

**Comment by stigrs** [comment]
I installed the 32-bit version of vscode and the problem persists. However, when I installed the 64-bit insider version of vscode, everything is working fine.

**Comment by vector-of-bool** [comment]
That bad � appears in your path? What is the actual path to cmake.exe?

**Comment by stigrs** [comment]
No, the bad character does not appear in my path. My path to cmake.exe is "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"

**Comment by tcsmith** [comment]
I am also getting this error. 
Running on CentOS 7

CMakeTools extension was unable to initialize: TypeError: Cannot read property '1' of null

I'm running the latest version of code (1.19)

cmake version is 3.6.3 and builds the example https://www.codeproject.com/Articles/1184735/Quick-Start-to-Use-Visual-Studio-Code-for-Cplusplu from the command line

**Comment by kearney401** [comment]
I had a similar issue, but I reinstalled CMake and added it to my path, then the tools worked.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by vector-of-bool** [comment]
@LempereurBenjamin Has this worked for you in the past? What do you think caused this issue to arise?

Try running `CMake: Reset CMake Tools extension state`. This will reload the window and might make the error stop.

**Comment by LempereurBenjamin** [comment]
@vector-of-bool It never worked for me. I tried running the CMake Tools reset command without success.

**Comment by vector-of-bool** [comment]
Would you open up a new issue? If you have a cmake-variants file could you also provide the contents thereof?

**Comment by adityaruplaha** [comment]
I also have the same issue. Reset CMake didn't fix it. :(
