### ISSUE TITLE
CMakeTools extension was unable to initialize: Error: spawn EACCES [See output window for more details]

### ISSUE THREAD

**Issue by swarnendubiswas** [vector-of-bool/vscode-cmake-tools#257]
I get this error even after install cmkae 3.9.5 and customizing cmake path. There is no log visible in the output window.

VSC version: 1.18.0
OS: CentOS 7.4

**Comment by vector-of-bool** [comment]
You looked in the `CMake/Build` output window?

Was the extension working for you previously?

Also, try disabling CMake Server in your `settings.json`

**Comment by swarnendubiswas** [comment]
Yes, I looked in CMake/Build. It contains the same information `Error: spawn EACCES`.

I am not sure whether the extension was working previously, let me not make wrong guesses.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
