### ISSUE TITLE
Plugin unresponsive when running multiple windows of vscode using cmake-tools

### ISSUE THREAD

**Issue by Mischa-Alff** [vector-of-bool/vscode-cmake-tools#258]
Hi,

When you have multiple windows of vscode open (using `File -> New Window`), `vscode-cmake-tools` becomes unresponsive. Running commands via `Ctrl+Shift+P` does nothing, keyboard shortcuts for `vscode-cmake-tools` do nothing either. When opening each window, I get a separate log for either one indicating that the CMake server is launched correctly:

Window 1:
```
Loading CMake Tools from c:\foo\bar\.vscode\.cmaketools.json
Detected available environment "Visual Studio Professional 2017 - x86
Detected available environment "Visual Studio Professional 2017 - amd64
Detected available environment "MinGW - C:\MinGW
Started new CMake Server instance with PID 14832
```

Window 2:
```
Loading CMake Tools from c:\another\foo\bar\.vscode\.cmaketools.json
Detected available environment "Visual Studio Professional 2017 - x86
Detected available environment "Visual Studio Professional 2017 - amd64
Detected available environment "MinGW - C:\MinGW
Started new CMake Server instance with PID 27528
```

But after that, none of configuring/generating/building/installing/cleaning work.

Having multiple projects open is common when working on two or more different projects that depend on each other (e.g application depending on a custom library, a game and its engine, etc).

**Comment by vector-of-bool** [comment]
This is really strange. I've used the extension with multiple windows frequently. I can't imagine how two separate instances are interacting in such a strange way. Is this a recent development? Has it worked for you in the past?

**Comment by Mischa-Alff** [comment]
I forgot to mention that I'm using the CMake 3.10.0-rc5 release candidate (for C++17 support). I just downgraded to CMake 3.9.6, which is the current release (although the first download on their downloads page is the RC, which is curious), and it works with the current release version.

I think it's still a bug worth fixing to prevent the 3.10 release from breaking things for everyone.

**Comment by vector-of-bool** [comment]
Made a new issue #261

**Comment by vector-of-bool** [comment]
Going to continue in that issue
