### ISSUE TITLE
configuration setting cmake.configureSettings works additive but instead should work overwriting

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#26]
I just tried to overwrite the default setting

  "cmake.configureSettings": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": true,
        "BUILD_TESTING": true
    }

by my user settings as follows:

"cmake.configureSettings": {
        "HELLO": "WORLD"
    }

. I did so in trying to workaround Issue #25 .

However, that did not work as expected: instead of OVERWRITING the default values,
my settings were just ADDED, so the resulting cmake command was

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DBUILD_TESTING=TRUE -DHELLO=WORLD

instead of the expected

cmake -DHELLO=WORLD

I think that the user settings should always work overwritingly,
as that is the only possibility to correct them if they are wrong or unwanted.

**Comment by vector-of-bool** [comment]
The reason I forcibly set ``CMAKE_EXPORT_COMPILE_COMMANDS`` is with the anticipation of future tools using it. This generates a ``compile_commands.json`` which can be used by automated tools to perform code analysis (including autocomplete/IntelliSense, linting, etc.). For the ``BUILD_TESTING`` option, see my comments on #25.

**Comment by vector-of-bool** [comment]
Seems that being additive is the only behavior that vscode allows. perhaps I'll just remove any default configuration options.
