### ISSUE TITLE
Ninja path

### ISSUE THREAD

**Issue by xgalaxy** [vector-of-bool/vscode-cmake-tools#260]
Like CTest, can we have an preferences option that points to the path of Ninja?

**Comment by vector-of-bool** [comment]
Not actually sure. It's up to CMake itself to find Ninja, but it might be possible to tell CMake exactly where it is.

**Comment by xgalaxy** [comment]
I didn't know about the `cmake.configureSettings`. That seems to do the trick well enough.
Sorry for the trouble.
