### ISSUE TITLE
Doesn't work with CMake 3.10

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/vscode-cmake-tools#261]
Gotta get fixed.

**Comment by vector-of-bool** [comment]
This is caused by an upstream bug in CMake-server [here](https://gitlab.kitware.com/cmake/cmake/merge_requests/1498). I can work around it for now.

**Comment by Mischa-Alff** [comment]
I saw your fix was merged into CMake 3.10 and CMake 3.10 has been released, I just tested and no longer have the issue I mentioned in #258 . Thanks!

**Comment by vector-of-bool** [comment]
@Mischa-Alff, thanks for confirming!
