### ISSUE TITLE
customizing build Directory doesn't work with CMake server mode

### ISSUE THREAD

**Issue by mathieu** [vector-of-bool/vscode-cmake-tools#264]
using this local configuration
```json
{ 
    "cmake.buildDirectory": "${workspaceRoot}/build/${buildType}",
    "cmake.useCMakeServer": true
}
```

Trying to configure will try to build with `.../build/Unknown/...` path

reverting `cmake.useCMakeServer`to `false` works fine

**Comment by vogel76** [comment]
I have some idea how to correctly fix this issue in all cases. It looks like that it is impossible to evaluate valid binary path (from buildDirectory containing references to internal variables) in cases when plugin tries to read any info from cmakeserver (especially when tries to start the server). I think that simplest solution could be to provide internal function which will return stripped path of buildDirectory (which can reference only variables independent on build settings ie `workspaceRoot`. This way we can achieve that cmake-server pipe file will be created ie inside ${workspaceRoot}/build directly, but further cmake generated files inside subdirectories created accordingly to project settings.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by vector-of-bool** [comment]
@Randshot, is this issue still valid on the refactor branch?

**Comment by Randshot** [comment]
@vector-of-bool No, it isn't. I will close it now.
