### ISSUE TITLE
would be very handy for substitutions to respect the ${env:VARIABLE} syntax

### ISSUE THREAD

**Issue by rolandking** [vector-of-bool/vscode-cmake-tools#265]
Our cmake is run locally by a makefile which substitutes in various environment variables (eg CONDA_PREFIX which we use for package management). It would be very handy to be able to substitute environment variables into paths using the ${env:VARIABLE} syntax which is used in other extensions.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
