### ISSUE TITLE
debug ouput

### ISSUE THREAD

**Issue by lightgoleft** [vector-of-bool/vscode-cmake-tools#269]
Hello, 

I need to use regular expression to simplify the printed log on screen during debugging. However, there is no printout when debugging(MinGW debugger) internal console. And external console dose not support regular expression. Any way to solve this problem or I can redirect stdout to some monitor tool? 

Thanks

**Comment by vector-of-bool** [comment]
This may be outside the scope of this project, and you may want to look into the cpptools extension instead since that is the default debug driver that this extension uses

**Comment by lightgoleft** [comment]
ok. Thanks. I will turn to cpptools team for help.
