### ISSUE TITLE
Cmake Debug Build Hangs after "-- Generating done"

### ISSUE THREAD

**Issue by nsalerni** [vector-of-bool/vscode-cmake-tools#270]
Hello,

I am trying to build a cmake project and the cmake tool consistently hangs after reaching "-- Generating done". I have an identical setup in Clion and Cmake build works there.

Any assistance would be appreciated!

Regards,
Nick

**Comment by vector-of-bool** [comment]
Could I get some information regarding your dev platform, CMake version, etc?

**Comment by nsalerni** [comment]
Any updates?

**Comment by vector-of-bool** [comment]
Sorry I vanished, and I'm sorry to say that I have no updates. Without a way to reliably reproduce the issue, I can't really make progress. Is there anything significant about your CMake settings, as far as you can tell?

**Comment by Randshot** [comment]
@nsalerni Could you provide us an example project, so that we can debug it?
Until then, I will close this issue.
You can also check whether this issue still persists in the latest **0.11.0-beta4**.

**Closed**.
