### ISSUE TITLE
Location of cmake-variants.yaml

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#275]
Thanks for your development of this vscode extension. It works already fine. I had only some problems to use the BETA it in my projects. 

### Brief Issue Summary
The variant management for switching between different kind of CMake Configuration works in the most cases. I used your description (https://vector-of-bool.github.io/docs/vscode-cmake-tools/variants.html)
to setup the describtions of my variants.  In the first tries I placed the file (cmake-variants.yaml) it to the wrong directory (.vscode). The extension expects it in the workspace root.

### Expected:
I would see the cmake-variants.yaml file as a IDE dependent file and would expect that it´s placed inside the .vscode folder.

In the documentation is the location of this cmake-variants.yaml missing.

### Platform and Versions
- **Operating System**: Windows 10
- **CMake Version**: 3.9
- **VSCode Version**: 1.19
- **CMake Tools Extension Version**:  0.11 BETA
- **Compiler/Toolchain**: MinGW GCC 6.3 gnu-arm-none-eabi 6.3

**Comment by vector-of-bool** [comment]
Thanks for checking out the documentation!

This issue has appeared before, and I thought I had it fixed. I'll take a look at it.

**Comment by vector-of-bool** [comment]
Docs should be updated with next (possibly beta) release. Also added support for putting variants file in .vscode
