### ISSUE TITLE
Documentation of subtitute values

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#276]
### Brief Issue Summary

The substitute values feature is a powerful tool to switch the build directory or other parts in the project.
For the use of the substitution the possible variables are missing in the documentation. 

### Expected:

I would like to use the substitute values to change the build directory dependent on the selected variants or the buildType.
I would expected that the substitute value chapter in documentation has a list with the possible substitution values and there meaning.

### Platform and Versions

    Operating System: Windows 10
    CMake Version: 3.9
    VSCode Version: 1.19
    CMake Tools Extension Version: 0.11 BETA
    Compiler/Toolchain: MinGW GCC 6.3 gnu-arm-none-eabi 6.3

**Comment by vector-of-bool** [comment]
I intended to add those to the docs, but not until I had them all sorted out. There's a few changes I want to do on variable substitution before publicly posting the full list, but it's on the roadmap for 0.11.0
