### ISSUE TITLE
when doing a clean build, you get an error message about "file not found CMakeCache.txt"

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#28]
When you do a REAL clean build,
i.e., you are completely DELETING the ./build subfolder of your sourcecode,
including all of its contents AND the folder itself,
and then are using your (nice!) plugin to launch a build without first launching
a manual "CMake: configure" command, then your plugin will display an error message
"file not found: build/CMakeCache.txt".
It would be much nicer if it instead could detect that either the folder OR that file
is not present, and in that case will automatically launch a cmake configure
instead of displaying that error message.

**Comment by vector-of-bool** [comment]
Hmm... Sounds like a problem. Could I get a more precise list of steps to reproduce the issue? I'll get on this one.

**Comment by vector-of-bool** [comment]
This behavior may have been changed/fixed in the 0.4.0 release. Could you try to reproduce the issue and confirm that it still occurs?

**Comment by MinnieTheMoocher** [comment]
the behaviour is now that I get an error message which requests me to first configure the project.
It allows me 2 reactions:
- do that
- close

I can not see a reason for that prompt. Why not automatically launch the "configure" step,
then the build?
If I wouldn't want that, I still could press the "stop" button.
I would find it much more convenient if I could completely skip worrying about
the "configure" step, and instead just use "CMake: build" all the time
(provided that I have present proper user settings and/or workspace settings).

**Comment by vector-of-bool** [comment]
You're probably right. I've considered just removing that prompt. Usually, the only time I've seen it is when I accidentally strike the F7 key in a non-CMake project, and even then it will get caught on the current workspace not being a CMake project.

**Comment by vector-of-bool** [comment]
Changed in next release
