### ISSUE TITLE
Cannot build due to CMakeTools Error:  Invalid Backend promise

### ISSUE THREAD

**Issue by hvdonge** [vector-of-bool/vscode-cmake-tools#281]
### Brief Issue Summary

CMakeTools Error: Invalid Backend promise
or
CMakeTools TypeError: Reduce of empty array with no initial value

### CMake Tools Log

Below you can find the output of the CMake/Build panel.

```
Loading CMake Tools from c:\msys64\home\(...)\.vscode\.cmaketools.json
```

### Platform and Versions

- **Operating System**: Windows 7-64
- **CMake Version**: 0.017
- **VSCode Version**: 1.19.1
- **CMake Tools Extension Version**: 0.10.4
- **Compiler/Toolchain**: ```gcc version 6.3.0 (Rev2, Built by MSYS2 project)```

**Comment by vector-of-bool** [comment]
This dups #237, a longstanding mystery.

I'm hoping to get this all worked out for the 0.11.0 release.

**Comment by atrantan** [comment]
@hvdonge In windows, you need to set the variable `cmake.cmakePath` to `C:/Program Files/CMake/bin/cmake.exe` in place of `cmake` in your vscode settings

**Comment by hvdonge** [comment]
> @hvdonge In windows, you need to set the variable cmake.cmakePath to C:/Program Files/CMake/bin/cmake.exe in place of cmake in your vscode settings

Does that also work with `"cmake.cmakePath": "C:/msys64/mingw64/bin/cmake.exe"`?

**Comment by vector-of-bool** [comment]
@hvdonge, that should work. Did you see any changes when you added that setting?

**Comment by hvdonge** [comment]
@vector-of-bool The setting has been there before CMakeTools failed. I have not changed it.

**Comment by Athius** [comment]
Hi,

I have exactly the same issue. I'm on Windows 10, with VS Code 1.19.3, CMake 3.10.2 and CMake Tools 0.10.4

I set cmake.cmakePath variable but nothing change. For more information I can launch cmake from a DOS prompt.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
