### ISSUE TITLE
No CMake in windows search path

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#285]
### Brief Issue Summary

The extension (ENOENT)  throws no exception when no CMake is found.  

### Expected:

I would expect that a notification opens. This informs me about the no existing or found Cmake binary and were I can get/download it.

**Comment by vector-of-bool** [comment]
This isn't a use case I've ever thought of, but it would indeed be helpful to provide a download link.

**Comment by Randshot** [comment]
To be honest, I think that this shouldn't be needed. But it would be nice anyway.

**Comment by vector-of-bool** [comment]
I think this has been covered by #296.

Having the option to download CMake would be nice, especially if it were so friction-free that it could get the entire userbase off of CMake < 3.7.2
