### ISSUE TITLE
CMakeTools extension was unable to initialize

### ISSUE THREAD

**Issue by pdemil** [vector-of-bool/vscode-cmake-tools#287]
### Brief Issue Summary

Trying to load the loramac-net project in Visual Studio Code.

Error: CMakeTools extension was unable to initialize: TypeError: Reduce of empty array with no initial values [ See output window for mor details]

In the output window:
Loading CMake Tools from C:\<mydir>\LoRaMac-node\.vscode\.cmaketools.json

When I look for hidden files in File Explorer, I don't see .cmaketools.json.
I do see c_cpp_poroperties.json, launch.json, settings.json

Who should make the .cmaketools.json file?

Next I disabled make-server in  settings.json.
New error appears: CMakeTools extension was unable to initialize: Error: Invalid backend promise [ See output window for more details]

Maybe related to https://github.com/vector-of-bool/vscode-cmake-tools/issues/237 ?

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.10.1
- **VSCode Version**: 1.19.1
- **CMake Tools Extension Version**: 0.10.4
- **Compiler/Toolchain**: gcc-arm-none-eabi-7-2017-q4

### Other Notes/Information

Maybe it is a good moment to test your 0.11 beta :-)

**Comment by pdemil** [comment]
Maybe the release notes of VSCode 1.19.1 give a hint?
https://code.visualstudio.com/updates/v1_19
" As a result of fixing issue 40351, we now require you to ptass "-" as an argument to explicitly signal that the output of a piped command is coming in through stdin. For example: echo Hello World | code - (Windows) and ps aux | grep code | code - (macOS, Linux). This is a breaking chage from 1.19.0, please update any scripts that make use of this functionality".

**Comment by vector-of-bool** [comment]
I've seen the "emptry reduce" error before, and thought I had it fixed. Not sure what's going on here... Can you give the beta a try and see what you get?

**Comment by yeyingsitan** [comment]
I have the same problem.

The status bar is "CMake:Unconfigured Project: UnitTest: Ready".
I click it, then get a error "CMakeTools extension was unable to initialize: TypeError: Reduce of empty array with no initial value".
The output window's message is "Loading CMake Tools from c:\swept\msys64\home\YEY2HZ\Panda1221.vscode.cmaketools.json

In my system, I only have VSCODE 1.18.1, which is different from #234. They all have VS 2017 installed but I don't.
How to deal with it???

**Comment by pdemil** [comment]
It is now working with 
VSCode Version: 1.19.0
CMake Tools Extension Version: 0.11.0 beta 3

**Comment by vector-of-bool** [comment]
I'm going to close as a dup of #287.
