### ISSUE TITLE
Cancel Build not Working

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#29]
Hello,

I have `{ "key": "cmd+b", "command": "cmake.buildWithTarget" }` in my `keybindings.json` file. When I hit `cmd+b`, I get the pop-up box asking me to enter a build target. This claims I can hit `Esc` to cancel. However, if I do so, it triggers a `make all`.

Do I have a setting wrong somewhere or is this a bug? Thanks.

**Comment by vector-of-bool** [comment]
This is a bug and has a pretty simple fix. I'll get on it.

**Comment by spinicist** [comment]
Thanks, it works now.

**Comment by MinnieTheMoocher** [comment]
for readers coming here: checkout also #35
