### ISSUE TITLE
0.11.0-beta4: Error: spawn cmake ENOENT {}

### ISSUE THREAD

**Issue by mkaring** [vector-of-bool/vscode-cmake-tools#296]
### Brief Issue Summary

The tools are property detecting the presence of Visual Studio and create the entries in the `cmake-kits.json` file. It does not select any kit automatically, When trying to select a kit, it raises the following error:
```
Error: spawn cmake ENOENT {}
```

### Expected:

It should be possible to select a kit, or at least a message should appear that gives any information regarding the nature of the problem.

### Apparent Behavior:

The detection of the kits seems to work fine, but something is wrong when trying to select them. I do not know what the ENOENT means. The last message in the logs indicates that the plugin is trying to start cmake. But there is no report that this actually worked.

### CMake Tools Log

The following messages appear when starting vscode:

```
[main] Safe constructing new CMakeTools instance
[kit] Constructing KitManager
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[rollbar] Checking Rollbar permissions
[rollbar] Rollbar enabled?  true
[variant] Loaded new set of variants
[kit] Second phase init for KitManager
[kit] Re-read kits file from prior session
[kit] Re-reading kits file C:\Users\<name>\AppData\Roaming\CMakeTools\cmake-kits.json
[kit] Loading new set of kits
[kit] Successfully loaded 3 kits
[kit] Active kit set to null
[main] Starting CMake driver
```

When trying to manually selecting a kit using the tool bar, the following message is added.

```
[rollbar] Unhandled exception: Unhandled Promise rejection: selectKit Error: spawn cmake ENOENT {}
```

When starting vscode without an already created kits file the following messages appear:

```
[main] Safe constructing new CMakeTools instance
[kit] Constructing KitManager
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[rollbar] Checking Rollbar permissions
[rollbar] Rollbar enabled?  true
[variant] Loaded new set of variants
[kit] Second phase init for KitManager
[kit] Rescanning for Kits
[kit] Scanning for Kits on system
[kit] Scanning directory ... for compilers
(shortend)
[kit] Found 0 kits in directory ...
(shortend)
[kit] Testing GCC-ish binary: C:\Strawberry\c\bin\gcc.exe
[kit] Found 0 kits in directory ...
(shortend)
[kit] Detected GCC compiler kit: C:\Strawberry\c\bin\gcc.exe
[kit] Checking for kit: Visual Studio Professional 2017 - ...
(shortend)
[kit] Checking for kit: VisualStudio.14.0 - ...
(shortend)
[kit] Found 1 kits in directory C:\Strawberry\c\bin
[proc] Executing command: C:\Users\<NAME>\AppData\Local\Temp\vs-cmt-0.5467378164347365.bat
(shortend)
[kit] Found Kit: GCC 7.1.0
[kit] Found Kit: Visual Studio Professional 2017 - x86
[kit] Found Kit: Visual Studio Professional 2017 - amd64
[kit] Saving news kits to C:\Users\<name>\AppData\Roaming\CMakeTools\cmake-kits.json
[kit] Re-reading kits file C:\Users\<name>\AppData\Roaming\CMakeTools\cmake-kits.json
[kit] Loading new set of kits
[kit] Successfully loaded 3 kits
[kit] Active kit set to null
[kit] C:\Users\<name>\AppData\Roaming\CMakeTools\cmake-kits.json saved
[main] Starting CMake driver
```

When trying to manually selecting a kit using the tool bar, the following message is added.

```
[rollbar] Unhandled exception: Unhandled Promise rejection: selectKit Error: spawn cmake ENOENT {}
```

### Platform and Versions

- **Operating System**: Windows 10 - Verion: 1703 - Build: 15063.786
- **CMake Version**: Visual Studio 2017 embedded version: 3.9.2-MSVC_2 (at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin)
- **VSCode Version**: 1.19.1
- **CMake Tools Extension Version**: 0.11.0-beta4
- **Compiler/Toolchain**: Visual C++ 2017, GCC 7.1

### Other Notes/Information

While it seems to detect the Visual Studio kit properly, it seems it is not using the cmake from Visual Studio as I'd expect it to do.
The error also it shown for every command I tried to execute related to the cmake extension. Even things like `resetState` raise this error:

```
[rollbar] Unhandled exception: Unhandled Promise rejection: resetState Error: spawn cmake ENOENT {}
```

**Comment by KoeMai** [comment]
Did you try to set "cmake.cmakePath" in your user settings?

**Comment by mkaring** [comment]
Isn't the point of this extension to locate the cmake implementations installed automatically? What point is there in setting the path of the cmake executable by hand?

Anyway. If I do, the error changes to 
```
[rollbar] Unhandled exception: Unhandled Promise rejection: selectKit Error: Unable to determine CMake Generator to use {}
```

Is it possible that the extension is not able to use the cmake installation that is part of the visual studio?

**Comment by KoeMai** [comment]
The first problem is simular to #285. 
The `cmake.cmakePath` is the path with name of the executeable. 
The default value is `cmake`. Is your cmake bin folder in the windows path variable?

**Comment by KoeMai** [comment]
For the second problem it would be helpful to see the debug output.

**Comment by mkaring** [comment]
cmake is not in the path.
How do I enable the debug output?

**Comment by KoeMai** [comment]
I use in the most cases this way:
Menu -> help -> toggle developer Tools - > goto tab console -> rights click into messages -> Save as...

**Comment by vector-of-bool** [comment]
In beta5 it will search more than just $PATH for the CMake executable. Should fix this for users who have CMake installed but not on the $PATH.

**Comment by AlexConlne** [comment]
thanks , makefile is wrong.I have fix.
