### ISSUE TITLE
CMake configuration and generation always run before build

### ISSUE THREAD

**Issue by gomons** [vector-of-bool/vscode-cmake-tools#298]
CMake configuration and generation steps usually take more time than build step for me. It would be nice to have option cmake.configureBeforeBuild or similar.

**Comment by vector-of-bool** [comment]
Sorry for the delay. What extension version are you using?

**Comment by gomons** [comment]
The extension version is 0.0.17

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
