### ISSUE TITLE
stop the spam!!

### ISSUE THREAD

**Issue by TankTheFrank** [vector-of-bool/vscode-cmake-tools#301]
Spamming me every few minutes with "Like CMake Tools? I need your feedback to help make this extension better!" and "Feeling adventurous? CMake Tools has a beta release and draft documentation, and I need help testing it!" REGARDLESS if I press or not "don't ask me again" makes me keep mentioning your mother in various serious sexual contexts...

**Comment by vector-of-bool** [comment]
I'm so sorry! I thought I tested that well, but apparently not...

**Comment by vector-of-bool** [comment]
Also sorry that it took so long to respond, I've been occupied...

I just turned the messages off. I was trying to find a way to solicit feedback, and I was careful to try and ensure that it was "disable-able," but I seem to have failed horribly.
