### ISSUE TITLE
REQ: Option to set up MSVC environment prior to running cmake server

### ISSUE THREAD

**Issue by hokiedsp** [vector-of-bool/vscode-cmake-tools#303]
Hi, this is a feature request post.

First of all, a great extension and thank you for all your work!

Now, one of the most frustrating thing about vscode in Windows to me is its disconnect with the MSVC compilers, and unfortunately cmake-tools is a victim of it as well as far as I can tell. However, I wonder if that problem can easily be worked around in the cmake-tools by spawning the server child process with a batch file.

Line 564 of server-client.ts, this process is spawned by:

      this._proc = proc.spawn(
        params.cmakePath,
        ['-E', 'server', '--experimental', `--pipe=${pipe_file}`], {
          env: params.environment,
        });

For Windows+MSVC environment, could you replace this line with: 

      this._proc = proc.spawn('cmd.exe', ['/c', 'msvc_cmake.bat']);

where the batch file looks something like:

----msvc_cmake.bat----
CALL C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat amd64
CALL cmake -E server --experimental --pipe=$(pipe_file)
------------------------

MSVC batch file takes several options and shall be customized to match user's cmake environment selection.

To make this viable, the architecture flag "x86" vs "amd64" may need be fixed via an extension's option but I don't see it being a detriment.

I'm not familiar with node.js enough to experiment with your code, but if it works, it would be a great feature.

FYI, I got the spawning a batch file from this page:

https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows

Thanks for reading!

**Comment by vector-of-bool** [comment]
Have you tried using the beta release? This was a bug that I fixed in the beta. Before the fix, changing the VS version required a full restart of VSCode for it to load properly. In the beta release, I fixed it so that it would restart CMake in the VS environment once you selected a VS kit.

**Comment by hokiedsp** [comment]
Ah, huh. Should've tried the beta earlier!! Love the tool. Thanks a bunch and keep up the great work!
