### ISSUE TITLE
Custom CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by KobNael** [vector-of-bool/vscode-cmake-tools#304]
### Custom CMAKE_MODULE_PATH ?

I've seen that you used your own (build/CMakeTools) but it overrided my own parameter, hence I've not been able to successfully configure my project.
Is there a way to provide its own path in addition to yours ?

**Comment by vector-of-bool** [comment]
What CMake version are you using? In the beta release, I've removed the functionality that required setting the module path. You'll still see full functionality if you are on CMake 3.7.2 or newer, and slightly reduced if you are running anything older than that.

**Comment by KobNael** [comment]
I use cmake 3.9.5.
I've made a workaround by using an additional variable in my CMakeList.
I'll test with the next release ;)

**Comment by wenglorfranz** [comment]
"cmake.configureSettings": {
        "CMAKE_MODULE_PATH":"\"/opt/toolchain/cmake\"",       
        },
This results in InitializeCache.cmake
set(CMAKE_MODULE_PATH "\";/;o;p;t;/;t;o;o;l;c;h;a;i;n;/;c;m;a;k;e;\";/home/user/workspace/hilscher/_build/CMakeTools" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)

**Comment by Randshot** [comment]
@wenglorfranz I don't see any issues in the latest Beta4.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
