### ISSUE TITLE
0.11.0-beta4: cmake.configureArgs ignored?

### ISSUE THREAD

**Issue by hokiedsp** [vector-of-bool/vscode-cmake-tools#305]
### Brief Issue Summary

cmake.configureArgs setting in the workspace .vscode/settings.json file appears to be neglected.

For example, my settings.json file in a project looks like:

{
   // Additional arguments to pass to CMake when configuring
   "cmake.configureArgs": [
      "-DUSE_FORTRAN=OFF"
   ]
}

And I placed on the first line of the project root's CMakeLists.txt:

message("USE_FORTRAN=" ${USE_FORTRAN})

When I build the project, it prints

"USE_FORTRAN="

When I configure the same project in terminal with the argument 

"cmake .. -GNinja -DUSE_FORTRAN=OFF"

I get the expected output:

"USE_FORTRAN=OFF"

### Platform and Versions

- **Operating System**: Windows 7
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.19.2
- **CMake Tools Extension Version**: 0.11.0-beta4
- **Compiler/Toolchain**: Ninja + Visual C++ 2017

**Comment by hokiedsp** [comment]
A quick follow-up with a related bug. 

The cmakes.buildEnvironment setting (possibly also other cmake.xxxEnvironment settings) also  seems to be ignored. For that matter, the operation of cmake.xxxArgs should also be checked. Thanks!

One of these days, I'll find enough time to learn node.js and can actually debug these things myself...

**Comment by Randshot** [comment]
@hokiedsp You are right.
In the current Beta4, the `configureArgs` settings and all `*Environment` settings, except for the `testEnvironment` one, don't get used yet.

**Comment by Randshot** [comment]
PR #317 merged.
