### ISSUE TITLE
command:cmakeLaunchTargetProgramPath doesn't work

### ISSUE THREAD

**Issue by cswiedler** [vector-of-bool/vscode-cmake-tools#307]
### Brief Issue Summary

Setting this in launch.json generates an error:
            "program": "${command:cmakeLaunchTargetProgramPath}",

VSCode displays "Please set up the launch configuration file for your application. command 'cmakeLaunchTargetProgramPath' not found"

Same result for cmakeDebugTargetProgramPath.

Additionally, is it possible to have a config option similar to cmakeLaunchTargetProgramPath for setting the cwd of the launched process to a path relative to the target? Something like cmakeLaunchTargetProgramDir.

### Platform and Versions

[[For issues, fill out the following. Otherwise delete this section.]]

- **Operating System**: [[Ubuntu 16.04]]
- **CMake Version**: [[3.10]]
- **VSCode Version**: [[1.19.3.]]
- **CMake Tools Extension Version**: [[0.11-beta4]]
- **Compiler/Toolchain**: [[clang/gdb]]

**Comment by loaden** [comment]
ping

**Comment by vector-of-bool** [comment]
@loaden have you tried using `${command:cmake.launchTargetPath}` in your `launch.json`?

**Comment by vector-of-bool** [comment]
There was a bug with `cmake.launchTargetPath`, but it will be fixed in the 0.11.0 final release, hopefully this week.

I've also updated the docs to point to `cmake.launchTargetPath`
