### ISSUE TITLE
Parallel Build doesn't work for install target

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#31]
If I build the default target, `-j 6` is correctly passed to `cmake --build` (6 is the default number of threads automatically detected).

If I choose any single particular target, the same happens.

EXCEPT if I pick the `install` target. Then the parallel build option is not passed to CMake. On my development machine `install` is the target I build most often, as my testing scripts use the installed versions. Am I doing it wrong or is this a bug?

**Comment by vector-of-bool** [comment]
I have it hard-coded to actually disable parallel building of the install target (as well as the ``clean`` target). Honestly, I don't remember if I had a good reason to do that. I can probably just undo that change and see if anything bad happens?

**Comment by spinicist** [comment]
Yes please - I'm happy to test!

**Comment by MinnieTheMoocher** [comment]
Yes, may I also ask for removing that hardcoded prevention?
My reasoning is:
the tool that spawns (here: VSCode) the build process (here: cmake) should not
prevent me from doing the build as I like it.
cmake allows me to spawn a -j4 build for "install", so VSCode should as well.
If that parallel build step is broken, it needs to be fixed inside your CMakeList.txt files
(your build process is broken), not in the editor (VSCode) spawning it.
