### ISSUE TITLE
General comments about first contact

### ISSUE THREAD

**Issue by stayprivates** [vector-of-bool/vscode-cmake-tools#314]
Just want to give some feedback about my first contact with VisualCode and CMake Tools.

I did not set my hopes to high because of expected roadblocks.  My goal is to move away from Eclipse.  We are using it to build QNX executables, which implies a cross-compiler environment given development is done on Ubuntu.   Luckily our stuff is using CMake, and after 3 hours of getting to know VC and CMakeTool I manage to get a decent working environment!!!

Thanks for making cmake-tools !

**Comment by vector-of-bool** [comment]
Thanks for the kind words! It really means a lot.
