### ISSUE TITLE
Suggestion: Restart build by invoking cmake.build twice

### ISSUE THREAD

**Issue by henricryden** [vector-of-bool/vscode-cmake-tools#318]
Running build when another build is running results in an error pop up with this message:

> A CMake task is already running. Stop it before trying to build.

This is reasonable, but a bit annoying as this pupup must be closed by clicking the "Close" button. The only way that I know of that stops the build is the little "stop" icon at the bottom.

I suggest that if you invoke the cmake.build (F7 by default) command twice in a short interval such as one second, the current build is cancelled, the popup is closed, and a new build starts.

**Comment by Randshot** [comment]
@henricryden I would suggest adding a setting field (e.g. `cmake.autoRestartBuild`) that enables this behavior.

**Comment by henricryden** [comment]
@Randshot Sure, it doesn't have to be on by default.

**Comment by vector-of-bool** [comment]
Closing since this PR was merged.

**Comment by Trass3r** [comment]
For the record, that workaround has been removed in https://github.com/microsoft/vscode-cmake-tools/commit/6d04ebd7d1e86c11d17f28296a0d9d22e2fabee0.
"task is already running" still happens to me because of https://github.com/microsoft/vscode-cmake-tools/issues/570.
