### ISSUE TITLE
Approach for extension test

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#328]
The idea behind the refactoring #323 was to separate internal tests from extension tests. We have at the moment not so many tests. This makes it easy to refactor. Sorry that I did not wrote my idea done for discussion and started immediatly.

# Test definitions

The **internal tests** are tests which use only parts of the extension (like only the kitmanager or the kit scan part). This test are only unit tests for components. This componets may can interact with filesystem, cmake, or other parts.

The **extension test** are tests in the user view. I would like to use them to check if the complete extension is working correct. All components work correct together. The first one which I have written are more trivial ones `no-kits-present.test.ts`.

# Extension test

My focus is at the moment on the extension tests. I hope we get soon the open pull requests merged.

## Test management

I like the approach with CTest in the `smoke` branch to manage the different test environments. 
The batch files make it hard to see which test environment failed.

## Test framework technologies

I would avoid to use a new test description language (the yaml-files). The idea of my refactoring was needed to make it possible for testing #290. In this case I need to stub some vscode function. 
Its is very easy with the typescript test frameworks (mocha, chi and sinon). 
You can see it in the ` Kits test` ->`GUI tests`

## Structure of tests

The structure in the `smoke` branch follows the same idea like my refactored `extenstion_tests` subfolders.
The folder is always structured in:

+ extension_tests
   + <name_group_of_tests>
      - project_folder
      - test

The `project_folder` contains a valid or broken CMake project with source files.
The `test` folder contains the related tests.

## Test result verification 

I like to use the extension like the users. In this case I need run function of the extension by the test script. The test expectation can be checked against 
- a executeable which provides a output
- cmake generated cache files or message 
- outputs provided by the extension itself (vscode messages/warning)

I hop you like the plan und hop to get some feedback.

@Randshot I would like to test, the commands you added first by an extension test. The tests on CMakeDriver level would mean we need to write the test twice, because CMake 3.5 and CMake 3.7 work different in the extension. 

# Open sub tasks

- [X] Task 1: Extract helper classes from test file into separate helper files, see PR
- [x] Task 2: Make all test available for Linux/MacOs and Windows (see Q1, Q2)
- [x] Task 3: Repair and make pending events available on all plattforms.

**Comment by Randshot** [comment]
@KoeMai What do you mean by commands? Which PRs of mine are you talking about?

**Comment by KoeMai** [comment]
Sorry, I was wrong you have added settings. The settings are used by the commands. The testing of the settings should work as well.

**Comment by KoeMai** [comment]
I pushed my first draft for configure and build test to ` feature/add_build_tests` (only the build test is active).

**Comment by vector-of-bool** [comment]
The reason I went with the yaml files was to abstract away a lot of the boilerplate with writing the test setup/teardown, making it trivial to add more tests.

@Randshot, what do you think?

**Comment by Randshot** [comment]
TBH, I don't have any idea what yaml files you are talking about :/
My priorities for testing would be easy integration and (modular) extensibility.

**Comment by vector-of-bool** [comment]
We're referring to the test stuff I threw together on the `feature/smoke` branch.

**Comment by Randshot** [comment]
I will look at it a bit closer after dinner.

**Comment by Randshot** [comment]
@KoeMai What is you reasoning for not using yaml files?
I like the idea of reducing boilerplate as much as possible.

**Comment by KoeMai** [comment]
I would like to reduce the complexity of the tests too. In the same way I do not want to loose the flexibility of a testing framework. 

I try to find test method's for 
- manipulate environment variables
- forward environment variable to cmake
- settings from settings.json
- catch error notification like in the ninja bug. 
I do not know how I can check them without individual test helpers. 

Both ways have their benefits. I like the test scenario views of yaml but I see the same possibilies in a test framework. In both ways I can write helpers. In the one way I have to write them to have access in the scenario and in the other one only if I see the reuseability or to make it more readable.

**Comment by vector-of-bool** [comment]
I guess it's a matter of just eliminating duplication. I chose YAML so that the only thing in those test directories were the steps to run the test (no setup/teardown). I abstracted the setup/teardown into a test runner class you can see in the smoke directory.

Have you looked at writing a test runner class? You might get away with putting all the setup/teardown logic and your helper methods in the single class and keep the individual test directories down in size to just concerning themselves with running the exact test for their own directory.

**Comment by Randshot** [comment]
@KoeMai I have taken a look at your `add_build_tests` branch and you left a comment asking how to get the path to the executable or the output of the executable.
I don't know the best approach for this, but one that came to my mind is by using custom targets to run the executable. The executable itself would have to write it's output to some file, or we somehow catch the output when CMake runs the custom target.

**Comment by Randshot** [comment]
@KoeMai I have a working `CMakeLists.txt` file here:
```
cmake_minimum_required(VERSION 3.0.0)
project(TestBuildProcess VERSION 0.1.0)

add_executable(TestBuildProcess main.cpp)

add_custom_command(
    TARGET TestBuildProcess
    POST_BUILD
    COMMAND $<TARGET_FILE:TestBuildProcess> > output.txt
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMENT "Running in ${CMAKE_CURRENT_BINARY_DIR}"
)

add_definitions(-D_CMAKE_VERSION="${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}")
```
The `output.txt` file will be in the `build` directory.

**Comment by Randshot** [comment]
@vector-of-bool @KoeMai I have a working example for getting the output of a built project executable.
You can find it in the [feature/get_output_example](https://github.com/vector-of-bool/vscode-cmake-tools/tree/feature/get_output_example) branch.

**Comment by KoeMai** [comment]
Yes I saw it. What do you think about one of this approachs? 
1. https://www.npmjs.com/package/mocha-shared 
2. https://www.npmjs.com/package/mocha-bdd-extend
Both combines our ideas and keep the tests lean and flexible.

**Comment by KoeMai** [comment]
I did some refactoring without the packages from above.

@Randshot I merged your branch into feature/add_build_tests

**Comment by Randshot** [comment]
@KoeMai If I remember right, I pushed some changes to my branch that fixes the appveyor problems.
I didn't manage to fix the travis problems though.

**Comment by vector-of-bool** [comment]
@KoeMai, mocha-shared and mocha-bdd-extend look like what I was hoping for. Nice.

Also, it looks like you're having trouble with driver startup on your branch. My tslint branch did some cleanup of driver startup that might affect what you are doing. The driver startup needs a bit of refinement, as it's very easy to accidentally have driver startup depend on itself.

**Comment by Randshot** [comment]
@KoeMai It seems like appveyor doesn't select a kit and travis just skips both tests.

**Comment by Randshot** [comment]
@KoeMai I think I have fixed the issues with appveyor.
You can find the fix in the [appveyor_init_debug](https://github.com/vector-of-bool/vscode-cmake-tools/tree/appveyor_init_debug) branch.
The only problem is, that the test checks for CMake version 3.9, which doesn't always fit the CMake version appveyor uses.

**Comment by vector-of-bool** [comment]
> doesn't always

Meaning the CMake version differs between AppVeyor machines? :fearful:

Kit scanning for VS prior to 2017 seems a bit more flakey than I'd like.

**Comment by KoeMai** [comment]
Oh you are right, thanks for your help.

At the moment I see this tests as a draft. So it works only on a subset for cmake and compilers + build system.

@vector-of-bool did you took a look at the tests? At the moment I use non of the tool packages,  but I think the style is very clear. Should we try to convert it more in to shared blocks?

**Comment by vector-of-bool** [comment]
I've looked it over a bit. It looks alright, and will be better once we get some of the boilerplate down.

I'd like to say that `cmake.stop` _should not_ stop the driver process, as I feel it will be a nightmare to debug in the future. I'd go the route of having CTest just start a new VSCode instance for each of the main tests, just to be sure we have a completely clean state, which just stopping the driver won't actually achieve.

**Comment by KoeMai** [comment]
Now I have a working draft and travis and appveyor (most parts) are happy.

Next steps:
- [ ] Task 1: Extract helper classes from test file into separate helper files.
- [ ] Task 2: Make all test available for Linux/MacOs and Windows (see Q1, Q2)
- [ ] Task 3: Repair and make pending events available on all plattforms.

For the next steps we need to define some environment settings for travis and appveyor
- [ ] Q1. What are our default compilers? CLang? Linux and MacOS.
- [ ] Q2. What is our default build system? Linux MacOS and Windows (The older VS versions fail because no build system is prevered)
Q3. Do we want to use this code base or do we want to refactor it to a other style or do we want to use the smoke branch?

I would create a pull request out of the `feature/add_build_tests` branch if task 1 is finished.

**Comment by vector-of-bool** [comment]
For Q1, I'd like to expand the test matrix as wide as possible. That means running Travis tests against both GCC and Clang for both Linux and macOS. May even multiple versions of each compiler.

For Q2, I'm not sure what you mean? You mean the CMake Generator? Again, I'd like to have a matrix for each backend that the extension supports.

For Q3, I don't feel strongly that my `feature/smoke` branch be used. If we can get what we need from Mocha, I'll be happy to use that. I'd like to start off a fresh new VSCode instance for each of the big smoke tests, though, just to make sure everything is clean when we start. I was using CTest for this, but it can be anything that can just launch a bunch of processes.

@ytimenkov was doing work in his own fork to make the backend system much more modular and testable. It may be worth looking to adopting aspects of his approach in the future.

**Comment by ytimenkov** [comment]
I've updated #190 with what I was thinking about and what I've managed to do.
If you like the idea I think it should be possible to drag in my changes firstly putting them under existing functionality (e.g. implement `CMakeServerClientDriver` in terms of new components), and then gradually remove these wrappers.

**Comment by ytimenkov** [comment]
Another thought about build matrix and a set of compilers:
After VS code implemented support for task discovery I thought that it might be good if this mechanism was (re)used for building with CMake.

**Cons:**
1. No ability to show progress bar during the build, but user will see nice colored output in the terminal.
2. Hooks? But their absence can be mitigated by watching files for changes.

**Pros:**
1. Ability to control and customize build process, including error parsers.
2. Specify as pre-launch task in debugger.
3. Similar template can be replicated for multiple tasks and/or more complex scenarios.

This way most interesting cases are:
1. Makefiles/Ninja on Linux mac with gcc/clang.
2. Multi-configuration generators like Visual Studio.
3. Weird generator+compiler combination like ninja + Visual Studio.

**Comment by ytimenkov** [comment]
What I think is of interest is different versions of CMake itself and VSCode. Something like < 3.7.2, latest released, latest nightly + similar for Code - latest released, latest insiders. However I'm not sure if backward compatibility is needed for VS Code (e.g. pre-multiroot).

**Comment by KoeMai** [comment]
I would like to build different levels of testing. At the moment I focus on the testing of the possible user interaction. I think on this level of tests we do not need to test many compilers and cmake versions, the should only check essential cases or issues from the users. The other test I would do it like @ytimenkov  says, more inside the extension by unit testing and integration test. The help us more on development.

**Comment by vector-of-bool** [comment]
I'm open to getting a good baseline as the first step. We can expand the test matrix at a later time.

@ytimenkov, I've looked into using the task-runner as a way to execute the CMake builds, with mixed findings. Last time I looked, it didn't support what I was hoping for. It may be better now (I looked several months ago).

I'd like to switch to the task-runner if possible, if only for using the integrated terminal for nicer output. Here's a wild possibility:

- Wrap the CMake build with a script that communicates back to the extension? I'm hesitant to use regex to do error matching since each compiler does something wildly different and sometimes errors are split over multiple lines.

> Weird generator+compiler combination like ninja + Visual Studio.

Actually, the reason I've struggled with Visual Studio generators is that I exclusively use the Ninja generator with MSVC :D

As for bringing in your changes: I'd like to phase out the current backend/two-phase init process. I just want to get our testing in order. If it would be simpler to pull in your changes while we add the tests, I'm good with that.

**Comment by KoeMai** [comment]
Ok, out of the discussion, I think we should create a new dashboard project with cards for the tasks of this issue (testing issues). This allows that different person could work on it.

I most tests could be done by mocha based test inside of one vscode instance. By reloading the cmaketools class. With this approach we could test the different cmake versions and compiler version. This approach does not support to test the binding of commands, because there is a reload of the extension needed.

For vscode version tests we need for each version a new test runner. For setting them up we could the smoke branch ctest part or by extension of the run_extensions_test.bat. But I see this more on the long term. 

- [ ] In add_build_test branch I would add additional an example how change settings inside a test. I think it will the cmake install path switch.

**Comment by KoeMai** [comment]
I think the main part of this issue is done, could we close it?

**Comment by vector-of-bool** [comment]
I say yes
