### ISSUE TITLE
${workspaceRoot} is not substituted if is used in kit "toolchainFile"

### ISSUE THREAD

**Issue by bbosnjak** [vector-of-bool/vscode-cmake-tools#329]
### Brief Issue Summary

If ${workspaceRoot} is used in cmake-kit.json:
    {
        "name": "Emscripten",
        "toolchainFile": "${workspaceRoot}/emscripten/toolchain.cmake"
    }
It will not be substituted.

- **Operating System**: Windows
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.20.1
- **CMake Tools Extension Version**:  0.11.0-beta4
- **Compiler/Toolchain**: [[Visual C++ 2018, GCC 5.3, GHS PPC, GHS V850, ARM 6.6.1, Clang 5.0.1, GCC 7.2.1 (arm)]]

**Comment by vector-of-bool** [comment]
@Randshot, do you want to look at this as part of your PR?

Since Kit processing happens so early in the initialization process, I don't think it's possible to support _all_ substitutions, but `workspaceRoot` should at least be supported.

**Comment by Randshot** [comment]
@vector-of-bool I will take a look at it.

**Comment by Randshot** [comment]
@vector-of-bool My PR #317 should already solve this issue, since I expand the final flags at the end of the `configure()` function.
https://github.com/Randshot/vscode-cmake-tools/blob/890e5e8a69a6b8471601b88728d01298d650f5b9/src/driver.ts#L599

**Comment by Randshot** [comment]
PR #317 merged.
