### ISSUE TITLE
"Select build environment" doesn't detect LLVM/Clang for Windows

### ISSUE THREAD

**Issue by xgalaxy** [vector-of-bool/vscode-cmake-tools#335]
### Brief Issue Summary

On Windows with "Clang for Windows" installed (see: http://releases.llvm.org/download.html#5.0.1).
Using CMake Tools extension in VSCode the status bar lets you select build environment.
The popup properly detects the MSVC environments but doesn't detect the "Clang for Windows" environment.

The LLVM environment path exists in the PATH environment variable.

### Expected:

If an LLVM environment is installed I expect CMake Tools to properly detect it and display it as an option for build environments.

### Apparent Behavior:

LLVM environment on Windows is not detected.

**Comment by KoeMai** [comment]
@xgalaxy could you give use the cmaketool log file. This would help us to isolate the problem.

**Comment by Randshot** [comment]
@xgalaxy Maybe also provide which CMake Tools version you are using.

**Comment by xgalaxy** [comment]
**CMake Tools version:** 0.10.4

Note: I'm seeing something different today than I was yesterday. The only thing I can think of is I restarted my computer. Today, I'm unable to use any of the environments, including MSVC when its selected as the environment (Note: LLVM still doesn't show up in the build environment selection).

Here is the log:

```
Loading CMake Tools from d:\Roamers\.vscode\.cmaketools.json
Detected available environment "Visual Studio Community 2017 - x86
Detected available environment "Visual Studio Community 2017 - amd64
Started new CMake Server instance with PID 5904
[vscode] Configuring using the "Ninja" CMake generator

[cmake-server] loading initial cache file d:\roamers\build\CMakeTools\InitializeCache.cmake

-- The C compiler identification is Clang 5.0.1
-- CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:771 (message):
  The Clang compiler tool

    "C:/Program Files/LLVM/bin/clang.exe"

  targets the MSVC ABI but has a GNU-like command-line interface.  This is
  not supported.  Use 'clang-cl' instead, e.g.  by setting 'CC=clang-cl' in
  the environment.  Furthermore, use the MSVC command-line environment.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeDetermineCCompiler.cmake:113 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)
  CMakeLists.txt:2 (project)


-- CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "d:/roamers/build/CMakeFiles/CMakeOutput.log".
[vscode] Configure failed: [cmake-server] Configuration failed
```

**Comment by xgalaxy** [comment]
A couple of notes and thoughts about that log:

1) If I'm selecting the build environment of 'MSVC - x86 or MSVC - x64' I still get that clang error - which doesn't make sense. If I'm selecting that I want to use MSVC then why is it complaining about clang?

2) Even if I don't select a build environment I get that same error.

3) In my opinion, I'd expect to see LLVM listed in the build environment dropdown and that is what would enable usage of clang.

Lastly, this may not be a CMake Tools problem, but I don't understand why I can't use clang instead of clang-cl. My understanding is that clang-cl is a command line adapter to mimick the MSVC command line and that the regular clang command works fine under Windows. And I can verify this by opening up a command line and using both clang and clang-cl.

**Comment by xgalaxy** [comment]
Here is the output of `CMakeOutput.log`

```
The system is: Windows - 10.0.16299 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files/LLVM/bin/clang.exe 
Build flags: 
Id flags:  

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"

The C compiler identification is Clang, found in "d:/roamers/build/CMakeFiles/3.10.2/CompilerIdC/a.exe"

```

**Comment by vector-of-bool** [comment]
This is a bug proper, since CMake Tools should see the clang executable on the $PATH. I have LLVM for Windows installed (version 6.0.0) and it shows up as a kit. I'm perplexed. Could you increase the log level (using settings.json) and rescan for kits? There's some heavy logging around kit scanning in debug mode.

**Comment by xgalaxy** [comment]
This is relevant I think:
https://gitlab.kitware.com/cmake/cmake/issues/16439

**Comment by vector-of-bool** [comment]
I'm somewhat confused. Does CMake Tools detect Clang as a kit? Is this just a failure when trying to configure using it?

**Comment by xgalaxy** [comment]
I've laid out all the problems in the post above. I have both LLVM installed and MSVC and I can't use either using CMake Tools.

**Comment by JacksonFurrier** [comment]
Same here with us targeting windows with clang-cl.

**Comment by vector-of-bool** [comment]
I have a hypothesis. Can you try to manually create a [compile kit](https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html#compiler-kits) using the path to `clang-cl` for `C` and `CXX`, then try configuring with that?

If my hypothesis is correct, it will be as simple as scanning for `clang-cl` separately from Clang

**Comment by vector-of-bool** [comment]
Can you also run the kit scan with debug logging and paste the result here?

**Comment by JacksonFurrier** [comment]
sure, today I will update you. Thank you for the fast answer!

**Comment by JacksonFurrier** [comment]
Manually setting the compile kit does help on the platform(Win10) that I am using at the moment. However here, I have Visual Studio Professional (2012, 2017)[vswhere is not installed] installed among with Clang 5. CMake Tools does report the installed kits correctly. Will try to provide you the debug log later with the other setup.[Win10, vswhere and vs build tools 2017 installed, Clang 6]

**Comment by JacksonFurrier** [comment]
Now trying on Windows 10 with Visual Studio Build Tools 2017 installed, with Clang 6.0.0 and in some cases it is not loading the env variables with vcvarsall.bat. Scenario is I set it correctly for a project and then opening another project with the same toolchain causes linking error for the last step which shows that it is not loading the env vars correctly for the second project. Log.txt provided :) 
[log.txt](https://github.com/vector-of-bool/vscode-cmake-tools/files/1957875/log.txt)

**Comment by JacksonFurrier** [comment]
Okay I think I have found the problem. First I TL;DR-d the kits session in the readme which was a bad idea, turned out I was naming my custom kit same as an auto-generated one. Second I have set wrong values for my custom kit. In case someone would do the same as us, I provide my custom kit for using **clang-cl** on **windows** with a **Ninja** generator.

- Our cmake-kits.json custom part is this:
 [cmake-tool.txt](https://github.com/vector-of-bool/vscode-cmake-tools/files/1957893/cmake-tool.txt)

- And our Toolchain.cmake is this to compile with clang:
 [Toolchain.txt](https://github.com/vector-of-bool/vscode-cmake-tools/files/1957894/Toolchain.txt)

Thank you @vector-of-bool for this extension, we love it!

**Comment by vector-of-bool** [comment]
It looks to me that there should be a kit that sets both the VS environment AND the compilers to clang-cl.

**Comment by vector-of-bool** [comment]
Sorry to take so long on this. I wanted to get the 1.0.0 release out almost three weeks ago, but some hardware failures prevented me from doing work on this ext. I'm hoping to finish up 1.0.0 by the end of the week.
