### ISSUE TITLE
Important Test Cases for 0.11.0

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/vscode-cmake-tools#340]
For the pending 0.11.0 release, I'd like to get test cases for most of our big tickets, as well as tests for basic functionality. I'll keep this checklist here and we can add to it and reference it for the upcoming release 

## Cases which must be tested:

- [x] `${workspaceRoot}` in toolchain kit.
- [x] Can configure a project 
- [x] Can build a project
- [x] Environment variables in variants (#248)
- [x] The Visual Studio generator matching the active VS kit should be selected if no other generator is available.
- [x] Substitutions for `buildArgs` and `buildToolArgs`
- [x] Testing for all `*Environment` setting fields
- [x] Substitutions for `configureSettings` and `configureArgs`
- [x] Substitutions using variant option names

Yeah... the list is short for now, but we'll grow it. Comment below on this that should be tested.

Tag @Randshot, @ytimenkov, @KoeMai.

**Comment by Randshot** [comment]
I plan to write tests for all my PRs:
- Variable substitution for `buildArgs` & `buildToolArgs`
- Testing for `*Environment` setting fields
- Variable substitution for `configureSettings` & `configureArgs`
- Variable substitution for variant option names

**Comment by KoeMai** [comment]
I write at the moment tests for the preferred generator. With this case I will introduce different compilers into the test environment.

**Comment by vector-of-bool** [comment]
[There's now a Gitter chat](https://gitter.im/vscode-cmake-tools/Lobby). Maybe a real badge someday.

**Comment by vector-of-bool** [comment]
@Randshot did we write a test for `${workspaceRoot}` in Toolchain kits?

**Comment by Randshot** [comment]
@vector-of-bool I don't think so, at least I didn't.

**Comment by vector-of-bool** [comment]
The case I'm referring to is a toolchain kit where the path to the toolchain file contains `${workspaceRoot}` such that the path to the toolchain file is dependent on the path to the current workspace. This helps when a project defines its own toolchain file and a user wishes to use it as a kit. This is even more relevant with changes to support workspace-local kit definitions.

The path to the toolchain file only needs to be expanded at the last moment before passing `CMAKE_TOOLCHAIN_FILE` to the CMake configure process.

**Comment by vector-of-bool** [comment]
BetWith beta5 released, what more test cases do we need to fill out?

**Comment by vector-of-bool** [comment]
## Test Case Refactoring

With the refactor of the variable expansion, I'd like to highlight some changes I'd like to see in the tests, and I think @ytimenkov will echo some of these sentiments.

The current expansion tests, in which an entire configure/build/etc process is run to check for expansions, is incredibly slow and fragile.

A note going into this: *The primary purpose* of the expansion tests is to ensure that all guaranteed expansion variables (eg. `workspaceRoot`, `buildType`) are expanded in all the proper contexts.

The goal of my expansion refactors was to encode the invariants of the expansion process _into the type system_. In order to perform a variable expansion on any given string, you **must** supply the values that we guarantee for expansion, or it becomes a compile error. In this way, we don't even need to test that we've provided all the values for any given context since the TS compiler will ensure that guarantee for us.

By this change, we can simplify the expansion tests into two separate tests that will both run faster, and be less fragile:

1. Check that calling `expandString` with a given set of values on a pre-defined template string will expand to the expected string. No need to perform a full project configure to ensure that expansion actually occurs. No need to even have a project at all.
2. Check that the `expansionOptions` property on a CMake driver instance contains the expected values for a given project. This includes checking the values for `RequiredExpansionContextVars`, which encodes the expansion variables that we guarantee to users in the documentation. We again don't require that we perform a project configure to do this test. All we need to do is open a project directory.

With these two test situations defined, I'd like to re-iterate my skepticism of mocking: It's a heavy hammer that indicates a bad architecture. We shouldn't _need_ to run a full configure to check that expansions work. There's one more thing that is needed to ensure correctness:

*The business-logic code performing expansions should be so simple that its correctness is so obvious as to not warrant testing*.

For example, this code snippet:

```typescript
const opts = this.expansionOptions;
const expanded_flags_promises = final_flags.map(
    (value: string) => expand.expandString(value, {...opts, envOverride: expanded_configure_env}));
```

is so simple as to be obviously correct by observation. It actually encodes quite a complex operation, but we have four things going for it:

1. We are guaranteed by the type system that `opts` contains _all_ the values we guarantee to users to be expanded.
2. At this point in the code, we must make the assumption that `this.expansionOptions` returns the correct value. We have separate tests to check this.
3. At this point in the code, we must make the assumption that `expand.expandString` is correct. Again, we have separate tests to check this.
4. JavaScript's `Array.map` has behavior guaranteed by the standard. We can assume it to be correct without testing.

Despite the complexity of the behavior observed in the two TS statements, we can hold these four facts in our head and reason that the code is correct by the guarantees afforded by the type system and guarantees of the APIs which we call.

The _only_ potential problem I can see in the above code is that `expandString` resolves asynchronously, and `${command:foo}` expansion might produce a race condition. Even then, this is a bug in the command being called, not of the lines themselves. A potential workaround would be to serialize the expansions, but this would be a workaround to someone else's bug, not a fix for a bug in the code itself.

With this new design, guaranteeing a new expansion variable to users requires adding a new variable to `RequiredExpansionContextVars`, and this will only necessitate a fix on any callers of `expandString`, as well as a test that `driver.expansionOptions` returns a correct value for the new expansion variable. Running a barrage of tests against the entire configure/build stack is unnecessary since the underlying `driver.expansionOptions` is guaranteed to be correct.

Of course, these full-stack tests are still useful. It simply shouldn't be standard practice to test the entire universe when we want to bake a new flavor of pie.

## What Am I Rambling About?

As with string variable expansion, I'd like to see other aspects of the code refactored in a similar manner. For example:

- Testing the parsing of CTest XML should be possible without configuring a CTest project.
- Testing parsing of CMake caches shouldn't require running a configure (The CMake cache tests are already in this state, thankfully)
- Kit scanning shouldn't require an extension instance running. We're almost there on this front.
- We should be able to spin up and talk to a CMake server instance without starting an entire new VSCode and CMake Tools extension instance. This may also lead to parallelization of the tests since CMake server is a lot of blocking IO.
- Parsing diagnostics of CMake and compiler errors shouldn't require actually _running_ either of these tools.

These are the kinds of testing refactors I hope to do in the 0.11.0 and following 1.0 release. Time pressure for the first 0.11.0 beta led me to rush and not consider these things properly, which is why the beta5 took quite a bit of work to get testing in a reasonable -- if flawed -- state.

**Comment by Randshot** [comment]
So in short you are saying, that we need to make the different parts of the extension independent of each other, so that testing them doesn't require a full blown CMT instance.

**Comment by vector-of-bool** [comment]
Yes, that's what I'm saying in a very round-about and overly wordy way. I guess I just wanted to rant for a bit, even if just to an audience of three who already agree with me. :stuck_out_tongue:
