### ISSUE TITLE
Its own cmake.buildDirectory for each build type

### ISSUE THREAD

**Issue by sergii-zaiets** [vector-of-bool/vscode-cmake-tools#343]
Hi everyone,

If I understand correctly, currently there can be only one build folder for each build type, like Release, Debug. 
**Is there a way to build in different folders, for example, Release in ${workspaceRoot}/build.release and Debug in ${workspaceRoot}/build.debug?**
I simply don't want to rebuild every time I switch build type. 
I hope my question is clear.

Regards, 
Sergii Zaiets

**Comment by Randshot** [comment]
Hey,
You should be able to use `${buildType}` when defining the build directory.

**Comment by sergii-zaiets** [comment]
Super. Great. It works :)
