### ISSUE TITLE
Environment variables don't get applied after the cmake-server got started

### ISSUE THREAD

**Issue by Randshot** [vector-of-bool/vscode-cmake-tools#346]
## Brief Issue Summary
Because of the way the (configure) environment variables get applied for the cmake-server, they don't get applied if the user changes them in the `settings.json` __*after*__ the extension started the cmake-server.
The user can fix this by restarting the cmake-server (e.g. by restarting vscode), but I don't think that the user should have to worry about that.

@vector-of-bool has suggested that we use vscode hooks to watch for any relevant changes to the project-specific and user-specific settings file. In that case, we would have to watch for any changes to the following option fields:
- `cmake.environment`
- `cmake.configureEnvironment`

I quite like the approach @vector-of-bool suggested, so I will also suggest that we do it that way.
If you have any other suggestions or I have missed something, then feel free to comment them below.

Tag @KoeMai, @ytimenkov, @vector-of-bool.

**Comment by vector-of-bool** [comment]
Marking done in the project since the PR was merged.
