### ISSUE TITLE
0.11.0-beta4: Compiler Kit selection UI bug

### ISSUE THREAD

**Issue by isushik94** [vector-of-bool/vscode-cmake-tools#348]
Hi.

I've installed 0.11.0-beta4. And after finding available Kits I've opened a Kits list to chose one of them and the list has looked like this:
![screenshot from 2018-03-19 14-38-55](https://user-images.githubusercontent.com/18529374/37593644-c07b5454-2b83-11e8-9c19-0a56344d6039.png)

I'm on Archlinux x86_64 with a fresh kernel. And I use Gnome desktop.

**Comment by Randshot** [comment]
@isushik94 I have also encountered the same graphic glitch on my Windows system after I added my Cygwin installation to the PATH. It seems like this is related to either GCC or Clang.
I will have to look into this further to confirm or deny this.

**Comment by vector-of-bool** [comment]
I've seen this and broken a debugger right before we call `showQuickPick`. It looks like the `label` property is set correctly. I see this on Linux as well. It started after vscode update either this month or last month. Note that this only happens with CompilerKits. VS kits work fine.

Did the QuickPick API change?

**Comment by isushik94** [comment]
> Did the QuickPick API change?

Sadly, but I don't know how VS Code works. I use 1.21.1 version.

**Comment by vector-of-bool** [comment]
The description text on CompileKits has newlines in it which have never rendered properly. I wouldn't be surprised if those newlines are somehow to blame here.

**Comment by vector-of-bool** [comment]
Confirmed, it is the newlines. Will release a fix soon.
