### ISSUE TITLE
0.11.0-beta4: Configuration from settings.conf isn't applied

### ISSUE THREAD

**Issue by isushik94** [vector-of-bool/vscode-cmake-tools#349]
Hi
After some work I've found that a cmake-tools configuration from settings.conf isn't applied. For instance, "cmake.installPrefix" doesn't change CMAKE_INSTALL_PREFIX and "cmake.configureArgs" doesn't pass specified arguments to cmake.
And the last bug is that `Edit Cmake Cache` command doesn't work. It prints: "There are no cache entries to show. Have you configured the project?". But I can build the project, run "Configure" command.

**Comment by Randshot** [comment]
@isushik94 This was already fixed in PR #317, but it's not in the beta4 release.
Either wait for the next beta release, or build the vsix package for yourself from the current `refactor-1.0` branch.

**Comment by vector-of-bool** [comment]
@isushik94, can you open another issue for the Edit CMake Cache bug?

Vscode will soon have a webview API that I hope to utilize for a more stable cache editor.

**Comment by isushik94** [comment]
@vector-of-bool, yes I can.

**Comment by isushik94** [comment]
@Randshot, is there any guide how to build the vsix package from sources?

**Comment by vector-of-bool** [comment]
@isushik94, sorry for the delay. There's unfortunately no docs on building the .vsix, but it should be pretty easy:

1. Clone the repo.
2. Run `npm install`.
3. Get `vsce`, which is the VSCode extension packaging tool.
4. Run `vsce package`

**Comment by vector-of-bool** [comment]
@isushik94, the fix should be in beta5. I'll close this, but feel free to re-open if it isn't fixed to your satisfaction.
