### ISSUE TITLE
"Stop" button does not work on Windows

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/vscode-cmake-tools#35]
Seems to be relating to the way that CMake generates processes on Windows?

**Comment by MinnieTheMoocher** [comment]
Yes and no.
Of course, cmake itself is responsible for killing all its child processes it spawns.
You should only be responsible for properly killing cmake.
However, there is a trick you can do on Windows to make sure that
cmake AND all its children die when you kill it:

http://stackoverflow.com/questions/3342941/kill-child-process-when-parent-process-is-killed

**Comment by bbosnjak** [comment]
To stop process on windows you have to use "taskkill". 
See: http://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows

**Comment by vector-of-bool** [comment]
Thanks @bbosnjak! This will be fixed in the next release.

**Comment by ykchong45** [comment]
Sorry to ask, but I don't see a stop button when configuring my project. How can I stop in the middle of configuration process?
I'm using CMake tool v1.9.1

**Comment by bobbrow** [comment]
There currently is no stop button for configuration, only for build.  You can open a feature request issue if you would like us to consider adding it.
