### ISSUE TITLE
CMakeTools extension was unable to initialize

### ISSUE THREAD

**Issue by loaden** [vector-of-bool/vscode-cmake-tools#358]
hi, I've got this error message and can not do anything. I can't select kit or next step. etc.
I thought maybe need feedback here.

ERROR MESSAGE:
CMakeTools extension was unable to initialize: TypeError: Reduce of empty array with no initial value [See output window for more details]

VSCode Version: 1.21.1
CMake Tools Version: 0.10.4

**Comment by vector-of-bool** [comment]
Have you tried running the latest beta release? You can get it from [here](https://github.com/vector-of-bool/vscode-cmake-tools/releases/tag/0.11.0-beta4).

**Comment by loaden** [comment]
big thanks, it's great after try the beta release. but still another problem, does this extension rescanning the kits when it invalid, I mean, maybe moved the Kit to other place, e.g. from C:/MinGW to D:/MinGW64.
In current beta version, it's still use the invalid kit, and can't update or rescan something.
I've tried delete the 'build' folder, but still have problem.

Error Message:
[cmake] The C compiler identification is unknown
[cmake] The CXX compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:4 (project):
[cmake]   The CMAKE_C_COMPILER:
[cmake] 
[cmake]     D:/qpSOFT/VSCode/VSCode_64-bit/MinGW/bin/gcc.exe
[cmake] 
[cmake]   is not a full path to an existing compiler tool.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
[cmake]   the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:4 (project):
[cmake]   The CMAKE_CXX_COMPILER:
[cmake] 
[cmake]     D:/qpSOFT/VSCode/VSCode_64-bit/MinGW/bin/g++.exe
[cmake] 
[cmake]   is not a full path to an existing compiler tool.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "d:/qpsoft/projects/test/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "d:/qpsoft/projects/test/build/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.

**Comment by vector-of-bool** [comment]
You can can run `CMake: Scan for kits` from the command palette, or `CMake: Edit CMake Kits` to manually fix the kits file.

**Comment by loaden** [comment]
thanks! it's works.

**Comment by Brannua** [comment]
helped me either, thanks a lot.
