### ISSUE TITLE
add_custom_target no more recognized

### ISSUE THREAD

**Issue by barsan-ds** [vector-of-bool/vscode-cmake-tools#359]
It seems that the command [add_custom_target](https://cmake.org/cmake/help/latest/command/add_custom_target.html) is not supported anymore. I mean it does no more appear in target and is not selectable to be built. Is this a regression? A deleted/unwanted feature?

**Comment by vector-of-bool** [comment]
Are you using the beta release?

Custom targets _should_ be listed. What version of CMake are you using?

**Comment by barsan-ds** [comment]
I'm using CMake 3.11.0-rc2. After some research, I found issue [#196](https://github.com/vector-of-bool/vscode-cmake-tools/issues/196), which may be related

**Comment by vector-of-bool** [comment]
What version of the CMake Tools extension do you have installed? Did you install the extension beta?

**Comment by barsan-ds** [comment]
I confirm it works with the beta of 0.11. Sorry I didn't expected that this was already solved.
Also nice add the selection of the compiler from VS Code, without having to manually set cc and c++ manually. Thank you!

**Comment by Randshot** [comment]
@barsan-ds I take that this issue can be closed now. If you have any more questions, fell free to reopen this issue or open a new one.

Closed.

**Comment by HorstBaerbel** [comment]
Should custom targets be available as "target to launch"? I have a custom target here that I don't see there. The target does not use add_executable, but only add_custom_target...
