### ISSUE TITLE
Can not launch the debugger for the selected target

### ISSUE THREAD

**Issue by loaden** [vector-of-bool/vscode-cmake-tools#360]
hi, I've installed 0.11 beta4, it's works fine except launch the debugger for the selected target. there show me a tooltip info box saying 'No target selected for debugging'.

> I can select the Kits and can switch the one of the build types.
> [build] Starting build
> [proc] Executing command: cmake --build d:/qpsoft/projects/test/build --config Release --target Test -- -j 6
> [build] [1/2] Building CXX object CMakeFiles/Test.dir/test.cpp.obj
> [build] [2/2] Linking CXX executable Test.exe
> [build] Build finished with exit code 0

so, how can i make the debug working? thanks.

**Comment by loaden** [comment]
In the first, I have to execute "CMake: Select a target to Debug".
I hope it can show 'all' in the right side of the "Debug" button.  like the "Build" button behavior.
so user can click the 'all' to select a target for Debug.

In the second, I have to set debug path in the user settings.json, at least one line like this.
```
{
    "cmake.debugConfig": {
        "miDebuggerPath": "gdb.exe"
    }
}
```
maybe there can get better way. e.g. auto config something.

**Comment by Randshot** [comment]
@loaden To debug, you obviously have to have a target and 'all' is not a valid target.
