### ISSUE TITLE
Improveing debug: excute the "CMake: Select a Target to Debug" when click the 'bug button' in the first time 

### ISSUE THREAD

**Issue by loaden** [vector-of-bool/vscode-cmake-tools#361]
This just a suggestion.
It's bother me a long time when I know I have to select a target to debug before start debugging.
In the status bar, there exist a button with a 'bug' picture, when I click, it warning me 'No target selected for debugging'. if in this moment it popup the target select list, how about that?
I'd say when click the 'bug' button and show me the target list, I will start quickly.
like a guide.

**Comment by vector-of-bool** [comment]
This started to happen when I did the 0.11.0 refactor. Beta5 should bring this behavior back. I'll keep this open and ping back when I push out the beta5 (Hopefully very soon)

**Comment by vector-of-bool** [comment]
Give this a try in the new beta5. I've verified a fix on my side, but you can re-open this if it's not working properly.

**Comment by loaden** [comment]
It's working great! thanks!
