### ISSUE TITLE
The `${workspaceFolder}` variable does not work in workspace local cmake-kits file

### ISSUE THREAD

**Issue by bjosa** [vector-of-bool/vscode-cmake-tools#367]
### Brief Issue Summary

Just testet the 0.11.0-beta5 release and tried to define a cmake-kits.json file in the workspace folder
The `${workspaceFolder}` variable will not be expanded in a workspace local cmake-kits file.

.vscode/cmake-kits.json

```json
[{
  "name": "Example",
  "toolchainFile": "${workspaceFolder}/toolchain-file.cmake"
}]
```

### Expected:

The variable `${workspaceFolder}` should be expanded to the vscode workspace folder.

### CMake Tools Log

```
[cms-client] Configuring using the "Ninja" CMake generator
[expand] Invalid variable reference ${workspaceFolder} in string: -DCMAKE_TOOLCHAIN_FILE=${workspaceFolder}/toolchain-file.cmake
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
[cmake]   Could not find toolchain file: ${workspaceFolder}/toolchain-file.cmake
```

### Platform and Versions

- **Operating System**: Windows 10
- **VSCode Version**:  1.21.1
- **CMake Tools Extension Version**: 0.11.0-beta5
- **Compiler/Toolchain**: CMake toolchain file based crosscompiler, gcc

### Other Notes/Information

Thank you for this awesome tool !

**Comment by Randshot** [comment]
@bjosa You need to use `${workspaceRoot}` to get the root folder of your current workspace.

**Comment by bjosa** [comment]
Thanks for the instant reply.
Yes i can confirm that `${workspaceRoot}` works.

I would expect the new variable `${workspaceFolder}` to also work. Even if Multi Workspace support is not yet given. The `${workpaceFolder}` should in this case return the root of the current workspace.

As stated at the [vscode homepage](https://code.visualstudio.com/docs/editor/variables-reference) the `${workspaceRoot}` variable is deprecated in favour of the `${workspaceFolder}` variable.

**Comment by Randshot** [comment]
Merged.
