### ISSUE TITLE
Target Debugging

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/vscode-cmake-tools#37]
This issue is used to collect feedback on the experimental [_Target Debugging_](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md) feature.

If you have tried out target debugging and find that it works and is useful for your project, add a 👍 reaction to let me know.

Any feedback would be highly appreciated.

Learn more about this feature in [these docs for Target Debugging](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md).

**Comment by magpier84** [comment]
This line makes it possible to make tools working:

include(${CMAKE_BINARY_DIR}/CMakeTools/CMakeToolsHelpers.cmake)

**Comment by magpier84** [comment]
Launching of application is working but launch.json provide possibility to pass environment variables but CMakeTools are not.

**Comment by vector-of-bool** [comment]
CMake Tools sets up the module path such that you only need to

~~~cmake
include(CMakeToolsHelpers OPTIONAL)
~~~

and it will be fine. No need to specify the full path to the file. Actually: please _do not_ specify the full path, because it may be moved in the future. See [the docs](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md) on how to configure the debugger, which should let you specify environment variables, program arguments, etc.

Thanks for trying it out! Any feedback is welcome!

**Comment by magpier84** [comment]
>include(CMakeToolsHelpers OPTIONAL)

It doesn't work for me (OSX cmake version 3.6.1).

**Comment by magpier84** [comment]
> CMake Tools generates a debugging configuration object on-the-fly, when debugging is requested. To set some additional parameters to this debug configuration, use the cmake.debugConfig

How environment variables should be passed to cmake.debugConfig?
Thanks!

**Comment by vector-of-bool** [comment]
Hmm... do you ``set(CMAKE_MODULE_PATH ...)`` at any point in your ``CMakeLists.txt``? Does it fail with any error/warning messages?

For configuring, set the same values in the ``all`` section of the ``cmake.debugConfig`` that you would in a ``launch.json`` file. For example:

~~~json
"cmake.debugConfig": {
    "all": {
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "environment": [{
            "foo": "bar"
        }],
        "linux": {
            "MIMode": "gdb"
        },
        "osx": {
            "MIMode": "lldb"
        },
        "windows": {
            "MIMode": "gdb"
        }
    }
}
~~~

I'll update the docs to talk more about this.

**Comment by magpier84** [comment]
Yep, I have set CMAKE_MODULE_PATH var before.
It's clear now how to set environment variables now.
Thanks!

**Comment by vector-of-bool** [comment]
Ah, ok. Instead of using ``set`` to add things to ``CMAKE_MODULE_PATH``, use this:

~~~cmake
list(APPEND CMAKE_MODULE_PATH "SomeDirectoryHere")
~~~

Replacing ``SomeDirectoryHere`` with what you want to add to the path.

I'll add a note to the docs about this.

**Comment by magpier84** [comment]
I have successfully launched app! Thanks!
Is it possible to associate keys for launching debugger?

**Comment by vector-of-bool** [comment]
Yes, just add a keybinding for the ``cmake.debugTarget`` command

**Comment by nsubtil** [comment]
For some reason, whenever I add the `include(CMakeToolsHelpers OPTIONAL)`, I will often see errors from CMake when generating build files through vscode:

```CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times for different configurations
  or languages with different content:

    <full path omitted>/build/CMakeToolsMeta.txt```

The error tends to repeat a dozen or so times in the output. Running the build again works fine and I can pick debug targets and debug with impunity, so it's not clear what exactly is wrong here. This happens on a couple of different trees, so it doesn't sound like something specific to one particular build.

FWIW, I'm running CMake 3.6.1 on Windows, target compiler is MSVC 19 (VS 2015), using the Visual Studio 2015 generator.

**Comment by vector-of-bool** [comment]
@nsubtil, I know what causes that. It's because the Visual Studio generators are multi-config generators. I didn't think about the interaction here. Thanks for the heads up, I'll put in a fix!

**Comment by Franky47** [comment]
It works for me, on OS X 10.9.5 / VSCode 1.5.3 / CMake 2.8.3 / CMake Tools 0.6.0

Thanks for this, it's very handy ! Somehow the native `launch.json`method did not work initially, but this worked like a charm.

**Comment by photex** [comment]
Including CMakeToolsHelper breaks my Qt5 applications build.

In order to access a specific Qt build I have a cache entry "QT_ROOT" this is set as the CMAKE_PREFIX_PATH.

Once I use `include(CMakeToolsHelpers OPTIONAL)` I get the following error during configuration:

```
-- Configuring done
CMake Error at build/CMakeTools/CMakeToolsHelpers.cmake:59 (file):
  Error evaluating generator expression:

    $<TARGET_FILE:Qt5::qmake>

  No target "Qt5::qmake"
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)
```

**Comment by vector-of-bool** [comment]
@photex Thanks for the notice. I have a good idea of how to fix that.

**Comment by photex** [comment]
Indeed, just taking a quick peek at the module, it seems to be missing the imported check for executables right?

**Comment by vector-of-bool** [comment]
That's correct. I've noticed it doing this before, but it's never actually caused an error... I'll have to add the check to make sure this error doesn't happen. Usually people aren't interested in debugging an imported executable.

**Comment by Thecontrarian** [comment]
This works great!

**Comment by Thecontrarian** [comment]
it was working but something happened and now there arent any any available targets for debugging. ive tried everything.

**Comment by vector-of-bool** [comment]
That's no good. Can you find a `CMakeToolsMeta.txt` file? What is inside it? What have you tried?

**Comment by Thecontrarian** [comment]
i found a `CMakeToolsMeta.in.txt` with
```interface-library;Boost::diagnostic_definitions
system;Darwin;x86_64;Clang
interface-library;Boost::disable_autolinking
interface-library;Boost::dynamic_linking
interface-library;Boost::boost
executable;rosebud;$<TARGET_FILE:rosebud>
```

ive tried reconfiguring the project, messing around with the order of the cmakelists file, uninstalling and reinstalling cmaketools, completely uninstalling all of my extensions and clearing whatever caches i could find. nothing.

**Comment by Thecontrarian** [comment]
i just changed the `CMakeToolsMeta.in.txt` file to `CMakeToolsMeta.txt` and now my target shows up. but `CMakeToolsMeta.in.txt` was autogenerated so i dont know why its called that

**Comment by vector-of-bool** [comment]
Just looked at the code, and it seems this is a bug relating to the project configuration. I'm guessing you are building in `Release` mode, or some other non-`Debug` mode. Is that correct? A bug is causing it to only generate the metadata in `Debug` mode. I'll do a release soon with a few bugfixes and tweaks.

**Comment by Thecontrarian** [comment]
no ive only been building in debug and release with deb info mode

**Comment by vector-of-bool** [comment]
Hmm... Could you open a separate issue for this? I don't want to keep spamming all past participants of this thread. Could you include details about you CMake version, CMake generator, workflow, platform, etc.?

**Comment by Thecontrarian** [comment]
sure thing https://github.com/vector-of-bool/vscode-cmake-tools/issues/67

**Comment by magpier84** [comment]
Hi! Last update broke environment variables: system ($HOME) and user-defined.

**Comment by vector-of-bool** [comment]
@magpier84, could you open a new issue and put in some more details? I'm going to close this ticket and start tracking target debugging features in individual issues. Thanks!
