### ISSUE TITLE
If "cmake.cmakePath" is set wrong, cmake-tools fails with unhandled exception

### ISSUE THREAD

**Issue by s-martin** [vector-of-bool/vscode-cmake-tools#371]
### Brief Issue Summary

I had from another platform set the `cmake.cmakePath` to `cmake3`, which didn't exist on my current plattform.

### Expected:

I would expect that cmake-tools would return some meaningful error, e.g. "No cmake file in cmake.cmakePath found".

### Apparent Behavior:

cmake-tools threw an unhandled exception:
```
console.ts:136 [Extension Host] Error: spawn cmake3 ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:400
(anonymous) @ extensionHost.ts:213
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

### Platform and Versions

- **Operating System**: Windows 7
- **CMake Version**: 3.9.4
- **VSCode Version**: 1.21.1
- **CMake Tools Extension Version**: 0.11-beta5
- **Compiler/Toolchain**: Visual C++ 2017 x86

**Comment by Randshot** [comment]
@s-martin CMT doesn't check whether a file exists before trying to execute it, so that is why an exception is thrown in your case. It's trivial to add a check, but I don't know what @vector-of-bool s opinion is on this topic.

**Comment by KoeMai** [comment]
Should be fixed in next version.
