### ISSUE TITLE
0.11.0 beta 5 - automatic kit generation for cross-gcc

### ISSUE THREAD

**Issue by stephenwhittle** [vector-of-bool/vscode-cmake-tools#373]
Haven't had much chance to do full-on testing yet, but it'd be great if the automatic kit generation supported cross-gcc builds.
I run vscode inside my msys2 installation so it picks up the custom PATHs from that environment - and it detects my mingw native GCC without issues, because it's aliased to gcc/G++.
However I also have arm-none-eabi-gcc and avr-gcc installed - it'd be lovely to pick these up also. 
(I'm expecting the extension to work with my toolchain file, though I haven't tested yet, but it'd be great to not need it).

**Comment by stephenwhittle** [comment]
Thanks for the reply. 
I don't really have to use a toolchain file - I can just put 

> SET(CMAKE_SYSTEM_NAME Generic)
> SET(CMAKE_SYSTEM_VERSION 1)
> set (CMAKE_C_COMPILER arm-none-eabi-gcc)
> set (CMAKE_CXX_COMPILER arm-none-eabi-g++)
> set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

into my main cmakelists.txt and all works well (the last line in particular is the workaround for the issue that you mention about trying to run an executable to verify the compiler tests). 

Will I still be able to use something like this approach once kits go into the stable build? Or do kits override such settings?

**Comment by KoeMai** [comment]
It should work with the next release
