### ISSUE TITLE
CMake: Debug Target does not find GDB

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#375]
### Brief Issue Summary

I try to use the extension in different projects. At the moment the debugging does not work out of the box. If I use the GCC then I get the following message, see figure below. I am not sure if there is a relation between debugger and kit needed. Is there some manual configuration needed? Or should it work out of the box?

### Expected:

1. Debugger should start out of the box (for quick start projects)
2. Possibility to place a debug configuration name to Kit or Variant, so that it switch automatic debug target dependent parts for different kits/variants on start of debugging.
3. May be a automatic generation of debug configuration of Kits, so that it use the debugger which is needed by the compiler (GCC, visual studio, cross compiler GCC will not work there are more information needed)

### Apparent Behavior:

1. Select MinGw GCC as kit
2. Create new executable project with quick start 
3. Build
4. Run debugger
![unabletoconfiguredebugger](https://user-images.githubusercontent.com/21360085/38452200-a68143cc-3a3f-11e8-8657-f738256b6fb5.png)

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.10.0
- **VSCode Version**: 1.21.1
- **CMake Tools Extension Version**: 0.11-beta5
- **Compiler/Toolchain**: mingw-w64/msys2 + gcc 6.3

**Comment by KoeMai** [comment]
I see the missing part. But I am not sure how we want to find gdb.
Below you can see my modification. It works but the kit contains at the moment no debugger path. 
This makes it necessary to convert the compiler path to it. 
  ```
...
  const debug_config: vscode.DebugConfiguration = {
    type: is_msvc ? 'cppvsdbg' : 'cppdbg',
    name: `Debug ${target_path}`,
    request: 'launch',
    cwd: '${workspaceRoot}',
    args: [],
    MIMode: mi_mode,
  };
  if (mi_mode == 'gdb') {
      if(this._kitManager.activeKit!.type == "compilerKit") {
        const kit: CompilerKit = this._kitManager.activeKit as CompilerKit;
        const compilers: {[lang: string]: string} = kit.compilers;
        // \todo error handling for missing "C" compiler
        const gdb = compilers["C"].replace("gcc", "gdb");
        // \todo find gdb path is a user transparent way
        debug_config["miDebuggerPath"] = gdb;
      } else {
        // \todo error handling and handling for toolchain files
      }
...
```

**Comment by KoeMai** [comment]
Yes that is abetter search place, we can read the compiler back from CMake cache (C-Compiler) and search for a gdb with the same prefix.  But we should add the possibility to override the automatic generation by a way to set a configuration name from launch.json. What do you think about?

**Comment by vector-of-bool** [comment]
I've been trying thinking about the debugging for a while. launch.json can be used perfectly well with CMakeTools, so I don't think it necessary to read back launch.json when doing quick debugging. I'd say doing automatic gdb discovery would be just fine for quick debugging.

**Comment by KoeMai** [comment]
I would not read back Lauch.json I would only allow to configuration are configname in the settings to quicklaunch debuging with the button.

**Comment by KoeMai** [comment]
done
