### ISSUE TITLE
Kits environmentVariables not respected

### ISSUE THREAD

**Issue by RichiCoder1** [vector-of-bool/vscode-cmake-tools#380]
### Brief Issue Summary

I'm attempted to set the `PATH` in cmake-kits.json, but it looks that while environmentVariables is in the scheme, it's not actually used in cmake-tools

### Expected:

Setting `environmentVariables` in `cmake-kits.json` would result in the appropriate env var getting set during cmake operations.

### Apparent Behavior:

The setting `environmentVariables` is ignored.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.10.2
- **VSCode Version**:  1.22
- **CMake Tools Extension Version**: 0.11.0-beta5
- **Compiler/Toolchain**: GCC 7.3.0/MSYS2 MinGW 64

**Comment by vector-of-bool** [comment]
Should be available in 0.11.0 proper
