### ISSUE TITLE
Does not recognize MSYS Makefiles

### ISSUE THREAD

**Issue by tapir** [vector-of-bool/vscode-cmake-tools#39]
I have msys2 installed on Windows 7 64-bit.
I have the mingw-w64-x86_64-cmake package installed.
I have this in my user settings:
```json
    "cmake.cmakePath": "C:\\msys64\\mingw64\\bin\\cmake.exe",
    "cmake.preferredGenerators": [
        "MSYS Makefiles",
        "MinGW Makefiles",
        "Unix Makefiles",
        "NMake Makefiles",
        "Ninja",
    ],
```
And when I try to build a project I get this:
```Unknown CMake generator "MSYS Makefiles"```

`cmake -G` shows that *MSYS Makefiles* is an option. And it works when invoked from MSYS or Windows terminal.

**Comment by MinnieTheMoocher** [comment]
this is the reason why I suggest that the VSCode cmake plugin should not parse
the generator strings: #33

**Comment by tapir** [comment]
In this case MSYS Makefiles is a legit generator. So it's unrelated to that issue but I see your point and I agree.

**Comment by vector-of-bool** [comment]
@MinnieTheMoocher, you're right. I'll poke around with some alternative approaches to see how to best set the generator.

@tapir, you can work around this by configuring your project once from the command line, then CMake Tools will continue to use the MSYS Generator as long as the build directory is kept around.

**Comment by vector-of-bool** [comment]
As of the 0.5.4 release, you can force CMake Tools to use a generator with the ``cmake.generator`` setting, so I believe this issue is fixed. @tapir, if it is fixed to your liking, please close the issue. Thanks!

**Comment by vector-of-bool** [comment]
I'll close this issue for lack of activity.

**Comment by tapir** [comment]
Sorry I couldn't test it yet. From what I see it creates a new problem as I
explained on my previous post. I can't make my project settings
cross-platform. If I want my app to compile on linux, mingw and mac now I
have to have 3 different workspaces If I'm not mistaken. A very simple
solutuon is to have 3 setting properties like
cmake.generator.win32/linux/macos so that we can have single settings.json
that will work on all platforms

**Comment by vector-of-bool** [comment]
Hmm... That is a problem.

I'll reopen and think about the best solution.

**Comment by tapir** [comment]
My solution comes from the integrated terminal addon. MS uses it like that
as well to specify platform specific shell.

**Comment by vector-of-bool** [comment]
Done! Should be ready in 0.5.5.

**Comment by tapir** [comment]
Thanks much appreciated!
