### ISSUE TITLE
scanForKits not detecting gcc in path when it starts with target triple

### ISSUE THREAD

**Issue by schultetwin1** [vector-of-bool/vscode-cmake-tools#402]
### Brief Issue Summary

scanForKits only looks for binaries which start with gcc. Certain versions of gcc (especially in the embedded world) ship with the target triple at the beginning of the binary name. For example arm-none-eabi-gcc.

### Expected:

scanForKits should find arm-none-eabi-gcc if its in my path.

**Comment by vector-of-bool** [comment]
This may be the same as #373. The scan regex can be tweaked to support this pretty easily.
