### ISSUE TITLE
Allow use of system defualt with no kit selected

### ISSUE THREAD

**Issue by reporter123** [vector-of-bool/vscode-cmake-tools#406]
I have been using this extension for a long time and appreciate the convince. Unfortunately the last update began enforcing the use of kits rather than allowing the compiler to found automatically per system default. I am requesting that auto detection by cmake be restored as option. Until this is done I wont be using this extension. The use of hard coded paths which must be updated when the system configuration changes does not suite my needs.

**Comment by vector-of-bool** [comment]
Automatic compiler detection was/is extremely tricky and caused a lot of problems. Having a "None" kit is possible, but not a preferred solution.

If Kits aren't working for you, what can be done to make them easier to use and manage?

**Comment by reporter123** [comment]
I think you're missing the point here. Can kits be improved? Yes but that's
not really what I'm looking for. Cmake has the ability to automatically
dectect the compiler for most configurations. Kits should fill the gap
where this needs to be overridden. Instead your blocking functionality that
would otherwise be available. I shouldn't havr think about the compiler for
every new project any more than I do with cmake itself.

**Comment by vector-of-bool** [comment]
I have a few kit-related changes slated for 1.0.0. I'll add another implicit Kit that falls through to the default CMake behavior.

**Comment by reporter123** [comment]
thanks.
