### ISSUE TITLE
Feature Request: Option to copy compile_commands.json to static path

### ISSUE THREAD

**Issue by DWagenk** [vector-of-bool/vscode-cmake-tools#407]
### Brief Summary

Hello! It would be great, to have an additional entry in `settings.json`, to define a static path where the current `compile_commands.json` should be copied/symlinked to. 

### Expected

The current `compile_commands.json` file is always accessible via a static path.

### Background

I'm using a per-configuration build directory like proposed here: https://github.com/vector-of-bool/vscode-cmake-tools/issues/195#issuecomment-311292876 
This leads to multiple `compile_commands.json` files. Since vscode-cmake-tools knows the active configuration it knows the currently valid `compile_commands.json` file. Other extensions, e.g. ms-vscode.cpptools or cquery-project.cquery don't and rely on a static path to the valid file. Having vscode-cmake-tools copy or symlink the currently valid file to a configurable location, for other extensions to pick it up, would be great.

Please consider adding this functionality! Thanks!

**Comment by vector-of-bool** [comment]
Useful, and easy enough to make it in 1.0.0

**Comment by vector-of-bool** [comment]
Ready in 1.0.1
