### ISSUE TITLE
Use case undocumented: "Toolchain is already configured through CMakeLists.txt"

### ISSUE THREAD

**Issue by DWagenk** [vector-of-bool/vscode-cmake-tools#408]
### Brief Issue Summary

I'm working on/with a cmake-based project ([zephyr](https://github.com/zephyrproject-rtos/zephyr/)), that takes care of the (cross-compilation-)toolchain configuration via files included by my apps CMakeLists.txt. Since I don't want to double those settings in vscode-cmake-tools I played around with various settings in `cmake-kits.json`. My desired behaviour can be achieved by creating an entry like this:
```json
  {
    "name": "Zephyr",
    "toolchainFile": ""
  }
```
It feels like a workaround, so documenting it or adding an bool option `toolchianConfiguredByCMakeLists` would be highly appreciated!

**Comment by vector-of-bool** [comment]
Subtle, but probably useful.

**Comment by DWagenk** [comment]
thanks
