### ISSUE TITLE
Option to build when using `cmake.launchTargetPath`

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/vscode-cmake-tools#410]
Early version supported building the target when started from `launch.json`. This can still be done by running a build when the binary is requested via `cmake.launchTargetPath`.

**Comment by vector-of-bool** [comment]
There's no way (AFAIK) to know the debug config you have just been launch with. The ext does not know why or who called `cmake.launchTargetPath`. You _could_ read the `launch.json` yourself, but there might be multiple launch configs in the file, and I'm not sure what the debug adapters would do if we added our own option into their debug configuration objects.

**Comment by KoeMai** [comment]
The only solution would be to provide two commands `launchTargetPath` and `launchTargetPathWithoutBuild`. I would close this issue and integrated a feature like a second command on request by the users.
