### ISSUE TITLE
Using  a Cache File

### ISSUE THREAD

**Issue by habemus-papadum** [vector-of-bool/vscode-cmake-tools#414]
### Brief Issue Summary

I would like to use a cache file (in place of a toolchain file)

### Expected:
An option to specify a cache file to use when configuring (I don't know the details of how your tool works, but 
I believe cmake processes multiple -C options in order -- so if you are using -C, it is possible for this option to peacefully coexist)

### Other Notes/Information
Note:  using a cache in place of a toolchain might not seem wise -- but in my opinion this is how apple, google, etc are building clang and other big projects, likely because cmake has very limited processing of the toolchain file, and cache is a more powerful workaround

**Comment by vector-of-bool** [comment]
Cache-init files will be settable in `settings.json`. I've opened a ticket #448 that will track setting them in other locations.
