### ISSUE TITLE
Specify path to cmake executable

### ISSUE THREAD

**Issue by habemus-papadum** [vector-of-bool/vscode-cmake-tools#417]
### Brief Issue Summary
There doesn't seem to be a config property for the cmake executable location.

### Expected:
A way to specify cmake executable location and clear instructions as to which property is to be used.

### Other Notes/Information
I have multiple versions of cmake on my system to support various projects

**Comment by KoeMai** [comment]
There is a way but it is missing inside the documentation. The settings file support it.
`"cmake.cmakePath": "<filepath of executable>"`

The `<filepath of executable>` has the default value `cmake`. This will search inside the path variable but you could use an absolute path to access the specific cmake versions.

**Comment by habemus-papadum** [comment]
Thanks!
