### ISSUE TITLE
Bring back cmake.defaultVariants

### ISSUE THREAD

**Issue by ghuser404** [vector-of-bool/vscode-cmake-tools#419]
I keep all settings in my workspace, I keep it outside of the source location.
I'm interested in specifying build variants, but the only way I found possible to do so is via cmake-variants.json (or yaml) file. However, this file must be kept in the source location `./` or `./.vscode/`, which is not desired.

Now, there is a variable called `cmake.defaultVariants`, which according to commits was previously used, but is no longer. Changing it makes no difference, and it only confuses users.

Can we get the ability to change build variants inside of VS Code back? Or maybe I missed something and it's all still possible?

**Comment by vector-of-bool** [comment]
Looks like it got dropped in the 0.11.0 and wasn't added back.
