### ISSUE TITLE
Add config option to suppress warning when build fails

### ISSUE THREAD

**Issue by nsubtil** [vector-of-bool/vscode-cmake-tools#42]
When building a project through cmake, vscode-cmake-tools will throw up a warning through the vscode UI if the build fails.

This warning seems unnecessary and persists in the UI until closed, plus it usually obscures the editor tab area, making keyboard-only operation difficult. It would be nice to get a config option to suppress this UI warning.

**Comment by vector-of-bool** [comment]
I've been growing tired of it as well. I may move it to a colored status bar element that times out automatically.

**Comment by vector-of-bool** [comment]
I decided to move it to the status bar exclusively, with a yellow color. I may change it to red to produce more visibility...

As a hint: you can press the ESC key to close all notification pop-ups in vscode. It's become muscle memory for me at this point.
