### ISSUE TITLE
MinGw32-make is not found

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#425]
### Brief Issue Summary

Mingw32-make is not found and ends in a unclear response

```
[cms-client] None of preferred generators available on the system.
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Unable to determine CMake Generator to use {}
```

### Expected:

- The mingw32 bin folder should be added to path for mingw kits.
- cmake.environment should be used for all command tests (like `this.testHaveCommand('mingw32-make');`)

**Comment by dm67x** [comment]
Did you configure your kits ?

Follow this tutorial : https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html

**Comment by KoeMai** [comment]
Yes you are right. 

I only created this issue, so that we could extend the scan algorithm. There is a settings to define the mingw search directory. This works only in the developer branch. The problem is that the mingw support is incomplete. It finds the compiler but it does not find the mingw-make and defines not the preferred generator.

**Comment by vector-of-bool** [comment]
@KoeMai do any of your recent changes address this issue?

**Comment by KoeMai** [comment]
mingw compiler is now found. To support mingw totally it is necessary add a preferred generator and the bin directory needs to be added into path environment for mingw kits.

**Comment by vector-of-bool** [comment]
Do you want to take this one on?

**Comment by KoeMai** [comment]
This issue is created out of the research of #413.
