### ISSUE TITLE
Specify command line arguments in cmake-kits.json

### ISSUE THREAD

**Issue by ghuser404** [vector-of-bool/vscode-cmake-tools#430]
I would like to be able to specify command line arguments depending on what kit is selected.

**Comment by vector-of-bool** [comment]
Are you referring to CMake arguments? Which arguments are of particular interest?

**Comment by ghuser404** [comment]
I'm talking about custom ones.

**Comment by ghuser404** [comment]
I actually found that you can set those in the toolchain file with set+cache (I'm not exactly a CMake guru).
Not sure if this ticket is relevant anymore. Feel free to close it.

**Comment by rcdailey** [comment]
This is still a fundamental requirement, especially when using the Android NDK toolchain file. You must specify arguments to CMake to configure the ABI, Platform, STL, and many other things. How does one pass `-D` arguments to CMake via a kit?

**Comment by GiantSox** [comment]
I hate to revive an old thread but I'm still struggling with this for similar reasons to @rcdailey. I have an Android NDK project that uses the NDK toolchain file, which uses MediaCodec APIs that require setting `-DANDROID_PLATFORM=28` (28/newer or `latest`). I can configure and build from the command line just fine but I'm stuck trying to figure out how to do so with CMake Tools.

**Comment by bobbrow** [comment]
@GiantSox, I believe you would do this with kit.cmakeSettings.  This only allows you to add `-D` type arguments though, not arbitrary CMake switches.

```
{
  "name": "myKit",
  "toolchainFile": "/my/toolchain.cmake"
  "cmakeSettings": {
    "ANDROID_PLATFORM": "28"
  }
}
```

**Comment by GiantSox** [comment]
@bobbrow Looks like that worked, thanks! For anyone else who stumbles across this, my kit definition for 32-bit Android NDK builds looks like this:
```
{
    "name": "Android Ninja - ARM32",
    "toolchainFile": "${env:ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake",
    "cmakeSettings": {
      "ANDROID_ABI": "armeabi-v7a",
      "ANDROID_PLATFORM": "28"
    }
},
```
