### ISSUE TITLE
You do not have a CMakeLists.txt

### ISSUE THREAD

**Issue by nsubtil** [vector-of-bool/vscode-cmake-tools#431]
### Brief Issue Summary

vscode-cmake-tools generates "You do not have a CMakeLists.txt" errors when there is a CMakeLists.txt at the root directory.

This seems to happen at random, including on older projects which were developed with vscode-cmake-tools to begin with.

### Expected:

1. Load CMake project in VSCode
2. Start compile
3. vscode-cmake-tools launches build via cmake

### Apparent Behavior:

Pop-up message that says 'You do not have a CMakeLists.txt' appears. Build doesn't start.

### CMake Tools Log

Nothing shows up in the CMake/Build log.

### Developer Tools Log

```
[Extension Host] [CMakeTools] 2018-05-17T03:01:46.733Z [debug] [main] Safe constructing new CMakeTools instance
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:46.735Z [debug] [kit] Constructing KitManager
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:46.737Z [debug] [variant] Constructing VariantManager
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:46.738Z [debug] [main] Constructing new CMakeTools instance
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:46.740Z [debug] [main] Starting CMakeTools second-phase init
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:46.741Z [debug] [rollbar] Checking Rollbar permissions
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:46.741Z [debug] [rollbar] Rollbar enabled?  true
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.077Z [info] [variant] Loaded new set of variants
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.105Z [debug] [kit] Second phase init for KitManager
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.108Z [debug] [kit] Re-read kits file from prior session
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.133Z [debug] [kit] Reading kits file C:\Users\nuno\AppData\Roaming\CMakeTools\cmake-kits.json
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.231Z [info] [kit] Successfully loaded 14 kits from C:\Users\nuno\AppData\Roaming\CMakeTools\cmake-kits.json
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.254Z [debug] [kit] Not reading non-existent kits file: c:\Users\nuno\ola\.vscode\cmake-kits.json
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.263Z [debug] [kit] Active kit set to Visual Studio Professional 2017 - amd64
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:01:47.319Z [debug] [main] CMakeTools instance initialization complete.
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:20.092Z [debug] [extension] [1130] cmake.build started
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:20.093Z [debug] [main] Saving open files before configure/build
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:20.095Z [debug] [main] Starting new CMake driver
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:20.095Z [debug] [main] Starting CMake driver
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:20.151Z [debug] [driver] CMakeDriver Kit set to Visual Studio Professional 2017 - amd64
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:20.818Z [debug] [cms-client] Started new CMake Server instance with PID 3580
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:21.821Z [debug] [driver] Trying to detect generator supported by system
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:21.874Z [info] [cms-client] Configuring using the "Ninja" CMake generator
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:21.877Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:21.957Z [debug] [cms-client] Started new CMake Server instance with PID 7316
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:22.958Z [debug] [driver] Trying to detect generator supported by system
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:23.009Z [info] [cms-client] Configuring using the "Ninja" CMake generator
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:23.013Z [debug] [main] Saving open files before configure/build
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:23.014Z [debug] [driver] Runnnig pre-configure checks and steps
notificationsAlerts.ts:39 You do not have a CMakeLists.txt
e.onDidNotificationChange @ notificationsAlerts.ts:39
console.ts:136 [Extension Host] [CMakeTools] 2018-05-17T03:07:23.015Z [debug] [driver] No configuring: There is no  c:/users/nuno/ola/cmakelists.txt
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.11.1
- **VSCode Version**: 1.23.1
- **CMake Tools Extension Version**: 0.11.1
- **Compiler/Toolchain**: VS2017/VS2015

**Comment by KoeMai** [comment]
could you show us your settings.json?

**Comment by nsubtil** [comment]
Actually... I'm seeing some other bizarre filesystem behavior during builds that is unrelated to vscode (compiler not finding local headers and the like when building well-known libraries, e.g., GLFW). Seems related to WSL.

This started after an upgrade to RS4. Downgrading makes both the vscode issues and this particular compiler problem go away. Not sure if they're related yet.

I'll try to dig in to the compile failures first. For reference, this is being tracked here: https://github.com/Microsoft/WSL/issues/3180

**Comment by petamaj** [comment]
Hi, I am having the same problem. My `settings.json` are empty, i.e. the source Directory is set to workspace root. There is `CMakeLists.txt` in the workspace root. The popup window offers me to start a new `CMakeLists.txt` when I try that, it complains that `CMakeLists.txt` already exists. 

Platform and versions same as above. Thanks!

**Comment by nsubtil** [comment]
This turns out to be caused by https://github.com/Microsoft/WSL/issues/2937 and is not a vscode issue.

FWIW, the workaround is to remount all drvfs mounts in WSL with 'case=off'.

**Comment by simonlegrand** [comment]
Hi everyone, 

I'm having exactly the same troubles as @petamaj but on a linux distribution:
- Ubuntu 16.04
- CMake 3.5.1
- VSCode 1.23.1
- CMake Tools 0.11.1

My project used to work properly with the CMake Tools extension but it recently stopped. I wouldn't be able to say from which version.

Thanks!

**Comment by vector-of-bool** [comment]
@simonlegrand sorry to be slow to reply. I've been facing some hardware failures this week. Would you mind opening a new ticket to keep the mailboxes of everyone in this thread clean, and include all of the important information in the issue template? Thanks!
