### ISSUE TITLE
remote debug 

### ISSUE THREAD

**Issue by lightgoleft** [vector-of-bool/vscode-cmake-tools#438]
### Brief Issue Summary
Is there a way to start gdb client connecting to a remote server. I am trying to debug native code on Android through adb or ssh. 

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: android cmake 3.6
- **VSCode Version**: 1.23.1
- **CMake Tools Extension Version**: 0.11.1
- **Compiler/Toolchain**: android sdk r11c

**Comment by KoeMai** [comment]
The cmaketool extension only supports basic debug only (host system and target system are runable on the same machine). Therefore it use the cpptools provided debugger. 

For your application I would set up the debug configuration in the `launch.json`, as described [here](https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html#debugging-with-cmake-tools-and-launch-json). This allows a more flexible configuration by using debugger options from the cpptools or the native debugger extension.

**Comment by vector-of-bool** [comment]
@lightgoleft does @KoeMai's comment sufficiently address your concern?

**Comment by lightgoleft** [comment]
Oh yeah. I have successfully remote debug through launch.json. One concern is that now I lost the feature of "auto build before debug" and "auto fetch cmake module name and run corresponding exec", since it is hard to extract such information out of cmake extension and fill it into launch.json.

**Comment by vector-of-bool** [comment]
The build-before-debug is going to be fixed in 1.0 (soon). I'm not sure what you are referring to by the second item?

**Comment by lightgoleft** [comment]
I got your point. I have tried. But the problem is android cmake is recognized as "legacy driver", and cannot parse target even I manually typed in target name by "cmake.setDefaultTarget" (it returned cmake.setDefaultTarget finished (returned undefined)). 

This causes cmake.launchTargetPath failed to return correct target path. 


Log: 
configure: 
>  [legacy-driver] Removing  /home/haoj/workspace/android/cmake/CMakeCache.txt
> [legacy-driver] Removing  /home/haoj/workspace/android/cmake/CMakeFiles
> [driver] Runnnig pre-configure checks and steps
> [driver] Using compilerKit android for usage
> [legacy-driver] Invoking CMake /cmake/3.6.3155560/bin/cmake with arguments ["--no-warn-unused-cli","-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/haoj/workspace/android/cmake/bin","-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/haoj/workspace/android/cmake/bin","-DCMAKE_TOOLCHAIN_FILE=/home/haoj/workspace/android/android-cmake/android.toolchain.cmake","-DANDROID_TOOLCHAIN_NAME=aarch64-linux-android-4.9","-DANDROID_NDK=/opt/android-ndk-r11c","-DCMAKE_BUILD_TYPE=Debug","-DANDROID_ABI=arm64-v8a","-DANDROID_NATIVE_API_LEVEL=24","-DANDROID_SO_UNDEFINED=true","-Wno-deprecated","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Debug","-H/home/haoj/workspace/android/test","-B/home/haoj/workspace/android/cmake"]
> [proc] Executing command: /cmake/3.6.3155560/bin/cmake --no-warn-unused-cli -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/haoj/workspace/android/cmake/bin -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/haoj/workspace/android/cmake/bin -DCMAKE_TOOLCHAIN_FILE=/home/haoj/workspace/android/android-cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN_NAME=aarch64-linux-android-4.9 -DANDROID_NDK=/opt/android-ndk-r11c -DCMAKE_BUILD_TYPE=Debug -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_SO_UNDEFINED=true -Wno-deprecated -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H/home/haoj/workspace/android/test -B/home/haoj/workspace/android/cmake
> [cmake] Not searching for unused variables given on the command line.
> [cmake] -- Configuring done
> [cmake] -- Generating done
> [cmake] -- Build files have been written to: /home/haoj/workspace/android/cmake
> [cache] Reading CMake cache file /home/haoj/workspace/android/cmake/CMakeCache.txt
> [cache] Parsing CMake cache string
> [extension] [6046] cmake.cleanConfigure finished (returned 0)

build: 

> [build] Starting build
> [driver] Runnnig pre-configure checks and steps
> [proc] Executing command: /cmake/3.6.3155560/bin/cmake --build /home/haoj/workspace/android/cmake --config Debug --target main_test -- -j 10
> [build] Scanning dependencies of target my
> [build] [ 25%] Building C object CMakeFiles/my.dir/hello.c.o
> [build] [ 50%] Linking C shared library bin/libmy.so
> [build] [ 50%] Built target my
> [build] Scanning dependencies of target main_test
> [build] [ 75%] Building CXX object CMakeFiles/main_test.dir/main.cpp.o
> [build] [100%] Linking CXX executable bin/main_test
> [build] [100%] Built target main_test
> [cache] Reading CMake cache file /home/haoj/workspace/android/cmake/CMakeCache.txt
> [cache] Parsing CMake cache string
> [build] Build finished with exit code 0
> [extension] [5883] cmake.build finished (returned 0)

launchTargetPath: 

> [extension] [3004] cmake.launchTargetPath started
> [main] =======================================================
> [main] No executable target was found to launch. Please check:
> [main]  - Have you called add_executable() in your CMake project?
> [main]  - Have you executed a successful CMake configure? 
> [main] No program will be executed
> [extension] [3004] cmake.launchTargetPath finished (returned null)

**Comment by vector-of-bool** [comment]
Ugggh... GOOGLE! They're shipping an old CMake version. `launchTargetPath` doesn't work with the legacy version because it was just too fragile and unreliable. Do you know if it is possible to use a newer CMake? It _should_ work fine unless they have made some strange modifications to CMake for the Android toolchain, and I'm not aware of them doing so.

**Comment by vector-of-bool** [comment]
Good to hear! Feel welcome to ask any more questions or report any further issues you find.
