### ISSUE TITLE
First build fails on MSBuild build files

### ISSUE THREAD

**Issue by nsubtil** [vector-of-bool/vscode-cmake-tools#44]
When starting up a new instance of vscode and loading a CMake project that has no build directory created, the first compilation will always fail. This seems to be caused by the plug-in assuming that, in the absence of build files, the default build target is `all`, which doesn't exist on VS solution files. So the very first time the build tool is invoked through CMake, it fails because it is being told to build a target that does not exist.

Once the build files are generated, the plugin automatically switches the build target to `ALL_BUILD`, so subsequent compiles will work fine.

(Side-note: despite my steady stream of issue reports, I have to give a giant thumbs-up to the project. It is a tremendous life-saver for development on Windows. Thanks!)

**Comment by vector-of-bool** [comment]
Thanks for the heads up. I don't use the VS generators very often (preferring to use Ninja on Windows), so a lot of the subtle differences catch me off guard.

**Comment by vector-of-bool** [comment]
Will be fixed in the next release.

**Comment by Zeex** [comment]
I'm seeing this behavior too, when I first open the project the default target is `all` in the status bar. Changing `all` to `ALL_BUILD` fixes the issue for me.

CMake Tools 0.8.7

**Comment by vector-of-bool** [comment]
That's unfortunate. I'll reopen this one and see when I can get to it.

**Comment by Zeex** [comment]
I think it might be because of the default build target being initialized to `all` initially:

```
private _defaultBuildTarget: string = 'all';
```
After removing `= al` everything is working 🎆

**Comment by vector-of-bool** [comment]
Curious as to what re-introduced the issue. It was probably from the big refactor in 0.8.7. I have a few more issues slated for 0.8.8, which should release tomorrow or Sunday, but I'll get to this one if I have extra time. It probably isn't that complex.

**Comment by vector-of-bool** [comment]
This should be fixed now in 0.8.8
