### ISSUE TITLE
Generate Kit for Mingw with preferred generator and environment includes

### ISSUE THREAD

**Issue by KoeMai** [vector-of-bool/vscode-cmake-tools#449]
### Brief Issue Summary

The `cmake.mingwSearchDirs` allows to find MinGw for build. But the configuration is incomplete.

### Expected:
For a successful configuration and build the kit file needs the MinGw in the environment variable and optional the `mingw-make` as preferred generator.

**Comment by KoeMai** [comment]
This issue is created out of the research of #413.

**Comment by vector-of-bool** [comment]
@KoeMai do you want to get this one in 1.1.0?
