### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#45]
(this is not really a bug report or feature request, but just a request to clarify the question)
the tasks in vscode allow to configure "env" environment variables.
so, with your plugin, I don't use tasks anymore. that's perfect.
but I don't know how to configure all required env variables with an extension.
currently I'm using .cmd file to start vscode with a preparing those variables,.
this is mostly a PATHs, to compiler, to cmake, to llvm, etc.
I'd like to use this configuration vscode inside, as previously. for workspace specific.

could you clarify - is it possible with your extension and how? 

thank you

**Comment by MinnieTheMoocher** [comment]
I agree that it would be nice if we could supply environment variables for the cmake calls your extension does. I would like to be able to supply them as user settings which your extension  reads and sets before spawning cmake.

**Comment by amigo421** [comment]
actually this should not be extension responsibility area, 
many env variables has to be allocated for whole vscode, so user settings tfor the editor itself would be preferable. however a custom tuning the environment for a project is also required

**Comment by vector-of-bool** [comment]
I don't think there is a way to configure it for the whole editor, but I would be able to set environment variables for invocations of cmake. I have a similar situation with using msvc, where Code must be started with the vcvarsall-type environment variables already set.

If I could programmatically determine the msvc environment variables and set them before running cmake, running in the dev cmd prompt would be unnecessary and simplify the windows workflow.

**Comment by amigo421** [comment]
if you have an experience with QtCreator , it detects installed VC toolchains somehow. I'll look at this. if I'll found I'll let you know

**Comment by MinnieTheMoocher** [comment]
no, I'm against implementing that stuff inside VSCode or its extensions.
instead, the cmake extension should
- be able to set custom environment variables prior to run cmake
- run a custom batch (e.g. the one you suggest) in the same shell before running cmake

The second point in fact means that not 2 process spawns should be done like
   run_your_batch.bat
   cmake
but instead both together in the same shell, making the env changes of the batch available to cmake like this:
   run_your_batch.bat && cmake

In your case that would be
   vcvarsall.bat && cmake

However, I do not like to invoke that batch.

My usecase is different, I need to set env variables which cmake sees.

**Comment by vector-of-bool** [comment]
Next release should support passing environment variables

**Comment by MathiasMagnus** [comment]
I could not guess the syntax of setting an absolute path to vcvars64.bat when there is a space in the path. Nonetheless I would guess that running the vcvars*** before EVERY build (because it calls cmake --build) would be incredibly slow.

I wanted to patch the environment through the new feature, but how do I append to an existing variable? Sorry for the dumb question, but I am new to both JSON and Code extensions. For eg.

`"cmake.defaultVariants": {
        "buildType": {
            "default$": "debug"`

What is the $ sign doing at the end? Is that an artifact of later being used by TypeScript?
