### ISSUE TITLE
CMake: Quick Start command creates main with Hello World indented with 3 spaces

### ISSUE THREAD

**Issue by yay** [vector-of-bool/vscode-cmake-tools#466]
It's a very minor thing, but gets annoying eventually. At first I always miss that the indent is 3 spaces, then at one point it becomes obvious and I have to fix the indentation.

```cpp
int main(int, char**) {
   std::cout << "Hello, world!\n"; // expect this to be indented with 4 spaces, not 3
}
```

Terrific extension otherwise!

### Platform and Versions

- **Operating System**: macOS 10.12.6
- **CMake Version**: 3.11.3
- **VSCode Version**: 1.24.1
- **CMake Tools Extension Version**: 1.0.1
- **Compiler/Toolchain**: Apple LLVM version 9.0.0 (clang-900.0.39.2)

**Comment by vector-of-bool** [comment]
That's definitely not intentional. Three-space indentations are a cardinal sin.
