### ISSUE TITLE
No entries found in CMakeCache

### ISSUE THREAD

**Issue by gotschmarcel** [vector-of-bool/vscode-cmake-tools#469]
### Brief Issue Summary

When editing the CMake Cache the following message appears: "There are no cache entries to show. Have you configured the project?". The project is configured and the actual cache file contains many entries. The path that is shown at the top of the editor points to the correct cache file.

### Expected:

1. Open a CMake Workspace
2. Configure CMake
3. Open the cache editor (e.g. from the command palette: "CMake: Edit the CMake Cache")
4. Editor panel opens and shows entries

### Apparent Behavior:

No entries shown, instead this message shows up: "There are no cache entries to show. Have you configured the project?"

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.11.3
- **VSCode Version**: 1.24.1
- **CMake Tools Extension Version**: 1.0.1
- **Compiler/Toolchain**: Clang 9.1

**Comment by vector-of-bool** [comment]
The cache editor needs a lot of fixes. With the new WebView APIs from VSCode I should be able to make something better than what's already there.

**Comment by gotschmarcel** [comment]
Sounds good to me :)

**Comment by vector-of-bool** [comment]
The WebView API is available now, I just have not had a chance to look into it and see what it will take.

**Comment by TheErk** [comment]
Same symptom here on Linux (Debian Stretch).

**Comment by vector-of-bool** [comment]
I'm going to close this one in favor of #513. The cache-editor is dead! Long live the cache-editor!
