### ISSUE TITLE
stray cmake option -DBUILD_SHARED_LIBS=FALSE

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#47]
I used VSCode plus CMake Tools 0.6.0.

They strangely pass an unwanted option -DBUILD_SHARED_LIBS=FALSE to cmake.

That's a custom, non-standard cmake option.
My build issues a warning about that that variable gets set but not read / used.

Please don't provide that option to cmake. It seems to be generator-specific (maybe Ninja?).

I use generator "Visual Studio 14 2015" instead._

**Comment by MinnieTheMoocher** [comment]
if you want to send that option to cmake, there's the Preferences setting
`cmake.configureSettings`
available. It can be used to specify custom cmake variable settings.

**Comment by vector-of-bool** [comment]
[It actually is a standard option that not enough projects use](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html), but I'm not sure why it would be passing it in for your project.

I planned on adding support for it in the future, but I specifically decided to leave it out for now. I may have committed something by accident. I'll look into it.

**Comment by MinnieTheMoocher** [comment]
the VSCode cmake plugin should work with as many cmake versions as possible IMHO.
it should not just work with the latest greatest.
the BUILD_SHARED_LIBS switch is not present in cmake version 3.4.4 which we currently use.
upgrading cmake is not always possible, so the vscode extension should not be tied
to it too close IMHO.
If somebody wants to set that option, he/she can do as custom setting,
but, as said, it should not be supplied as standard option by default IMHO

**Comment by vector-of-bool** [comment]
[BUILD_SHARED_LIBS has been available since at least CMake 2.6](https://cmake.org/cmake/help/cmake2.6docs.html#variable:BUILD_SHARED_LIBS). You are probably seeing the warning because the project may not be using `add_library`. Either way, the warning should not be visible to users. I'll see what I can do.

**Comment by MinnieTheMoocher** [comment]
OK, that may be the case. I tested it with a simple hello world project which only consisted of a add_executable() call, no add_library().

However, none of our builds currently supplies that option on the command line to cmake.
I think if anybody wants that, he/she can set that as custom option.
The default should be "does not get set", i.e., the option -DBUILD_SHARED_LIBS=... should not be present on the cmake command line by default.

(To explain why I am so curious about this cmake integration into VSCode:
amongst other things, in our company I'm responsible for the build process since > 10 years.
Just FYI)

**Comment by vector-of-bool** [comment]
This should be cleaned up in the next release. I still set the parameter, but I've come up with a solution that will keep it out of sight and out of mind for users who don't care about it.
