### ISSUE TITLE
Broken compiler symlinks cause ENOENT error

### ISSUE THREAD

**Issue by ryanlevy** [vector-of-bool/vscode-cmake-tools#470]
### Brief Issue Summary

I've fixed the issue on my end but wanted to document in case someone else runs into this. I had broken symlinks to macports gcc compilers from switching computers which were found during the kit search. Any attempt to use the extension (even quick start) was met with the error
```bash
ENOENT: no such file or directory, stat '/opt/local/bin/gcc'
```
which was confusing as that file did exist (it was just symlinked to a file that didn't exist). 

To reproduce, go to `/opt/local/bin` (create it if necessary) and create some dummy symlink like
`sudo ln -s foo gcc` and rescan for kits.

### Expected:
Everything not to instantly break

### CMake Tools Log
```
[kit] Failed to check binary /opt/local/bin/gcc by exception: Error: spawn /opt/local/bin/gcc ENOENT
[kit] Failed to check binary /opt/local/bin/gcc by exception: Error: spawn /opt/local/bin/gcc ENOENT
[rollbar] Unhandled exception: Unhandled Promise rejection: scanForKits Error: ENOENT: no such file or directory, stat '/opt/local/bin/gcc' {}
```
### Platform and Versions

- **Operating System**:  macOS
- **CMake Version**:  3.10.3
- **VSCode Version**:  1.24.1
- **CMake Tools Extension Version**:  1.0.1
- **Compiler/Toolchain**: GCC 7.3.0

### Other Notes/Information

It'd be nice if it was handled by the extension but at worst it's a user problem.

**Comment by vector-of-bool** [comment]
Good find. I'll add it to the next milestone
