### ISSUE TITLE
cannot build custom target INSTALL

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#48]
I'm using VSCode plus CMake tools extension 0.6.0.

I use "Visual Studio 14 2015" as generator.

I ran the cmake configure command.

After that I wanted to run the "CMake: Build a Target" command.

It prompted me with a text box to enter the make target.

I entered INSTALL there and hit enter.

Nothing happens. cmake isn't launched.
The box just silently closes and does nothing :(

When I choose "CMake: Install" instead,
the build for the build target INSTALL gets launched.

Why does the manual launch of a specific build target no longer work?

**Comment by vector-of-bool** [comment]
Very strange... I'll look into it.
