### ISSUE TITLE
Cmake install error : Can not configured 

### ISSUE THREAD

**Issue by tamdinh** [vector-of-bool/vscode-cmake-tools#480]
### Brief Issue Summary
Cmake cannot be configured.
### Expected:
There is no error.

### Apparent Behavior:

<img width="314" alt="c_cpp_properties_json_ _simpleblockchain_and_helloworldcpp-vscode-withtask" src="https://user-images.githubusercontent.com/2469248/42938588-f8a8af44-8b7c-11e8-9587-4407d3c96393.png">

When I click to it there is an error message:

<img width="470" alt="c_cpp_properties_json_ _simpleblockchain_and_inbox__727_messages__2_unread_" src="https://user-images.githubusercontent.com/2469248/42938339-2ac14fdc-8b7c-11e8-980c-fcad3fa9197a.png">

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.9.1
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.0.1
- **Compiler/Toolchain**: Apple LLVM version 9.1.0 (clang-902.0.39.2)

**Comment by vector-of-bool** [comment]
Looks like bad error handling. Have you run `Scan for kits`? If so, are you using a kit? Which one?

**Comment by tamdinh** [comment]
Hi,
I have reopened and use Scan for kits as you suggested and now it works.
Thank you a lot.
