### ISSUE TITLE
Add a donation link?

### ISSUE THREAD

**Issue by barcharcraz** [vector-of-bool/vscode-cmake-tools#483]
After the latest release I came to the github page in the hopes of sending vector-of-bool and a few dollars in appreciation for this plugin. Would you consider adding such a link?

**Comment by vector-of-bool** [comment]
I'm so humbled that you think my Internet shenanigans are worthy of your money. Thank you!

I've never actually thought about doing this, and I don't understand the ramifications of doing so. It's hard to find information on doing this. How do most people do it?

**Comment by vector-of-bool** [comment]
I'd also like to note that I'm not entirely alone on this one. @KoeMai and @Randshot have done work on this as well.

**Comment by barcharcraz** [comment]
I've seen use of librepay, and bountysource.

**Comment by barcharcraz** [comment]
Looks like https://www.patreon.com/vector_of_bool is the place to go!

Closing this issue now as it is "fixed"
