### ISSUE TITLE
Execute target doesn’t handle spaces

### ISSUE THREAD

**Issue by gotschmarcel** [vector-of-bool/vscode-cmake-tools#487]
### Brief Issue Summary

When running “Execute the current target without a debugger” it’s trying to run the command, but fails if there are spaces in it. 

### Expected Behavior:

Handles spaces properly and executes the target. 

### Apparent Behavior:

Fails to execute with “unknown command”. 

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.9.1
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.0

### Other Notes

Need to escape spaces in the file or use quotes.

**Comment by vector-of-bool** [comment]
Should be an easy fix. Will be in next bugfix rel
