### ISSUE TITLE
Variable expansion for Variants

### ISSUE THREAD

**Issue by gotschmarcel** [vector-of-bool/vscode-cmake-tools#488]
### Brief Issue Summary

In the documentation there’s a paragraph about variable expansions and it mentions an expansion for variants: ${variant_identifier}. How does it work? I couldn’t get it to work. 

### Expected:

Using this placeholder expands to the currently active variant name. 

### Apparent Behavior

Error log: [expand] Invalid reference ${variant_identifier} in string ...

**Comment by vector-of-bool** [comment]
`variant_identifier` refers to a variant key. It looks like `buildType` is special-case renamed to `buildLabel`, which is somewhat annoying. Do you have a `variants.(json|yaml)`?

**Comment by vector-of-bool** [comment]
Maybe tweak it to support both, for legacy but also uniformity?

**Comment by Randshot** [comment]
What do you mean with legacy and uniformity?

**Comment by vector-of-bool** [comment]
Support `buildLabel` as an alias for `buildType`. That way `buildType` is replaced as expected, but `buildLabel` will continue to work.

**Comment by Randshot** [comment]
Eh, now I am confused.
At the moment `buildType` is used for getting the current CMake build configuration type: `buildType: this.currentBuildType`
And for variants, it checks whether the key identifier is `buildType` and if that is the case, it replaces the identifier with `buildLable` to avoid overwriting the previous definition of `buildType`.

**Comment by vector-of-bool** [comment]
Oh... Hmm. That makes sense, but it still somewhat confusing. Probably worth a note in the docs then.

**Comment by Randshot** [comment]
Yeah, it is confusing, but I had no other choice unless the variant or settings.json api is changed.

**Comment by gotschmarcel** [comment]
Thanks for the clarification! Maybe the documentation could give an example what exactly is meant by the `variant_identifier`. To me this was not clear. I thought it would expand to the currently active variant, e.g. if you have `buildType` and `OpenGL` as variants I expected these kind of expansions: `Debug`, `Debug+OpenGL`, `Release`and others.

**Comment by Randshot** [comment]
Here is an example.
If you have the following `cmake-variants.yaml`:
```yaml
mybuildtype:
  default: debug
  choices:
    mydebug:
      short: Debug
      long: Emit debug information
      buildType: Debug
    myrelease:
      short: Release
      long: Optimize generated code
      buildType: Release
```

And then use the variant substitution/expansion like this (`settings.json`):
```json
{
    "cmake.configureSettings": {
        "TEST_CMAKE_VAR": "${mybuildtype}"
    }
}
```

This will expand `${mybuildtype}` to either `mydebug` or `myrelease`, depending on what you currently have active for that particular variant option.

**Comment by Randshot** [comment]
I will close this one.

**Comment by gotschmarcel** [comment]
@vector-of-bool works for me. Thanks!
