### ISSUE TITLE
Substitution of environment variables seems not to work

### ISSUE THREAD

**Issue by hriekehof** [vector-of-bool/vscode-cmake-tools#489]
### Brief Issue Summary

substitution of environment variables seems not to work in cmake.configureSettings on Windows.

```
    "cmake.configureSettings": {
        "CMAKE_MODULE_PATH" : "${env:SOME_VAR}/utils",
    }
```
When i run the configure process the environment variable is not being substituted. I can check this in the CmakeCache.

### Expected:

I would expect that environment variables are substituted. But this is not happening. 

### Apparent Behavior:

It appears that just the the rest of the string is passed to the CmakeCache.txt. It just appears the string "/utils"
However the substitution of build in variables works without any problem. For example:
```
    "cmake.configureSettings": {
        "CMAKE_MODULE_PATH" : "${workspaceRoot}/utils",
    }
```

### CMake Tools Log
If my module path is not correct CMake will not find some included files thats all.

### Platform and Versions

- **Operating System**: Windows 10 Pro 1803
- **CMake Version**: 3.11.0
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.0
- **Compiler/Toolchain**: arm-none-eabi-gcc

**Comment by vector-of-bool** [comment]
Will look into it

**Comment by hriekehof** [comment]
Thanks. I totally missed to say, that this extension is totally awesome 🥇

**Comment by Randshot** [comment]
@vector-of-bool I think I know what the problem is.
The problem seems to be, that, when fetching the configure environment, it doesn't include the (vscode) process environment.
```ts
const expanded_configure_env = this.getConfigureEnvironment();
```

You could see this as a bug or a feature...

**Comment by vector-of-bool** [comment]
That's a bug, and I found a probable fix.

**Comment by DeveloperPaul123** [comment]
I'm experiencing the same bug currently. The environment variable is getting replaced by nothing currently.

Operating System: Windows 10 Pro 1803
CMake Version: 3.14.0
VSCode Version: 1.33.1
CMake Tools Extension Version: 1.1.3
Compiler/Toolchain: clang 8.0.0 with VS 2019

**Comment by nackdai** [comment]
> I'm experiencing the same bug currently. The environment variable is getting replaced by nothing currently.
> 
> Operating System: Windows 10 Pro 1803
> CMake Version: 3.14.0
> VSCode Version: 1.33.1
> CMake Tools Extension Version: 1.1.3
> Compiler/Toolchain: clang 8.0.0 with VS 2019

Me too

OS: Ubuntu 18.04 LTS
CMake: 3.10.2
cmake-tools: 1.1.3
vscode: 1.37.1
