### ISSUE TITLE
CMake: Build a target... and then hitting just enter does no longer work

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#50]
It should be possible for a user to not explicitly specify a make target.

Previously, this was possible in this extension by just hitting ENTER after the command
`CMake: Build target ...`

This no longer works in version 0.6.0. When you just hit ENTER, nothing happens.

Expected: just a default build (for example `make`) without specified build target should be launched.
The implicit default of "all" will be used in those cases, but that is the job of the build backend.

The VSCode extension should just invoke that build, without handing a build target to it.

**Comment by MinnieTheMoocher** [comment]
Update: even when I enter a target for building there, the build is not launched.
This is probably related to #48 .

I just can't enter a make target at all. When I do and hit ENTER, nothing happens.

**Comment by vector-of-bool** [comment]
My guess is that this and #48 are caused by the same bug and it's related to the VS generator. I'll poke at it when I get some time later today.
