### ISSUE TITLE
Configure and build with toolchain file only (no kit)

### ISSUE THREAD

**Issue by DexterMagnific** [vector-of-bool/vscode-cmake-tools#500]
### Configure and build without selecting a kit

I have setup my project to use a toolchain file

```
"cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE" : "${workspaceRoot}/../config/cmake/hexagon.cmake"
    },
```
The toolchain file defines the compilers. But currently I cannot configure and build without selecting a toolkit.

### Expected:

1. I can configure and build without selecting a toolkit

### Apparent Behavior:

1. Cannot configure without selecting a toolkit. This is annoying since:
- I have to manually add the toolkit, which will be unused because the toolchain file redefines it
- the toolkit configuration file is located outside the project tree (in the home dir). This is a flaw since only the project knows where to find the compiler (given that it is installed in the recommended location).

### Platform and Versions

- **Operating System**: Any
- **CMake Version**: 3.11.2
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.1
- **Compiler/Toolchain**: Custom target compiler, based on CLang 3.9.0

**Comment by vector-of-bool** [comment]
You should see an `[Unspecified]` kit when it asks you to choose one. Selecting this is the equivalent of "no kit," and doesn't require you to modify or configure any kit files. Does this work for your case?

**Comment by DexterMagnific** [comment]
Hi,

Yes selecting "Unspecified" works thank you. But it has the following two bad side effects:
- When I restart VSCode, it does not remember the "unspecified" choice. You have to select it again
- When configuring and after building, dozens of the following messages are shown and pollute the "output" view:

```
[rollbar] Unable to automatically determine compiler {"lang":"C","fileGroup":{"compileFlags":" -mv60 -D_HAS_C9X -fPIC -O3 C:/Hexagon3.2/Hexagon_SDK/3.2/tools/HEXAGON_Tools/8.0.10/Tools/target/hexagon/lib/v5/G0/libc.a -Wall -Wextra -g  ","includePath":[{"path":"C:/Users/slankri/DspRefBase-Hexagon/build/audio/modules/AGC"},{"path":"C:/Users/slankri/DspRefBase-Hexagon/src/audio/modules/AGC"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/tools/HEXAGON_Tools/8.0.10/Tools/target/hexagon/include"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/incs"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/incs/audio"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/incs/stddef"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/incs/a1std"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/libs/common/rtld/ship/hexagon_Debug_dynamic_toolv72_v60"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/libs/audio/capi_v2_utils_props/inc"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/libs/common/atomic/inc"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/test/common/cpptest/inc"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/test/common/test_profile/inc"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/test/common/test_main/inc"},{"path":"C:/Hexagon3.2/Hexagon_SDK/3.2/test/common/test_capi_v2/inc"},{"path":"c:/users/slankri/dsprefbase-hexagon/src"}],"isGenerated":false,"language":"C","sources":["AGC.c"]}}
```

I have this message for each compiled file.

Thanks

**Comment by vector-of-bool** [comment]
If it isn't remember that you chose "Unspecified," that is a bug. Could you make another ticket for this?

The other output is unexpected. What is your toolchain doing? Are you setting a `CMAKE_C_COMPILER` in the toolchain?

Also, have you looked at using "toolchain" kits? It will let you use the kits feature but also use a toolchain file alone.

**Comment by DexterMagnific** [comment]
Thanks.

Submitted #502 for the first problem.

For the second case:

Yes I'm setting CMAKE_C_COMPILER and CMAKE_CXX_COMPILER.

Please find below my toolchain file:

```
# Linux system (CMake is not able to make the compiler work when system is Windows)
set(CMAKE_SYSTEM_NAME "Linux")

# Hexagon SDK
if ("$ENV{HEXAGON_SDK_ROOT}" STREQUAL "")
  message(FATAL_ERROR "\
The HEXAGON_SDK_ROOT environment variable is not set. \
Please set it to your HEXAGON SDK path")
endif()

# Save the variable
set(HEXAGON_SDK_ROOT "$ENV{HEXAGON_SDK_ROOT}")

# Hexagon SYSROOT
set(CMAKE_SYSROOT "${HEXAGON_SDK_ROOT}")

if (NOT EXISTS "${CMAKE_SYSROOT}")
  message(FATAL_ERROR "\
The ${CMAKE_SYSROOT} could not be found. Is the HEXAGON_SDK_ROOT \
environment variable correctly set ? Its current value is HEXAGON_SDK_ROOT=${HEXAGON_SDK_ROOT}")
endif()

# Compilers
if ("$ENV{OS}" MATCHES "Windows*")
  set(CMAKE_C_COMPILER ${CMAKE_SYSROOT}/tools/HEXAGON_Tools/8.0.10/Tools/bin/hexagon-clang.exe)
  set(CMAKE_CXX_COMPILER ${CMAKE_SYSROOT}/tools/HEXAGON_Tools/8.0.10/Tools/bin/hexagon-clang++.exe)
else()
  set(CMAKE_C_COMPILER ${CMAKE_SYSROOT}/tools/HEXAGON_Tools/8.0.10/Tools/bin/hexagon-clang)
  set(CMAKE_CXX_COMPILER ${CMAKE_SYSROOT}/tools/HEXAGON_Tools/8.0.10/Tools/bin/hexagon-clang++)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Includes
include_directories(${HEXAGON_SDK_ROOT}/tools/HEXAGON_Tools/8.0.10/Tools/target/hexagon/include)
include_directories(${HEXAGON_SDK_ROOT}/incs)
include_directories(${HEXAGON_SDK_ROOT}/incs/audio)
include_directories(${HEXAGON_SDK_ROOT}/incs/stddef)
include_directories(${HEXAGON_SDK_ROOT}/incs/a1std)
include_directories(${HEXAGON_SDK_ROOT}/libs/common/rtld/ship/hexagon_Debug_dynamic_toolv72_v60)
include_directories(${HEXAGON_SDK_ROOT}/libs/audio/capi_v2_utils_props/inc)
include_directories(${HEXAGON_SDK_ROOT}/libs/common/atomic/inc)
include_directories(${HEXAGON_SDK_ROOT}/test/common/cpptest/inc)
include_directories(${HEXAGON_SDK_ROOT}/test/common/test_profile/inc)
include_directories(${HEXAGON_SDK_ROOT}/test/common/test_main/inc)
include_directories(${HEXAGON_SDK_ROOT}/test/common/test_capi_v2/inc)

# Links
#link_directories(${CMAKE_SYSROOT}/target/hexagon/lib/v60)

# Flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mv60 -D_HAS_C9X -fPIC -O3 ${HEXAGON_SDK_ROOT}/tools/HEXAGON_Tools/8.0.10/Tools/target/hexagon/lib/v5/G0/libc.a")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mv60 -D_HAS_C9X -fPIC -O3 ${HEXAGON_SDK_ROOT}/tools/HEXAGON_Tools/8.0.10/Tools/target/hexagon/lib/v5/G0/libc.a")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_LDFLAGS} -nostartfiles -nodefaultlibs -nostdlib -Wl,--wrap=malloc -Wl,--wrap=calloc -Wl,--wrap=free -Wl,--wrap=realloc -Wl,--wrap=memalign -Wl,--wrap=__stack_chk_fail -shared -G0 -fPIC")
```

As you can see there is nothing special in this file.

I do not understand the "toolchain kits" suggestion. Our project comes with the toolchain file inside one of its directories. We don't want each user to configure it himself.

If these is any other proper way of telling CMake Tools about the toolchain file, please let me know it so I can try.

Thanks

**Comment by vector-of-bool** [comment]
Check out the Kits docs [here](https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html#toolchain). Setting `toolchainFile` in a kit should give you the ability to select the toolchain as a regular kit.

Another test: After a successful configure from the command line, can you paste the output from `cmake -N -L`? Note that this might contain sensitive values, so check and/or edit before pasting. I'm mostly interested in any `CMAKE_*` cache values.

**Comment by DexterMagnific** [comment]
I have set the toolchain file inside cmake-kits.json and it worked. Now I can select the kit from the kits menu. This is great since I can tell developers to select the correct kit rather than "unspecified". Thanks.

The effect of this is that the Kit is remembered when restarting VSCode.

Now the second case (errors about roller bar) are still here.

Here is the requested output:
```
-- Cache values
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_STATIC_LIBS:BOOL=ON
BUILD_TESTING:BOOL=ON
BUILD_TESTS:BOOL=OFF
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=C:/Program Files (x86)/XXXXX_deleted
CMAKE_TOOLCHAIN_FILE:FILEPATH=C:/Users/slankri/DspRefBase-Hexagon/config/cmake/hexagon.cmake
```

**Comment by vector-of-bool** [comment]
It looks to be that the `_COMPILER` cache entries are not there. In the toolchain file, try changing the `set(CMAKE_C_COMPILER ...)` to `set(CMAKE_C_COMPIMLER_INIT ...)` (For both `C` and `CXX`. Note the `_INIT` on the end of the var names. This changes the way CMake tries to load the compilers. If that doesn't work, change the `set()` commands to use `CACHE` mode for the compilers.

**Comment by DexterMagnific** [comment]
Hi,

Adding the _INIT suffix does not work: CMake takes the compiler it autodetects (the host compiler)
Adding CACHE mode works: rollbar errors have disappeared. But I notice that cmake -N -L produces the same output as before.
Also, compilation is fine without CACHE, and according to the documentation CACHE is not needed when setting the compilers. So there must be something weird between the generated config and the rollbar.

**Comment by vector-of-bool** [comment]
The trouble is in that I use the cache entries to determine the per-language compiler. The source files declare their language as either `C` or `CXX`, so I look for the cache entry for `CMAKE_<LANG>_COMPILER`. If the cache entry is not present, it produces that warning. I'll have to either document that `CACHE` is required for cmt, or find a different way of getting the compiler path.

**Comment by DexterMagnific** [comment]
Ok thanks. For now I can live with CACHE added, but it has to be documented. I hope there won't be any side effect regarding CMake build.

Please close this item if you feel it's OK. I have nothing special to add for now.

Thanks for your help.

**Comment by vector-of-bool** [comment]
I'll mark it as a documentation bug for now. Maybe show a user warning if necessary.

**Comment by mmanyen** [comment]
Don't know if this is helpful but I am doing a cross compiler toolchain as well and have it working.

In cmake-tools.json:
{
    "name": "Green Hills INTEGRITY",
    "toolchainFile": "${workspaceFolder}/GHSToolchain.cmake"
}

This allows me to select between kits (Linux,Win32 and GHS) from the bottom bar

**Comment by DexterMagnific** [comment]
Yes using a toolchain file works. Do you have the "rollbar" errors above ? Could you share your toolchain file with us to compare ? Thanks

**Comment by mmanyen** [comment]
Here is the toolchain file:

# CMake for GHS Integrity (By: Mark Manyen)
# Environment Variables used (IF set)
#   GHS_HOME         (default: ./GHSIntegrity)
#   GHS_OS_REV       (default: 1144)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER cxintarm)
set(CMAKE_CXX_COMPILER ccintarm)
set(CMAKE_C_COMPILER ${CMAKE_C_COMPILER} CACHE FILEPATH "C Compiler")
set(CMAKE_CXX_COMPILER ${CMAKE_CXX_COMPILER} CACHE FILEPATH "CXX Compiler")

# Define the absolute path to the GHS directory for the rest of the tree to reference
# If there is an environment variable "GHS_HOME", use that instead of default location
if (DEFINED ENV{GHS_HOME})
  set(GHS_HOME $ENV{GHS_HOME})
else()
  get_filename_component(GHS_HOME ./GHSIntegrity ABSOLUTE)
endif(DEFINED ENV{GHS_HOME})

set(GHS_OS_ROOT ${GHS_HOME})
set(GHS_OS_ROOT ${GHS_OS_ROOT} CACHE PATH "GHS platform OS search root directory")
mark_as_advanced(GHS_OS_ROOT)

# If there is an environment variable "GHS_OS_REV", use that instead of default revision
if (DEFINED ENV{GHS_OS_REV})
   set(GHS_OS_REV $ENV{GHS_OS_REV})
else()
   set(GHS_OS_REV int1144)
endif(DEFINED ENV{GHS_OS_REV})

set(GHS_OS_DIR ${GHS_HOME}/${GHS_OS_REV})
set(GHS_OS_DIR ${GHS_OS_DIR} CACHE PATH "GHS platform OS directory")
mark_as_advanced(GHS_OS_DIR)

set(GHS_BSP_NAME "default" CACHE STRING "BSP name")

string(APPEND GHS_CC_BASICS  " --no_commons -Wformat -bsp=${GHS_BSP_NAME} -os_dir=${GHS_OS_DIR}")

set(CMAKE_C_VERBOSE_FLAG "-v")
set(CMAKE_C_OUTPUT_EXTENSION ".o")

string(APPEND CMAKE_C_FLAGS_INIT " ${GHS_CC_BASICS}")
string(APPEND CMAKE_C_FLAGS_DEBUG_INIT " -Odebug -g")
string(APPEND CMAKE_C_FLAGS_MINSIZEREL_INIT " -Ospace")
string(APPEND CMAKE_C_FLAGS_RELEASE_INIT " -O")
string(APPEND CMAKE_C_FLAGS_RELWITHDEBINFO_INIT " -O -g")

set(CMAKE_CXX_VERBOSE_FLAG "-v")
set(CMAKE_CXX_OUTPUT_EXTENSION ".o")

string(APPEND CMAKE_CXX_FLAGS_INIT " -language=cxx ${GHS_CC_BASICS}")
string(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT " -Odebug -g")
string(APPEND CMAKE_CXX_FLAGS_MINSIZEREL_INIT " -Ospace")
string(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT " -O")
string(APPEND CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT " -O -g")

set(CMAKE_FIND_ROOT_PATH ${GHS_OS_DIR})
# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

**Comment by mmanyen** [comment]
markdown fun!
