### ISSUE TITLE
Special kits that only specify toolchain file and generator

### ISSUE THREAD

**Issue by decimad** [vector-of-bool/vscode-cmake-tools#501]
Is it possible to create a custom "Kit" that only sets a preferred generator and a toolchain file for configuration? That would be great, since we wouldn't have to fix cmake tools to one toolchain file system-wide (by user settings) or edit the settings per project.

**Comment by vector-of-bool** [comment]
This should be supported. [Check here](https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html#toolchain). You can set the `preferredGenerator` in the kit as well.

**Comment by decimad** [comment]
Oh, I missed that spot... sorry. But this is great news for me! :)

**Comment by vector-of-bool** [comment]
Excellent. I'll close this, but you can re-open it if you have any more questions or concerns.
