### ISSUE TITLE
command 'cmake.*' not found

### ISSUE THREAD

**Issue by JohannesWoeber** [vector-of-bool/vscode-cmake-tools#503]
### Brief Issue Summary

Hi, after installation of cmake over the extensions marketplace I tried to call the Qickstart Start command resulting in 
`command 'cmake.configure' not found`

- **Operating System**: Windows 10
- **VSCode Version**: 1.24.1
- **CMake Tools Extension Version**: 1.0.1

### Other Notes/Information

I had installed cmake previously over choco but deleteted it via choco uninstall after installing this. Could that mess something up?

**Comment by Randshot** [comment]
Your CMake installation shouldn't affect this issue, as far as I know.
I have noticed, that you have an older version of CMT. Could you maybe get the newest one (1.1.1) and report back again?

**Comment by JohannesWoeber** [comment]
Hi,
thank you updating vscode and CMT fixed this.
