### ISSUE TITLE
Lower-cased path in cmake build command

### ISSUE THREAD

**Issue by decimad** [vector-of-bool/vscode-cmake-tools#507]
Hi there,
given ```"cmake.buildDirectory": "${workspaceFolder}/build/${buildType}"``` the path ends up lower-cased on the cmake build command, resulting in lower cased paths for error-messages for me. As usual, this is problematic since then vscode will not be able to associate problems with files opened through the project browser (which have the physical casing).

**Comment by vector-of-bool** [comment]
There is a persistent trouble with paths on Windows. The path normalization will lowercase paths, but this case-normalization is only really needed when doing path comparison. I'll look into this, as it is a persistent problem.
