### ISSUE TITLE
CompileFile not working on MacOS

### ISSUE THREAD

**Issue by john-mullins** [vector-of-bool/vscode-cmake-tools#509]
### Brief Issue Summary
The command CMake:CompileFile does not seen to issue the correct command to the compiler on MacOS.

### Expected:

In the explorer View right-click on the file and select Compile File.
Alternatively with file in the editor view select CMake: CompileFile from the command palette

### Apparent Behavior:
The file fails to compile as it cannot find the #include'd files.

### CMake Tools Log

Output from terminal:

MacBook-Pro:build john$ /usr/bin/clang++ "/Users/john 1/projects/TestFramework/." "/Users/john 1/projects/dqer/." "/Users/john 1/projects/tci/." -O3 -DNDEBUG -std=gnu++1z -o CMakeFiles/dqer_tests.dir/micromip32r6_info_tests.cpp.o -c "/Users/john 1/projects/dqer/tests/micromip32r6_info_tests.cpp"
clang: warning: /Users/john 1/projects/TestFramework/.: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: /Users/john 1/projects/dqer/.: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: /Users/john 1/projects/tci/.: 'linker' input unused [-Wunused-command-line-argument]
/Users/john 1/projects/dqer/tests/micromip32r6_info_tests.cpp:1:10: fatal error: 'dqer/micromips32r6_info.h' file not
      found
#include "dqer/micromips32r6_info.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
MacBook-Pro:build john$

The relevant settings from compile_commands.json are:

{
  "directory": "/Users/john 1/projects/dqer/tests/build",
  "command": "/usr/bin/clang++   -I\"/Users/john 1/projects/TestFramework/.\" -I\"/Users/john 1/projects/dqer/.\" -I\"/Users/john 1/projects/tci/.\"  -O3 -DNDEBUG   -std=gnu++1z -o CMakeFiles/dqer_tests.dir/micromip32r6_info_tests.cpp.o -c \"/Users/john 1/projects/dqer/tests/micromip32r6_info_tests.cpp\"",
  "file": "/Users/john 1/projects/dqer/tests/micromip32r6_info_tests.cpp"
},

### Platform and Versions

- **Operating System**: macOS 10.13.6
- **CMake Version**: 3.12.0
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.1
- **Compiler/Toolchain**: Apple clang 9.1.0

### Other Notes/Information

The issue seems fairly straightforward. Somewhere in the command line cleaning/formatting process the "-I" to specify which files to include has been lost.

**Comment by vector-of-bool** [comment]
Hmm... May be trouble with the shell lexing. I can add a test case for this. I'm guessing it is because the double-quote appears attached to the preceding `-I`.

**Comment by Zingam** [comment]
And on Linux too!

**Comment by john-mullins** [comment]
You just need to have spaces in your pathnames and you get the same error regardless of platform. Windows manages this by using the short (8.3) pathnames that do not contain spaces.

**Comment by vector-of-bool** [comment]
Sorry to everyone who has run into this. I have a pending fix for the 1.1.2 release.
