### ISSUE TITLE
Switch the generator

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#51]
I'm not sure that is a bug and even that I can reproduce this each time 
but I see this from time to time, this is related with a command : "Delete Cached settings and reconfigure".

I don't specify the generator explicitly  (by the way - how to do this?), and for my environment (Win10/VC) nmake is in use. however, if I'm performing the command above, VisualStudio/MSBuild generator is in use then.

**Comment by vector-of-bool** [comment]
The reason is that the NMake generator is preferred if no generator is specified. There are values in ``settings.json`` you can use to control what generator the extension will use when you configure.

**Comment by amigo421** [comment]
but problem is still there, I don't understand why already built project after the cache deletion, switched to msbuild.. it 'is not built in my case, a lot of msbuild specifics required. e.g. it tries to build win32 by default (instead of required x64)

**Comment by vector-of-bool** [comment]
Oh oh. I think I know what is happening here. The issue seems to be that I don't set the ``-G`` option when I do the clean reconfigure. That would make CMake fallback to its own logic regarding how a generator is selected. This is a bug.

**Comment by amigo421** [comment]
@vector-of-bool just one more question out this scope:
how do you use vscode daily as c++ developer?
I'm newbie here, and still didn't find useful way to embed linters/static analyzers, don't see refactoring features, etc. at the office, I'm working in CLion, I can't find in vscode even basic features like a renaming symbols in a files or files itselves (I mean - with a scanning a dependencies)

**Comment by vector-of-bool** [comment]
It mostly boils down to a lack of good extensions. In my case, I just work without some of the nicer refactoring features that might be present in other editors. I'm hoping someone will make a better extension for C++ language support than what we currently have, as I find them severely lacking compared to what is already available for other languages. It's not so much a technical problem either, but  simply that no one has bothered to implement such an extension yet. I am hoping to build such an extension based on Clang, but it's still a long way from usable.

**Comment by amigo421** [comment]
thank you. 
I see many other extensions (for languages) are more advanced

**Comment by bbosnjak** [comment]
I had same problem. It also occurs when configuring other build (for example Release after Debug) without closing vscode.
Problem is that cmakeCache is not properly "reloaded" - Release build use Debug cache and pickGenerator is not executed.

I fix it. I would like to contribute change.

**Comment by vector-of-bool** [comment]
@bbosnjak, you've got a fix? Create a pull request: contributions are always welcome! I wasn't able to get to fixing this one today, so any help would be very appreciated.
