### ISSUE TITLE
Cmake generator Visual Studio 2017 Win64 not found.

### ISSUE THREAD

**Issue by jaques-sam** [vector-of-bool/vscode-cmake-tools#519]
### Brief Issue Summary

Visual Studio 2017 not found by Cmake.
Visual Studio 2015 was uninstalled before installing Visual Studio Professional 2017 (with C++ development & cmake files selected!).
Afterwards I got the message "couldn't find any instance of Visual Studio"

### Apparent Behavior:

$ cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MODULE_PATH=../devenv/modules ../devenv
CMake Error at CMakeLists.txt:4 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.

### Platform and Versions

[[For issues, fill out the following. Otherwise delete this section.]]

- **Operating System**: Windows 10.0.17134 - AMD64
- **CMake Version**: 3.12.1
- **VSCode Version**: 14.10.25017
- **Compiler/Toolchain**: Visual C++ 2017 Win64

### Other Notes/Information

Solution given in https://github.com/Valloric/YouCompleteMe/issues/2945 did not work for me as C++ development & cmake files were selected during installation!
Also reinstalling Cmake did not work.

**Comment by Randshot** [comment]
What's the output from `vswhere`?

**Comment by jaques-sam** [comment]
Git shell: bash: vswhere: command not found
Cmd: 'vswhere' is not recognized as an internal or external command, operable program or batch file.

**Comment by jaques-sam** [comment]
Thanks for your reaction, after installing vswhere:
$ vswhere
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.8.8.44148]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 5831e9e7
installDate: 21/08/2018 17:12:36
installationName: VisualStudio/15.0.0+26228.49
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
installationVersion: 15.0.26228.49
productId: Microsoft.VisualStudio.Product.Professional
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
displayName: Visual Studio Professional 2017
description: Professional developer tools and services for small teams
channelId: VisualStudio.15.Release
channelPath: C:\Users\samja\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\4CB340F5\install_catalog.json
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
installChannelUri: https://aka.ms/vs/15/release/6309d8f40/channel
properties_campaignId:
properties_channelManifestId:
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

I don't know what happened, I several things: reinstalling cmake, restart pc etc.
Now it works...

**Comment by vector-of-bool** [comment]
Sorry for the delay. This doesn't look to be VSCode or CMake Tools related. It's probable that your Windows simply needed to be restarted for the VS installation to be visible to other tools. Glad to hear that its working!
