### ISSUE TITLE
Auto generated kis clang 6.0 for vs2017 is not so good:(

### ISSUE THREAD

**Issue by lygstate** [vector-of-bool/vscode-cmake-tools#523]
```
  {
    "name": "Clang 6.0.0 for MSVC with Visual Studio Community 2017 (amd64)",
    "visualStudio": "0d8da669",
    "visualStudioArchitecture": "amd64",
    "compilers": {
      "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
    }
  },
```
"visualStudio": "0d8da669", is to werid:)

**Comment by lygstate** [comment]
Want something like this:
cmake -G "Visual Studio 15 2017 Win64" -T v140 .. -DCMAKE_PREFIX_PATH=C:/Qt/Qt5.9.6/5.9.6/msvc2015_64

**Comment by vector-of-bool** [comment]
Sorry for the delay.

I'm somewhat confused on what you are referring to. Is the trouble in the `visualStudio` key? That key is derived from the `instanceId` output from `vswhere`. It used to use the display name for the kit, but it was unreliable when using legacy VS versions.

**Comment by lygstate** [comment]
Can close
