### ISSUE TITLE
Add way to specify CMAKE_GENERATOR_TOOLSET by using option -T

### ISSUE THREAD

**Issue by lygstate** [vector-of-bool/vscode-cmake-tools#524]
https://cmake.org/cmake/help/v3.12/variable/CMAKE_GENERATOR_TOOLSET.html

**Comment by vector-of-bool** [comment]
Sorry for the delay. I've been busy with other projects.

CMake Tools should already support this via the `cmake.toolset` option, or the `toolset` option in a Kit. Do these options support your use case?

**Comment by lygstate** [comment]
not document at https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html

**Comment by lygstate** [comment]
It's already been fixed.
