### ISSUE TITLE
Linux LLDB debugging and documentation could use some love

### ISSUE THREAD

**Issue by chaoticbob** [vector-of-bool/vscode-cmake-tools#541]
I've been using vscode-cmake-tools for about a week now to write a lot of Vulkan graphics code. I think it's a great tool and is providing coverage that is sorely missing in every other IDE that's on Linux. I do have some requests that I think would benefit the vscode-cmake-tools ecosystem as a whole. 

**LLDB debugging**
This feature does not seem to be fully implemented. I tried searching through the issues here, but the discussions are very windy with no conclusions. Currently, from vscode, setting this up seems to launch gdb instead of lldb. Changing the MImode does cause lldb to launch, but it doesn't seem usable. 

Not expecting miracles to make LLDB work, but it would be nice if there was some clear documentation around to save one some time messing around with it. 

**Documentation**
There are several areas of the documentation that are gaps. One example is the debugging sections. It's not clear, nor are examples provided on how to set an environment variable for launching a debug session. The syntax in vscode-cmake-tools shares DNA with JSON and CMAKE. Which isn't really a problem, but it would save a lot of time if there were examples. 

In my case, vscode-cmake-tools is sufficient for basic debugging. But as debugging cases become more complex, one often has to fallback to command line gdb. Again, some of this is just due to lack of documentation. 

**Other**
Might be also useful to provide build/install instructions for vscode-cmake-tools. Could possibly increase the likelihood of PRs.

Thanks!

**Comment by chaoticbob** [comment]
Thank you for the response.  I've been all over the docs on github.io this weekend :)

The bit that I was referring to in my example was `environment` in the `launch.json` - and I realize this may be out of vscode-cmake-tools' purview. It took me a long longer than I want to admit to track down the formatting for `environment`:
```
"environment": [{"name" : "VULKAN_SDK", "value" : "$HOME/local/vulkan"}],
```
I'm not 100% sure it's correct, but it seems to be doing the right thing. 

My suggestion is if something like that showed up in the docs, it would make getting up and going with vscode-cmake-tools a tad easier.

**Comment by vector-of-bool** [comment]
I'll update the docs for 1.1.2
