### ISSUE TITLE
Improve diagnostic parsing

### ISSUE THREAD

**Issue by bbosnjak** [vector-of-bool/vscode-cmake-tools#55]
I am using embedded MCU compiler in automotive business. We use subset of C defined by MISRA standard. MISRA compatible compilers produce much more warnings than PC world compilers (gcc for example). Some things can not be made MISRA compatible like MCU register description and they reproduce lots of warnings.
In project with I am testing this extension we have 'h' file defining MCU registers and producing around 10 thousands warnings (worst case). This file is included (indirectly) in every 'c' file. Compiler produce this 10 thousands warnings when compiling each 'c' file. Our project is small, around 50 'c' files implementing only MCU drivers, and when compiling with this extension vscode hangs.
Using vscode task with problemMatcher to run cmake build works, quite slow, but no hang.

**Comment by bbosnjak** [comment]
Current implementation to collect complete cmake out (stout and stderr) and parse diagnostic is quite bad for extreme use cases.
I volunteer to improve this, but maybe somebody need to polish my work (my goal is to get my project compile)

**Comment by vector-of-bool** [comment]
Contributions are very welcome!

This is an interesting problem to solve... Currently, all output is accumulated in a single string and is parsed after the build stops. Some kind of incremental parsing and diagnostic deduplication would be necessary. If you make a pull request, I'll gladly help polish it for inclusion in a future release!

**Comment by bbosnjak** [comment]
I did some more testing. Hang happens when sending data to OutputChannel. There is also vcode issue for this: https://github.com/Microsoft/vscode/issues/12265

**Comment by vector-of-bool** [comment]
I can't see a reasonable way for me to fix this until that bug is fixed. I think I'll close this until I see a fix on that one, then I'll review this issue.

**Comment by bbosnjak** [comment]
You can check fix for OutputChannel hangup at:
https://github.com/bbosnjak/vscode-cmake-tools/tree/bugfix/OutputChannel_hangup
