### ISSUE TITLE
Request: add build dir prefix support to CMake Variants

### ISSUE THREAD

**Issue by DexterMagnific** [vector-of-bool/vscode-cmake-tools#553]
### Add ability to build variants in custom dirs

Currently, the CMake Variants concept supports the `buildType` option which it passes to CMake through `CMAKE_BUILD_TYPE` variable. This is fine.

It also allows to set other variants but unfortunately they cannot be built in separate dirs. This makes switching between variants painful since a rebuild is necessary.

If I add another `buildType` entry, it overwrites the previous one instead of accumulating it.

What I would suggest is to add a `buildDir` variable to accumulate these into a directory structure. The difference between `buildDir` and `buildType` is that the former is not passed to `CMAKE_BUILD_TYPE`.

Example:

```
buildType:
  default: release
  description: The build type
  choices:
    release:
      short: Release
      long: Combined libs and stripped binaries
      buildType: Release
    debug:
      short: Debug
      long: Debugging symbols and no optimization
      buildType: Debug

audioConfig:
  default: unspecified
  choices:
    unspecified:
      short: Unspecified
      long: No particular audio config
      settings:
        AUDIO_CONFIG: UNSPECIFIED
    quali:
      short: QUALI
      long: Qualitative
      buildType: QUALI
      settings:
        AUDIO_CONFIG: QUALI
    inter:
      short: INTER
      long: Intermediate
      buildType: INTER
      settings:
        AUDIO_CONFIG: INTER
    premium:
      short: PREMIUM
      long: Premium
      buildType: PREMIUM
      settings:
        AUDIO_CONFIG: PREMIUM
```

I would like a build directory like `Release/PREMIUM` if I select 'Release + PREMIUM` as a variant. The build type would stay `Release` and now I have my variant in its own dir.

### Platform and Versions

- **Operating System**: Linux
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.27.2
- **CMake Tools Extension Version**: 1.1.2
- **Compiler/Toolchain**: GCC 7.3.0

### Other Notes/Information

Thank you for this fantastic extension.

**Comment by vector-of-bool** [comment]
Hello! Sorry to take so long to get back to you. Does [this substitution](https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#variant-substitution) support your use case?

**Comment by DexterMagnific** [comment]
Fantastic this is exactly what I need. Thank you very much for this.
