### ISSUE TITLE
Laster Version is causing configuration to hang

### ISSUE THREAD

**Issue by john3-16** [vector-of-bool/vscode-cmake-tools#56]
Clicking stop will not stop it. Going back to previous version.

**Comment by vector-of-bool** [comment]
That's no good... I happen to be in a good position to do a hotfix. Could I get some more information?

**Comment by john3-16** [comment]
previous to 0.6.1 it would some bunch of messages when doing configuring.  Now run the configuring it hangs with about 3 lines of messages.  Is there a way to debug it don't mind helping you.

**Comment by vector-of-bool** [comment]
What lines of output are you able to see before it hangs?

**Comment by john3-16** [comment]
reinstalled currently on the status bar it says CMake: Unconfigured: RelWithDebInfo: Ready

**Comment by vector-of-bool** [comment]
What platform are you on?

**Comment by john3-16** [comment]
OS/X 10.11.6 on MacBook Pro

**Comment by john3-16** [comment]
Anyway to go back previous version which I had problems with it.

**Comment by john3-16** [comment]
Also can't see what its doing CPU is normal.

**Comment by john3-16** [comment]
Now I'm using Visual Studio Code and have 2nd one open as well, its status says Unconfigured Refreshing targets its open a different folder.

**Comment by vector-of-bool** [comment]
I'm starting a hotfix branch 0.6.2. I've identified a serious potential issue, which may or may not be the issue you are seeing. Environment variables are not being passed correctly.

**Comment by john3-16** [comment]
The Stop button is doesn't do anything by the way.

**Comment by vector-of-bool** [comment]
Just published hotfix for 0.6.2. Give it a try and see if it fixes the issue.

**Comment by john3-16** [comment]
not hanging now

**Comment by john3-16** [comment]
working again like 0.6.0

**Comment by vector-of-bool** [comment]
Excellent. Thanks for bringing this to my attention: I was about to go offline for the next day or two!
