### ISSUE TITLE
Hide output window

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/vscode-cmake-tools#560]
Currently, whenever CMakeTools runs a command with output, the Output window comes into focus. However, most of the time, I'm not actually interested in the outputted information. I'd love to have an option to hide the Output window by default, allowing me to manually open it if I do want to see the output.

Essentially, I'm asking for control over the [output behavior](https://code.visualstudio.com/docs/editor/tasks#_output-behavior) (or equivalent) of the tasks.

**Comment by KoeMai** [comment]
Does you still miss this feature in version 1.1.3?

**Comment by Quincunx271** [comment]
@KoeMai I didn't realize this feature was implemented. It is indeed addressed by #590 . The option could use some documentation, though.
