### ISSUE TITLE
Running an executable on Windows Powershell through the sidebar doesn't run the executable.

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/vscode-cmake-tools#562]
### Brief Issue Summary

Building and running an executable from the CMakeTools sidebar (right click > Run in terminal) fails in Windows Powershell because the executable is quoted. After building, CMakeTools opened the terminal and I saw the following:

```powershell
PS C:\...> "C:\...\tests.exe"
C:\...\tests.exe
PS C:\...>
```

### Expected:

Actually runs the executable.

### Apparent Behavior:

Simple evaluates the string

### Other Notes/Information

Powershell evaluates quoted commands as "just evaluate and print this string." I believe the intent of the quotes is to handle spaces in filenames. I'm not 100% sure, but I believe ``\``-escaped spaces is the way to go here.

**Comment by vector-of-bool** [comment]
I can't reliably determine what shell is going to start up. I could inspect the user's `settings.json`, but that sounds very error-prone. I'm thinking of just forcing the startup shell to be `cmd.exe`
