### ISSUE TITLE
Allow project relative path for cmake.cmakePath

### ISSUE THREAD

**Issue by Farigh** [vector-of-bool/vscode-cmake-tools#569]
### Brief Issue Summary

The `cmake-kits.json` file property `cmake.cmakePath` expects the binary fullpath. Passing a relative path results in an error message 
```
Bad CMake executable "<path>". Is it installed or settings contain the correct Path (cmake.cmakePath)?
```

### Expected:

I'd like to be able to specify a relative path (to the cmake-kits.json file or the ${workspaceRoot})

### Some context
Our project deploys the CMake and Make binaries via packages within our project directory

**Comment by vector-of-bool** [comment]
`cmake-kits.json` doesn't have a `cmakePath` property. Are you referring to `cmake.cmakePath` in `settings.json`?

It's a simple modification to get a relative path to resolve relative to the workspace folder directory.
