### ISSUE TITLE
Problem in determination of available CPU cores

### ISSUE THREAD

**Issue by Barben360** [vector-of-bool/vscode-cmake-tools#578]
### Brief Issue Summary

The automatic CPU core number detection in CMake Tools seems broken

### Expected:

With an 4-core-8-threads-CPU:

1. Set `"cmake.parallelJobs": 0` or/and `"cmake.ctest.parallelJobs": 0` for automatic 
2. Configure, build, run tests
3. Build and tests append `-j 10` while `-j 8` (or even `-j 7`) should be expected (I think).

### Platform and Versions

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.28.2
- **CMake Tools Extension Version**: 1.1.2
- **Compiler/Toolchain**: GCC 7.3

### Other Notes/Information

Tested with i7-6700K and i7-8550U with the exact same other conditions.

**Comment by lflserg** [comment]
Agree my virtual box has only 4 cores assigned but got -j6

**Comment by Barben360** [comment]
This seems actually normal, I read that in general it is advised to assign 1.5x your number of cores (I guess this is a statistical law which says this is faster).

**Comment by vector-of-bool** [comment]
Sorry that I let this sit for a while. CMake borrows this heuristic from Ninja, which runs `-j (number-of-cores + 2)`. The general idea is to have the additional jobs busy on the CPU while some jobs are stuck waiting on the disk, leading to better hardware utilization than `-j (number-of-cores)`.
