### ISSUE TITLE
Allow running configure before build

### ISSUE THREAD

**Issue by iThinker** [vector-of-bool/vscode-cmake-tools#585]
CMake only re-configures projects if cmake files change. But in generic setups sources may change and not cmake files, so re-configuration is needed before build.
It might be expressed as an opt-in setting same way as "build before run" is expressed.

**Comment by iThinker** [comment]
I have 2 cases when I need it:
1. As part of CMake build system generation happens source generation from the IDL. Unfortunately, I cannot make generation as part of the build itself, so before the build, I have to run configuration to get new sources generated if I changed IDL.
2. In my `Sources.cmake` I gather sources with `GLOB_RECURSE` and use the filesystem as a project structure. But when I add or remove files, build system generated by CMake does not pick up those changes. Which leads again to a requirement of triggering CMake configuration before a build.

So instead of manually configuring CMake every time before a build would be nice to have it automated.
Thanks in advance.

**Comment by vector-of-bool** [comment]
Good news! Both of these use cases are supported by CMake itself:

1. You need to notify CMake that "configure depends" on some additional files. You do this with a `set_property()` call:

    ```cmake
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS some_file_1.idl some_file_2.idl ...)
    ```

    CMake will add rules to the build system to re-run the configure process when any of the listed files are changed.

2. You can cause CMake to re-run configure based on the result of a globbing expression. As part of `file(GLOB_RECURSE ...)` add the `CONFIGURE_DEPENDS` argument. [Take a look here](https://cmake.org/cmake/help/latest/command/file.html#filesystem). This will require a more recent version of CMake to run though, and does not work with MSBuild (the "Visual Studio" generators).

**Comment by iThinker** [comment]
Great! Thank you for the reply. I will check and close the issue if it is invalid.

**Comment by iThinker** [comment]
I did not have a chance to validate the solution yet, but presumably, it is what I need. Thanks again.
