### ISSUE TITLE
The ci are failed, make me hard to update pull request

### ISSUE THREAD

**Issue by lygstate** [vector-of-bool/vscode-cmake-tools#592]
### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by vector-of-bool** [comment]
I'm working on solving some CI issues at the moment. Keep an eye out.

**Comment by vector-of-bool** [comment]
Should be fixed now

**Comment by lygstate** [comment]
@vector-of-bool Appveyor still failed:(
