### ISSUE TITLE
cannot execute command

### ISSUE THREAD

**Issue by kie4280** [vector-of-bool/vscode-cmake-tools#601]
Issue Type: <b>Bug</b>

cmake tools cannot execute  "CMake:Execute current target without debugger"
It always return :
The terminal process command 'C:/Windows/System32/cmd.exe' failed to launch (exit code: 1)
It also created  .exe directory in the base folder

Extension version: 1.1.3
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (4.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Clocktown** [comment]
I am able to reproduce this. It was working fine until a few days ago and today I suddenly encountered the same problem.

**Comment by momentum-games** [comment]
I am also able to reproduce this.
Seems the update broke something.

**Comment by FelikZ** [comment]
It is not released yet, right?

**Comment by RisingOrange** [comment]
I'm on version 1.1.3 and still encountered the smae problem.

**Comment by SuperWig** [comment]
Because 1.1.3 is from November and that was merged a month ago.

**Comment by Jonas1312** [comment]
Same error, that would be nice to release version 1.1.4 with #616
