### ISSUE TITLE
Simple question, how does one configure cmake tools to build + debug when I hit f5?

### ISSUE THREAD

**Issue by JasonDictos** [vector-of-bool/vscode-cmake-tools#609]
I've yet to find an answer, try as I might to search on this very basic request.

Just want to hit f5, have it build the current default target, then run the debugger. 

Must be doable, just lost in these configs.

**Comment by HorstBaerbel** [comment]
Make sure you have a recent version ans selected the correct target to build and to launch. According to the docs, it SHOULD [build before run by default now](https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#cmake-buildbeforerun).
If you have a reason it does not work (custom targets, whatnot), here's a workaroundlution. Create a tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "cmake --build ${cmake.buildDirectory} --config Debug --target TARGET_TO_BUILD -- -j 4",
            "options": {
                "cwd": "${cmake.buildDirectory}"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
    ]
}
```
Note _"cwd": "${cmake.buildDirectory}"_ does not work currently. Use _"cwd": "${workspaceFolder}/build"_ (the default) there until it works. For _TARGET_TO_BUILD_ you should ideally use _${command:cmake.launchTargetPath}_ which should build the target selected to launch.
Create a launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run target",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${command:cmake.launchTargetPath}",
            "cwd": "${workspaceFolder}/build"
         }
    ]
}
```

**Comment by JasonDictos** [comment]
Thank you, much appreciated!

**Comment by Akselmo** [comment]
Hi, I'm pretty new using Github so forgive me if I'm doing something wrong when replying to old issue..

Anyway, you can also add `tasks.json` with this:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "{cmake.debugTarget}",
            "options": {
                "cwd": "${workspaceFolder}/build"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
    ]
}
```

Then use the `launch.json` mentioned earlier. This is basically same thing as pressing the little debug button in the status bar, but replaces the F5 button with it.

Hopefully this helps someone!

**Comment by bobbrow** [comment]
That's pretty clever to launch our command directly in a task, but it won't allow you to pass arguments to the target.  Our documentation for debugging with `launch.json` [is here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md#debug-using-a-launchjson-file) and is the preferred approach since there are more ways to configure it.

**Comment by Marr11317** [comment]
The link seems dead unfortunately

**Comment by Marr11317** [comment]
Seems like it moved [here](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md)

**Comment by bobbrow** [comment]
Thanks. I updated my previous comment to fix the link too.  We changed our development process and that branch doesn't exist anymore.
