### ISSUE TITLE
Add system specific "cmake.buildDirectory"

### ISSUE THREAD

**Issue by filipsky** [vector-of-bool/vscode-cmake-tools#62]
Hi,
thanks for your plugin, it works great.

In our build scenario it would be great to be able to configure the cmake build directory per system.

any of 
`"cmake.buildDirectory.<system>": "..."`

or 

```
"<system>": {
    "cmake.buildDirectory": "..."
}
```

will help us a lot.

Thanks, Honza

**Comment by vector-of-bool** [comment]
Sounds reasonable.

**Comment by filipsky** [comment]
Thanks :)
We are looking for some future update then

Honza

**Comment by vector-of-bool** [comment]
Sorry for the delay! This will be easy to implement it but I forgot about it for the latest patch release. I haven't forgotten!

**Comment by filipsky** [comment]
Thanks for your message.
Tbh: I was quite surprised that the vscode itself does not do the variable
substitution and the os specific config branches.

We are looking forward to the update, it will enable us to submit the whole
project including the settings.json to the source control (now we have to
use a bit different settings on each platform)

Dne 6. 11. 2016 4:05 napsal uživatel "vector-of-bool" <
notifications@github.com>:

**Comment by vector-of-bool** [comment]
This should be available in the latest `0.7.3` release, as `cmake.<system>.buildDirectory`. Give it a try, and if it works to your satisfaction, close this issue.

Thanks for the suggestion!

**Comment by filipsky** [comment]
Thanks a lot. I will try the new version as soon as it is out, the version I can see now is 0.7.2

**Comment by vector-of-bool** [comment]
Uggh, I must have failed to check the output of `vsce publish` correctly. I was certain I just pushed out the `0.7.3` release. I'll get to it later today.

**Comment by vector-of-bool** [comment]
Should be released for real now

**Comment by filipsky** [comment]
Great,
works as expected.

thanks a lot, this extension is very useful for us
