### ISSUE TITLE
MinGW make parallel build is broken

### ISSUE THREAD

**Issue by bbosnjak** [vector-of-bool/vscode-cmake-tools#65]
MinGW make parallel builds in (last) version 3.82.90 are broken. Error output is scrambled (output from two files are mixed together) and there is no "-O" option as in original gmake.
As such MinGW make is not usable to parse build errors and use "-j" option. vscode-cmake-tools automatically set "-j". It would be better to leave this decision to developer (set  "-j" in buildToolArgs).

**Comment by vector-of-bool** [comment]
Hmm... That's problematic. Unfortunately, I'm not sure if I could make this change without users noticing that their builds have slowed down by default.

There is an existing configuration option `cmake.parallelJobs` which sets the `-j` option for the build tool, which may be a reasonable alternative. The default value `0` tells CMake Tools to automatically detect how many jobs to pass to the build tool. Setting it to `1` may fix your issue, but I don't think I'd like to make that the default for all users. Maybe I'll ask for some feedback and see what others say.

# Feedback wanted:
### Should the default value for `cmake.parallelJobs` be changed?

**Comment by danme** [comment]
👎

**Comment by spinicist** [comment]
I like the current setting - is leaving a big warning in the documentation for MinGW users sufficient?

**Comment by bbosnjak** [comment]
I am happy with cmake.parallelJobs: 1
