### ISSUE TITLE
CUDA kit not being forwarded to cmake

### ISSUE THREAD

**Issue by LuisAyuso** [vector-of-bool/vscode-cmake-tools#656]
### Brief Issue Summary

When using native CUDA support in cmake, CUDACXX environment variable can be used to point out the toolchain location.
When adding  CUDACXX to an exisiting kit, it is not forwarded to cmake and therefore ignored.

```
  {
    "name": "GCC 7.3.0",
    "compilers": {
      "C": "/usr/bin/gcc-7",
      "CXX": "/usr/bin/g++-7",
      "CUDACXX": "/usr/local/cuda-10.1/bin/nvcc"
    }
  },
```

### Expected:

1. add complete kit to ```cmake-tools-kits.json```
2. cmake detects compiler as if it was invoked from terminal or cmake-gui

### Apparent Behavior:

1. add complete kit to ```cmake-tools-kits.json```
2. CMake reports error
```
[cmake] CMake Error at /opt/cmake/share/cmake-3.13/Modules/CMakeDetermineCUDACompiler.cmake:25 (message):
[cmake]   Could not find compiler set in environment variable CUDACXX:
[cmake] 
[cmake]   CMAKE_CUDA_COMPILER-NOTFOUND.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:3 (project)
```

### CMake Tools Log

```
[cmake] CMake Error at /opt/cmake/share/cmake-3.13/Modules/CMakeDetermineCUDACompiler.cmake:25 (message):
[cmake]   Could not find compiler set in environment variable CUDACXX:
[cmake] 
[cmake]   CMAKE_CUDA_COMPILER-NOTFOUND.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:3 (project)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "/home/luis/code/microscope/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/luis/code/microscope/build/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.
[main] Failed to prepare executable target with name 'undefined'

```

### Platform and Versions

- **Operating System**: ubuntu 18.04
- **CMake Version**: 3.13
- **VSCode Version**: 1.31.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: gcc-7, cuda xxxx

**Comment by dcourtois** [comment]
Hi,

This is not how kits work. See https://vector-of-bool.github.io/docs/vscode-cmake-tools/configuring.html#configuring-how

Here the relevant part:

> For Compilers, CMake Tools sets the CMAKE_<LANG>_COMPILER cache variable to point to the path for each <LANG> defined in the kit.

So if you want `CMAKE_CUDA_COMPILER` to be defined, you should write `"CUDA": "/usr/local/cuda-10.1/bin/nvcc"` in the `compilers` field of your kit (you used `CUDAXX`, so ...)

Check if it works, and if it does, you can close the issue :)

**Comment by LuisAyuso** [comment]
hi there,

The solution you propose is not working neither, that was my first attempt:
If you look at the original post, cmake propose CUDACXX as the environment variable  for toolkits, just like CC for c or CXX for c++.
``` Could not find compiler set in environment variable CUDACXX:```
(why they do not use just  CUDA is a mistery to me... )

how are this variables forwarded into cmake? what is the magic that forwards kits into cmake? if you point me out into the code maybe I can find out that can we do there.
cheers,

**Comment by dcourtois** [comment]
Hi,

It does work, but it probably depends on how you're using CUDA in your project.
Here is a minimal example of a CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.10)
project(testcuda)
# this is the way to use CUDA since CMake version 3.10
# See https://cmake.org/cmake/help/v3.10/module/FindCUDA.html
enable_language(CUDA)
add_executable(testcuda main.cpp test.cu)
```

and my kit (I'm on Windows, but it should work the same on other platforms:

```
{
    "name": "Clang - CUDA",
    "visualStudio": "VisualStudio.15.0",
    "visualStudioArchitecture": "amd64",
    "compilers": {
        "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
        "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
        "CUDA": "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe"
    }
}
```

My guess is that you're using the old way of enabling CUDA in your CMake script. Since your system has CMake 3.13 installed, I strongly advise to switch to the new way. It's far simpler (just enable the language) and will solve your problem.

If you can't for some reasons, then you can customize your kit. See https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html#kits It explains in detail how kits work. At the end of the page, you have 2 options that might interest you: `cmakeSettings` and `environmentVariables`

**Comment by LuisAyuso** [comment]
I have always been using the "new way" although is not feature complete and can not replace some things find_cuda could do. 

your test works just as described, the error must be somewhere in my cmake stuff.. but is not trivial as there are quite some modules in here.

thanks for you time.
