### ISSUE TITLE
Targets are always launched using cmd.exe on Windows.

### ISSUE THREAD

**Issue by hudsonmiranda291** [vector-of-bool/vscode-cmake-tools#659]
### Brief Issue Summary
 
When the default integrated terminal on Windows is set to Powershell, the extesion uses cmd.exe despite the default choice to launch a target.

### Expected:

1. Click on CMake extension button on left-side bar;
2. Right-click a target;
3. Choose "Run in terminal";
4. The extension calls the target using the default terminal set by terminal.integrated.shell.windows".

### Apparent Behavior:

1. Click on CMake extension button on left-side bar;
2. Right-click a target;
3. Choose "Run in terminal";
4. The extension calls the target using cmd.exe always.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.11.1
- **VSCode Version**: 1.32.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017

### Other Notes/Information

The cmd.exe is hardcoded on line 1089 of vscode-cmake-tools/src/cmake-tools.ts but I don't know how to properly fix it.

**Comment by iamtangxin** [comment]
yes, that's what I want to say! 
when I "Execute the current target without a debugger" on windows, I got a error message:
 "The terminal process command 'C:/Windows/System32/cmd.exe' failed to launch (exit code: 1)"
but I have already configed like this : 
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"

**Comment by Randshot** [comment]
@iamtangxin @hudsonmiranda291 A fix for this already got committed and should be part of the next release.
