### ISSUE TITLE
Unable to determine which CMake generator to use

### ISSUE THREAD

**Issue by smfelsher** [vector-of-bool/vscode-cmake-tools#660]
### Brief Issue Summary

Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json or your Kit configuration.

### Platform and Versions

- **Operating System**: Linux Mint 18.3/Ubuntu 16.04.1 (Linux x64 4.15.0-46-generic)
- **CMake Version**: 3.13.4
- **VSCode Version**: 1.32.3
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: nios2-elf-g++ (Altera 16.1 Build 196) 5.3.0

### Other Notes/Information

I have a CMake toolchain file, `gcc_nios.cmake`:

```
#
# A toolchain file to cross-compile for the Nios II processor.
#

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR nios)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_C_COMPILER nios2-elf-gcc)
set(CMAKE_CXX_COMPILER nios2-elf-g++)
set(CMAKE_ASM_COMPILER nios2-elf-gcc)
set(CMAKE_SIZE nios2-elf-size)

set(CMAKE_C_FLAGS_INIT "-mno-hw-div -mhw-mul -mno-hw-mulx -mgpopt=global"
    CACHE STRING "Altera Nios C flags")

set(CMAKE_CXX_FLAGS_INIT "-mno-hw-div -mhw-mul -mno-hw-mulx -mgpopt=global"
    CACHE STRING "Altera Nios C++ flags")

set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--gc-sections" CACHE STRING "Altera Nios Linker flags")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
I created `cmake-kits.json` file:
```
[
   {
      "name": "GCC for Nios II",
      "toolchainFile": "../cmake/toolchain/gcc_nios.cmake",
      "environmentVariables": {
         "PATH": "/home/steve/intelFPGA_lite/16.1/nios2eds/bin/gnu/H-x86_64-pc-linux-gnu/bin:/home/steve/intelFPGA_lite/16.1/nios2eds/sdk2/bin:/home/steve/intelFPGA_lite/16.1/nios2eds/bin:$PATH"
      },
      "preferredGenerator": {
         "name": "Unix Makefiles"
      }
   }
]
```
When I use the CMake Tools extension to configure my project, I am presented with the error message presented above.

**Comment by zt-luo** [comment]
also have this problems

**Comment by KoeMai** [comment]
Hey could you provide use a logfile. This would help to see more Details.

https://vector-of-bool.github.io/docs/vscode-cmake-tools/troubleshooting.html#checking-the-log-file

**Comment by smfelsher** [comment]
I no longer have the plugin installed.
