### ISSUE TITLE
How to cross compile using GNU GCC

### ISSUE THREAD

**Issue by dvescovi1** [vector-of-bool/vscode-cmake-tools#662]
### Brief Issue Summary

Can't configure GCC ARM cross compile tools under windows.

My cmake-tools-kits.json shows this:
 … {
    "name": "GCC for arm-none-eabi 8.2.1",
    "compilers": {
      "C": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\8 2018-q4-major\\bin\\arm-none-eabi-gcc.exe",
      "CXX": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\8 2018-q4-major\\bin\\arm-none-eabi-g++.exe"
    }
  },
  ...
So scanner picked it up.

### Expected:

support GCC ARM cross compile tool chain  … windows version

### Apparent Behavior:

errors

### CMake Tools Log

[cmake] The C compiler identification is GNU 8.2.1
[cmake] The CXX compiler identification is GNU 8.2.1
[cmake] Check for working C compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe
[cmake] Check for working C compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe -- broken
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "C:/Program Files (x86)/GNU Tools ARM Embedded/8 2018-q4-major/bin/arm-none-eabi-gcc.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: c:/nxp_ws/testws/hello_world8MM/build/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command:"C:/MinGW/bin/mingw32-make.exe" "cmTC_97dba/fast"
[cmake]     C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_97dba.dir\build.make CMakeFiles/cmTC_97dba.dir/build
[cmake]     mingw32-make.exe[1]: Entering directory 'c:/nxp_ws/testws/hello_world8MM/build/CMakeFiles/CMakeTmp'
[cmake]     Building C object CMakeFiles/cmTC_97dba.dir/testCCompiler.c.obj
[cmake]     cd /d C:\nxp_ws\testws\hello_world8MM\build\CMakeFiles\CMakeTmp && C:\PROGRA~2\GNUTOO~1\82018-~1\bin\AR19DD~1.EXE    -o CMakeFiles\cmTC_97dba.dir\testCCompiler.c.obj   -c C:\nxp_ws\testws\hello_world8MM\build\CMakeFiles\CMakeTmp\testCCompiler.c
[cmake]     Linking C executable cmTC_97dba
[cmake]     cd /d C:\nxp_ws\testws\hello_world8MM\build\CMakeFiles\CMakeTmp && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\cmTC_97dba.dir\link.txt --verbose=1
[cmake]     C:\PROGRA~2\GNUTOO~1\82018-~1\bin\AR19DD~1.EXE      CMakeFiles/cmTC_97dba.dir/testCCompiler.c.obj  -o cmTC_97dba 
[cmake]     c:/progra~2/gnutoo~1/82018-~1/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: c:/progra~2/gnutoo~1/82018-~1/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/lib\libc.a(lib_a-exit.o): in function `exit':
[cmake]     exit.c:(.text.exit+0x2c): undefined reference to `_exit'
[cmake]     collect2.exe: error: ld returned 1 exit status
[cmake]     CMakeFiles\cmTC_97dba.dir\build.make:85: recipe for target 'cmTC_97dba' failed
[cmake]     mingw32-make.exe[1]: *** [cmTC_97dba] Error 1
[cmake]     mingw32-make.exe[1]: Leaving directory 'c:/nxp_ws/testws/hello_world8MM/build/CMakeFiles/CMakeTmp'
[cmake]     Makefile:120: recipe for target 'cmTC_97dba/fast' failed
[cmake]     mingw32-make.exe: *** [cmTC_97dba/fast] Error 2
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "c:/nxp_ws/testws/hello_world8MM/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "c:/nxp_ws/testws/hello_world8MM/build/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.
```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**:  Windows 10 64bit. 
- **CMake Version**:  3.13.4 
- **VSCode Version**:  1.32.3. 
- **CMake Tools Extension Version**:  1.1.3 
- **Compiler/Toolchain**:  GCC for arm-none-eabi 8.2.1 

### Other Notes/Information

I installed the windows version the GNU ARM GCC cross tools and also the GNUwin32-make-3.81

I can select the GCC kit and it appears to start but it dies with:
[cmake]     C:\MinGW\bin\ar.exe cr CMakeFiles\cmTC_be28d.dir/objects.a @CMakeFiles\cmTC_be28d.dir\objects1.rsp
[cmake]     C:\PROGRA~2\GNUTOO~1\82018-~1\bin\AR19DD~1.EXE      -Wl,--whole-archive CMakeFiles\cmTC_be28d.dir/objects.a -Wl,--no-whole-archive  -o cmTC_be28d.exe -Wl,--out-implib,libcmTC_be28d.dll.a -Wl,--major-image-version,0,--minor-image-version,0 
[cmake]     c:/progra~2/gnutoo~1/82018-~1/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: unrecognized option '--major-image-version'
[cmake]     c:/progra~2/gnutoo~1/82018-~1/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: use the --help option for usage information
[cmake]     collect2.exe: error: ld returned 1 exit status

so I then modified the CMakeSystem.cmake from:

set(CMAKE_SYSTEM "Windows-10.0.17763")
set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_VERSION "10.0.17763")
set(CMAKE_SYSTEM_PROCESSOR "AMD64")

set(CMAKE_CROSSCOMPILING "FALSE")

to:
set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "arm")
set(CMAKE_CROSSCOMPILING "TRUE")

and also added local setting.json entry:
{
     "cmake.generator": "MinGW Makefiles"
}

This got me a little further. 
But now it seems to fail on the linker when running the test compile:
[cmake]     Linking C executable cmTC_97dba
[cmake]     cd /d C:\nxp_ws\testws\hello_world8MM\build\CMakeFiles\CMakeTmp && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\cmTC_97dba.dir\link.txt --verbose=1
[cmake]     C:\PROGRA~2\GNUTOO~1\82018-~1\bin\AR19DD~1.EXE      CMakeFiles/cmTC_97dba.dir/testCCompiler.c.obj  -o cmTC_97dba 
[cmake]     c:/progra~2/gnutoo~1/82018-~1/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: c:/progra~2/gnutoo~1/82018-~1/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/lib\libc.a(lib_a-exit.o): in function `exit':
[cmake]     exit.c:(.text.exit+0x2c): undefined reference to `_exit'
[cmake]     collect2.exe: error: ld returned 1 exit status

From what I saw on Google if you pass "--spec=nosys.spec" as a linker parameter you might be able to fix this error. 
I do not see anyway configure this linker option in cmake tools.

I feel I am close but just can't get it over the finish line.

Am I missing something?
Is there a better way to configure GCC ARM cross tools under windows?

**Comment by adigie** [comment]
You are missing `set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)` in your toolchain file. This tells CMake to build static library when testing compiler, so it will skip linking step.

I recently created template for STM32 and CMake, you can find it [here](https://github.com/adigie/stm32-cmake-template/tree/example_l053).

**Comment by dvescovi1** [comment]
fantastic!   Thanks for the quick reply … I'll give it a try.

**Comment by dvescovi1** [comment]
that did it! Thanks!

**Comment by davidbitton** [comment]
> You are missing `set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)` in your toolchain file. This tells CMake to build static library when testing compiler, so it will skip linking step.
> 
> I recently created template for STM32 and CMake, you can find it [here](https://github.com/adigie/stm32-cmake-template/tree/example_l053).

Where is this in your template? I'm a cmake novice; which file does the above go in; `CMakeLists.txt`?

**Comment by edo386** [comment]
> > You are missing `set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)` in your toolchain file. This tells CMake to build static library when testing compiler, so it will skip linking step.
> > I recently created template for STM32 and CMake, you can find it [here](https://github.com/adigie/stm32-cmake-template/tree/example_l053).
> 
> Where is this in your template? I'm a cmake novice; which file does the above go in; `CMakeLists.txt`?

Seems to be at cmake/toolchain.cmake line 8
