### ISSUE TITLE
Cannot debug target

### ISSUE THREAD

**Issue by Thecontrarian** [vector-of-bool/vscode-cmake-tools#67]
MacOS 10.12.1, VSCode 1.7.1, Cmake 3.6.3

when i use CMake: Configure command, i can build my project but i cant run/debug it with the new targetDebugging feature. after looking into it i realized that it is generating a CMakeToolsMeta.in.txt file and when i rename that file to CMakeToolsMeta.txt then vscode can detect my target and it shows up in the debug target list and i can debug it.

ive tried it with both unix makefile and ninja, same outcome.

**Comment by vector-of-bool** [comment]
Can you show the contents of both `CMakeToolsMeta.txt` and `CMakeToolsMeta.in.txt`? The `.in.txt` should have a generator expression of `$<TARGET_FILE:foo>` while the other should have the actual path to the executable in place of the generator expression.

I'm not sure how simply renaming the file to `CMakeToolsMeta.txt` would work. Puzzling.

If you configure your project with `RelWithDebInfo`, `Release`, `MinSizeRel` and `Debug`, deleting the meta file before each configure, does the meta file get generated each time, for only some configurations, or for no configurations?

Also, can I confirm that you are running the configuration using the `CMake: Configure` command inside of Visual Studio Code?

**Comment by Thecontrarian** [comment]
because im renaming it, both the `CMakeToolsMeta.txt` and `CMakeToolsMeta.in.txt` files have the same contents, which is
```
executable;rosebud;$<TARGET_FILE:rosebud>
system;Darwin;x86_64;
```

when i delete both files and then change the configuration to `Debug` it generates both files, `CMakeToolsMeta.txt` with 
```
executable;rosebud;/Users/contrarian/Documents/Play/Rosebud/build/rosebud
system;Darwin;x86_64;
```
and `CMakeToolsMeta.in.txt` with
```
executable;rosebud;$<TARGET_FILE:rosebud>
system;Darwin;x86_64;
```

when i configure it to `RelWithDebInfo`, `Release`, or `MinSizeRel` it only generates the `CMakeToolsMeta.in.txt` with the same contents from before

**Comment by vector-of-bool** [comment]
Confirms my suspicion. I'll get a fix out for this soon.

**Comment by Thecontrarian** [comment]
thanks for the quick response to this issue!

**Comment by vector-of-bool** [comment]
Sure!

Could you confirm that `0.7.2` fixes this issue for you?

**Comment by Thecontrarian** [comment]
yup its fixed!
