### ISSUE TITLE
No line breaks in CTest Results

### ISSUE THREAD

**Issue by s-martin** [vector-of-bool/vscode-cmake-tools#68]
I have no line breaks in the CTest Results window (see attachment).

![scr](https://cloud.githubusercontent.com/assets/6143783/20141327/1dcaf044-a690-11e6-8f1c-f1d0f0c1da1c.png)

This makes it difficult to check the output.

**Comment by vector-of-bool** [comment]
Ew... That's not good. I'll look into it.
