### ISSUE TITLE
[Question] Cygwin supported?

### ISSUE THREAD

**Issue by tan-wei** [vector-of-bool/vscode-cmake-tools#687]
It works well with MSYS2 with MinGW env, does it support Cygwin? If the answer is yes, how? Thanks very much!

**Comment by KoeMai** [comment]
I added `c:\cygwin64\bin` in to windows search path to find `gcc` from cygwin. The scan for kit found the compiler and a build works.
A cmake installation inside of cygwin failed. There was no pipe communication between cmake on cygwin and vscode on windows possible.

**Comment by tan-wei** [comment]
It works when adding the path into `PATH`. I also try to find a solution to make VS Code uses a configurable `PATH` setting, it seems a unsupported feature for now. Thanks for your reply. A workaround now used by me: Write a batch file whose `PATH` including `c:\cygwin64\bin`, and then in the next line call `code`. So I can use VS Code without modifying the global `PATH`. Just a workround.

**Comment by KoeMai** [comment]
It is possible to modify the environment variable inside of the kit file for a kit. But it does not support expansion of the env.path.

**Comment by tan-wei** [comment]
@KoeMai Thanks for your advice. I think my requirement may somehow particular. The `ENV.PATH` is not only for the building process, but also for an extra plugin named `cquery` which is used the parse the source codes. `CMake` can export `compile_commands.json`, and then `cquery` uses the file to parse the source codes. However, the compiler and its DLL dependencies should in `ENV.PATH` so that the parse commands can be done without DLL missing errors. It seems that the environment variable inside of the kit file is just for building process. After I restart `VS Code`, `cquery` will complain DLL missing errors. I think the reason is `cquery` is automatically launched before the launching of `vscode-cmake-tools`. 
So I think a particular `*.bat` file is a better workaround (but really ugly). After searching for information for some days, I think there is no better solution now for `VS Code` in this situation.
