### ISSUE TITLE
Error: spawn ctest ENOENT

### ISSUE THREAD

**Issue by oiltanker** [vector-of-bool/vscode-cmake-tools#701]
# Error
```
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: spawn ctest ENOENT {"folder":{"uri":{"$mid":1,"fsPath":"c:\\<PATH_TO_PROJECT>","_sep":1,"external":"file:///c%3A/<PATH_TO_PROJECT>","path":"/c:/<PATH_TO_PROJECT>","scheme":"file"},"name":"<PROJECT_NAME>","index":0}}
```
# Generator kit
```json
{
  "name": "MinGW-W64 GCC 8.1.0 - 64 bit",
  "compilers": {
    "C": "C:/MinGW-W64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/x86_64-w64-mingw32-gcc-8.1.0.exe",
    "CXX": "C:/MinGW-W64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/x86_64-w64-mingw32-g++.exe"
  },
  "preferredGenerator": {
    "name": "MinGW Makefiles"
  },
  "environmentVariables": {
    "PATH": "%PATH%;C:\\MinGW-W64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin;"
  },
  "cmakeSettings": {
    "CMAKE_CXX_FLAGS": "-m64"
  }
}
```
# Variant
```json
"linkage": "static",
"buildType": "Debug"
```

**Comment by oiltanker** [comment]
Issue temporarily can be fixed by deleting binary folder, but then appears again, when VSCode is reloaded.

**Comment by oiltanker** [comment]
Found the issue. The extension does not expand the PATH variables such as `%PATH%;<CUSTOM_PATHS>`. It all has to be defined before hand.

**Comment by oiltanker** [comment]
A good thing to implement would be to add some expression that would represent an existing environment variable value, in order to allow appending to environment variables that might be subject to change.

**Comment by itbgcthate** [comment]
Same issue, but I'm not sure what you mean by "it all has to be defined before hand". Defined by whom and where? I get the following:

[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: spawn ctest ENOENT {"folder":{"uri":{"$mid":1,
"fsPath":"c:\\Users\\Kevin\\Documents\\Projects\\Embedded\\VSCode\\SmartDoorChimePrototype","_sep":1,
"external":"file:///c%3A/Users/Kevin/Documents/Projects/Embedded/VSCode/SmartDoorChimePrototype",
"path":"/c:/Users/Kevin/Documents/Projects/Embedded/VSCode/SmartDoorChimePrototype","scheme":"file"},
"name":"SmartDoorChimePrototype","index":0}}

It seems to be having a problem with the definition of "external". This is all from the boilerplate generated by CMakeTools during initial setup. Everything configures and builds fine until VSCode is restarted.
