### ISSUE TITLE
Add back option to disable target debugging

### ISSUE THREAD

**Issue by willyd** [vector-of-bool/vscode-cmake-tools#71]
Hi,

First let me thank you for this very nice extension. It integrates with CMake much better than Visual Studio. However, I am having issues with the Target Debugging features, which I have not been able to diagnose completely. Sometimes, I hit F5 and nothing happens. Some other times, something happens but the Debug Output Console does not show up, VSCode still shows the build output. All errors I am seeing might be related to #70 since I am setting the PATH env var so that some DLLs I link against are found. Also, I have a feeling that if I have my own launch.json file CMake Tools somewhat conflicts with this even if I don't include the CMakeToolsHelper cmake module in my CMakeLists.txt. 

Since C++ debugging is not perfectly stable and CMakeTools target debugging is not stable either, I would suggest that you add back the option to disable the debugging feature of CMakeTools while keeping the Configure, Build and other commands available. This way should a problem occur it makes it easier to figure out which extension is responsible for the problem.

How does that sound?

For the record I am using:

- Windows 10
- VSCode 1.7.1
- CMakeTools 0.7.4

**Comment by vector-of-bool** [comment]
CMake Tools will not consider the content of your `launch.json`, and pressing F5 will not launch the target debugger (unless you switched your keybindings). The target debugging command is invoked separately from the `launch.json` and your regular debugging configuration, and shouldn't have any effect on the built-in debugging feature in vscode. Are you sure this is being caused by target debugging?

**Comment by willyd** [comment]
> CMake Tools will not consider the content of your launch.json, and pressing F5 will not launch the target debugger (unless you switched your keybindings). The target debugging command is invoked separately from the launch.json and your regular debugging configuration, and shouldn't have any effect on the built-in debugging feature in vscode

Ok. Is was not obvious.

> Are you sure this is being caused by target debugging?

No I am not but I am finding it very hard to nail down what works and what does not. Sometimes the debugger won't start the process, sometimes it will but it is very hard to understand what is causing this behavior. I guess I will wait for a new version of the cpptools and try again.

Thanks
