### ISSUE TITLE
Warning about using ${buildType} in ${cmake.buildDirectory} endlessly pops up

### ISSUE THREAD

**Issue by willyd** [vector-of-bool/vscode-cmake-tools#72]
This warning

> It is not advised to use ${buildType} in the cmake.buildDirectory settings when the generator supports multiple build configurations.

continuously pops up even though I am using Ninja which DOES NOT support multiple configurations.

**Comment by vector-of-bool** [comment]
That's strange... Could I get some more information about your platform and setup?

**Comment by willyd** [comment]
Windows 10
VSCode 1.7.1
CMakeTools 0.7.4

**Comment by vector-of-bool** [comment]
Do you ever manually do `set(CMAKE_CONFIGURATION_TYPES ...)` in your CMake files? That's the heuristic I'm using to determine if the generator is multi-conf or not, and I'm guessing it is not working very well in this case. I may need to come up with a better way to detect multi-conf generators without just enumerating them all.

**Comment by vector-of-bool** [comment]
Should be fixed in next release

**Comment by vector-of-bool** [comment]
Close this issue if the `0.7.5` release fixes this for you. Thanks!

**Comment by willyd** [comment]
Yes it does thansks!
