### ISSUE TITLE
Run Tests more configurable

### ISSUE THREAD

**Issue by s-martin** [vector-of-bool/vscode-cmake-tools#74]
I use heavily the Run Tests option.

I would like to be able to run only a subset of my tests. Therefor I would need an CTest option, which is more configurable (e.g. to pass "-R MYTESTSUITE1" to my test framework).

Something similar to "Build a target" would be useful.

**Comment by vector-of-bool** [comment]
There's now an option to set CTest command line arguments. I think I may also add the ability to run a test by name in the future, but not yet.

**Comment by s-martin** [comment]
As #79 was fixed, I was now able to test it.

Works fine for me, thanks!
