### ISSUE TITLE
Better errors when CMake isn't installed.

### ISSUE THREAD

**Issue by Lillecarl** [vector-of-bool/vscode-cmake-tools#76]
I uninstalled all my MacPorts going over to Brew, and forgot to reinstall CMake, took awhile before I figured out that I didn't have CMake CLI tools available when restarting VS Code, this could be improved! :)

**Comment by vector-of-bool** [comment]
Bad error messages count as bugs.

**Comment by vector-of-bool** [comment]
Should have a more helpful message with `0.8.0`. Thanks!
