### ISSUE TITLE
Unable to compile simple test program

### ISSUE THREAD

**Issue by Schroedingers-Cat** [vector-of-bool/vscode-cmake-tools#80]
I'm using Visual Studio Code 1.7.1 with the following extensions:
* C/C++
* CMake
* CMake Tools

I have installed visualcppbuildtools_full as instruected by the C/C++ extension. I had some issues using the CMake extension first, because the following paths had to be placed into system variables:
> Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64

> Lib=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64;C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64

> INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include

Otherwise, some lib files were missing. You should either add this to the doc or add it to the extensions setup routine.

However, having fixed all these problems, cmake is still unable to compile it's test program. This is the cmake output from VSC:
http://pastebin.com/pQgBzehG

And this the CMakeOutput.log:
http://pastebin.com/nRcdcuh6

And this is the CMakeError.log
http://pastebin.com/Wb176ssi

I'm out of ideas.

**Comment by Schroedingers-Cat** [comment]
After installing the full Visual Studio Community 2015 I can add a build environment in VSC. However, starting a build fails with:
> -- Building for: Visual Studio 14 2015
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:2 (project):
>   No CMAKE_C_COMPILER could be found.

Checking the error.log, it seems cmake is missing a file:
> LINK : fatal error LNK1104: cannot open file 'MSVCRTD.lib' 

However, I have included the path to that file via:
> LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64;C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\;C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x86;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x86;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\store;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\store\amd64

First, I don't get it why these standards are not set up correctly. Second, I don't know how to tell CMake where to find the library it's missing.

**Comment by vector-of-bool** [comment]
You shouldn't have to tweak your global system environment variables in order to perform the build. Visual C++ should have shipped with a "Developer Command Prompt" which will dynamically set up the correct build environment as required. If you start VSCode from within this command prompt (make sure no prior instances are already running), then delete your build directory and reconfigure, you should see it succeed.

I tried to implement a feature that would lift the requirement to use the developer command prompt, but [it broke everything](https://github.com/vector-of-bool/vscode-cmake-tools/issues/79), so you'll still need to use the dev command prompt until I can get that fixed. Give it a try and get back to me.

**Comment by Schroedingers-Cat** [comment]
![grafik](https://cloud.githubusercontent.com/assets/6382400/20400430/f37737ba-acf4-11e6-8dd6-35c1a595a768.png)

When I start this (its name is a bit different that what you suggested), I get this window:
![grafik](https://cloud.githubusercontent.com/assets/6382400/20400474/199324f4-acf5-11e6-8aba-251b3635804c.png)

I'm not sure if that is correct, but it's stating an error already. I started VSC from this prompt but I got the same results.

**Comment by vector-of-bool** [comment]
Have you reverted the changes to your system environment variables and also completely deleted the build directory?

Instead of running VSCode, execute these commands from the developer command prompt inside of your project directory:

~~~batch
md build
cd build
cmake ..
~~~

Tell me if that configures properly.

**Comment by Schroedingers-Cat** [comment]
Ok, I deleted the additional LIB and INCLUDE Variables and removed the Paths I manually added to PATH.

I get this when I run it from "Developer Command Prompt for VS2015":

> -- Building for: Visual Studio 14 2015
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:2 (project):
>   No CMAKE_C_COMPILER could be found.
> 
> 
> 
> CMake Error at CMakeLists.txt:2 (project):
>   No CMAKE_CXX_COMPILER could be found.
> 

When starting the Developer Command prompt, I get this error:
> Der Befehl ""D:\Programme (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VCVarsQueryRegistry.bat"" ist entweder falsch geschrieben oder
> konnte nicht gefunden werden.
> ERROR: Cannot determine the location of the VS installation.
Could it be possible, that there is an issue because this bat file is missing?

**Comment by vector-of-bool** [comment]
That's interesting... If you execute `cl` inside of the dev command prompt, what output do you receive? It looks like you've also installed visual studio in a non-standard directory. What do you see inside of the `D:\Programme (x86)\Microsoft Visual Studio 14.0\Common7\Tools` directory?

**Comment by Schroedingers-Cat** [comment]
![grafik](https://cloud.githubusercontent.com/assets/6382400/20401267/592de5ba-acf8-11e6-8660-4df1f78a47d1.png)

The command `cl` cannot be found. Oh my, what's going on here.

**Comment by vector-of-bool** [comment]
This is somewhat beyond me. I'd recommend doing a reinstall and seeing what happens next.

**Comment by Schroedingers-Cat** [comment]
I fully removed all MS Visual related stuff, rebooted and installed VSC and visualcppbuildtools_full. This time, I get an entry in the start menu for every plattform and when I open Visual Studio Code from the prompt, it finds the compilers. Thank you for your help!
