### ISSUE TITLE
CMake Tools always runs make before a build even though no CMake file are changing

### ISSUE THREAD

**Issue by imikejackson** [vector-of-bool/vscode-cmake-tools#81]
Would be nice if CMake did not have to run each time and instead just invoke Ninja.

**Comment by vector-of-bool** [comment]
I thought I had fixed this in the past. It should only reconfigure if actually necessary. What platform and versions are you using?

**Comment by imikejackson** [comment]
Mac OS X 10.10.5 and VS Code 1.7.1 and 0.8.0 of your tool.

**Comment by vector-of-bool** [comment]
Should be fixed in `0.8.2`
