### ISSUE TITLE
Allow passing arguments to CMake

### ISSUE THREAD

**Issue by Lillecarl** [vector-of-bool/vscode-cmake-tools#82]
Hi!

I noticed that to "pass parameters" to CMake you configure once, then edit the CMake cache file to set paths and such.

i was thinking there should be an option in the Palette like:
CMake configure with additional params.
Which then opens a second box where i can type things like -DCMAKE_INSTALL_PREFIX=/usr/local/ and others alike.

Would be a bit more intuitive for people not too common with CMake.

Cheers :)

**Comment by s-martin** [comment]
Does 
`"cmake.configureArgs": []`
help?

**Comment by Lillecarl** [comment]
I'm sorry but I don't get what you're referring to :/

**Comment by vector-of-bool** [comment]
Take a look at [the configuration options available for the extension](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/configuration.md). That should have what you need.

**Comment by vector-of-bool** [comment]
Do the available configuration options support your use case?

**Comment by krab** [comment]
Add to settings.json example:
```
{
    "cmake.configureArgs": [
        "-DCMAKE_PREFIX_PATH=C:/Qt/5.7/msvc2015"
    ]
}
```

**Comment by Lillecarl** [comment]
@vector-of-bool  Well yes it supports the needs, but it's not presented in a very nice GUI so to speak.

**Comment by vector-of-bool** [comment]
I've thought about ways to better show the CMake options available within VSCode, but I'm not sure that there is currently a very good alternative to `settings.json`. I recently sent a PR to have syntax highlighting in `CMakeCache.txt`, which should at least improve the experience of editing the cache directly. There's also `cmake-gui`, which I might add a command for launching. Note that using `cmake.configureSettings` is probably your best bet so far. (Should be preferred to `configureArgs`). In your example of settings `CMAKE_INSTALL_PREFIX`, that's best set using `cmake.installPrefix` in your `settings.json`.

Hopefully we'll get some better support for custom UI in future VSCode updates.

**Comment by vector-of-bool** [comment]
Good news! I've found a way to get such a GUI-style cache editor in. It's still a little rough around the edges, but it should be available in the 0.9.0 release experimentally. I'll close this issue and any more issues regarding the cache editor should be brought up in a new issue when it comes out next week. Thanks!

**Comment by Lillecarl** [comment]
Great! 👍

**Comment by tiendq** [comment]
> Add to settings.json example:
> 
> ```
> {
>     "cmake.configureArgs": [
>         "-DCMAKE_PREFIX_PATH=C:/Qt/5.7/msvc2015"
>     ]
> }
> ```

It affects all projects, doesn't it?

How can I add more argument for a specific project? It complains that I need to add `Qt5_Dir`, I do know how to do with CMake but not with this extension.

**Comment by Lillecarl** [comment]
> 
> 
> > Add to settings.json example:
> > ```
> > {
> >     "cmake.configureArgs": [
> >         "-DCMAKE_PREFIX_PATH=C:/Qt/5.7/msvc2015"
> >     ]
> > }
> > ```
> 
> It affects all projects, doesn't it?
> 
> How can I add more argument for a specific project? It complains that I need to add `Qt5_Dir`, I do know how to do with CMake but not with this extension.

There are workspace and user settings.json
https://stackoverflow.com/questions/44629890/what-is-a-workspace-in-visual-studio-code
https://code.visualstudio.com/docs/getstarted/settings
