### ISSUE TITLE
Build is started before autosave files is finished

### ISSUE THREAD

**Issue by bbosnjak** [vector-of-bool/vscode-cmake-tools#84]
It is easy to reproduce (Windows):

1. Make one c file read-only
2. Made some changes to file
3. Start build (click Build on status bar)

vscode prompt:
![image](https://cloud.githubusercontent.com/assets/3226555/20440859/109a6592-adc2-11e6-87d8-c5d472c192cd.png)
Build is running parallely.

**Comment by vector-of-bool** [comment]
Good catch.

**Comment by vector-of-bool** [comment]
Should be fixed in `0.8.2`
