### ISSUE TITLE
Getting error on every Cmake command

### ISSUE THREAD

**Issue by bbosnjak** [vector-of-bool/vscode-cmake-tools#85]
I am getting error on everything I try to do with Cmake. I deleted everything from build and cmaketools.json. Note I do use cross compiler, my build environment can not be auto-detected.
Using plugin 0.8.3
![image](https://cloud.githubusercontent.com/assets/3226555/20489967/b5f70df0-b00c-11e6-9c8a-6bab7ab0dffb.png)

**Comment by vector-of-bool** [comment]
Could I see a traceback from the error? Open up devtools in Code and paste the traceback here. I've been trying to solve this one for a few days, and I'm unable to reproduce it myself

**Comment by bbosnjak** [comment]
I did some debugging:
Problem starts with:
`console.assert(!!mat, line);` in environment.ts.
This exception is cached in `_init` but also passed to the:
`await Promise.all(env_promises);`
As Promise.all do not catch it, exception is cached by `await cmake.initFinished` in `activate()`. No code after Promise.all is executed.
This works for me:
```
        try {
            await Promise.all(env_promises);
        } catch (e) {
        }
```

console.assert(!!mat, line) is triggered by arch = 'x64_arm'. This is wrong option and vcvarsall.bat prints usage:

> Error in script usage. The correct usage is:
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option]
>   or
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option] store
>   or
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option] [version number]
>   or
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option] store [version number]
> where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_arm
> where [version number] is either the full Windows 10 SDK version number or "8.1" to use the windows 8.1 SDK
> :
> The store parameter sets environment variables to support
>   store (rather than desktop) development.
> :
> For example:
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_arm store
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64 10.0.10240.0
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_arm store 10.0.10240.0
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 8.1
>     "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 store 8.1
> :
> Please make sure either Visual Studio or C++ Build SKU is installed.

**Comment by vector-of-bool** [comment]
I didn't catch that error in my own testing. Odd... I'm seeing the `AssertionError` in my own log, but I'm still able to execute commands without error.

Try this as a temporary workaround: In `.cmaketools.json`, add `"activeEnvironments": []`. See if that fixes anything.

Ping @MathiasMagnus.

**Comment by bbosnjak** [comment]
nope...
Here is also trace you asked before.
[trace.zip](https://github.com/vector-of-bool/vscode-cmake-tools/files/604598/trace.zip)

**Comment by vector-of-bool** [comment]
Thanks! I wish I could reproduce the issue, but I may have to blindly release your suggested patch if I can't get a test to work... I can at least verify and fix the issue with `x64_arm`.

**Comment by vector-of-bool** [comment]
Great news! I was able to reproduce the issue on my own system. For some reason, my `vcvarsall.bat` was perfectly happy to accept `x64_arm` as a toolchain (???). Entering an obviously fake toolchain like `asdfqwerty` caused the same issue you've been seeing. I've got a fix in, should release tonight.

**Comment by MathiasMagnus** [comment]
Works like a charm. Thanks!
