### ISSUE TITLE
Unable to generate CMake project after 0.8.0

### ISSUE THREAD

**Issue by MrJaqbq** [vector-of-bool/vscode-cmake-tools#88]
After updating to ``0.8.0`` (happens on newer versions up to ``0.8.5``) I'm unable to generate project files.

```
-- Configuring done
CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times for different configurations
  or languages with different content:

    C:/Projekty/YAGE/Engine/build/CMakeToolsMeta.txt

-- Generating done
-- Build files have been written to: C:/Projekty/YAGE/Engine/build
[vscode] cmake existed with status 1
```
(last error repeats 9 times)

Heres [CMakeToolsMeta.txt](https://gist.github.com/MrJaqbq/4ecf1f1a27c0fa559130058aa721aaa8)

What is interesting - when I change something in workspace settings, like ``"cmake.experimental.enableTargetDebugging"`` (has same effect regardless of value) and call ``CMake : Configure`` once again, project updates without errors and everything seems to work.

Generating project by hand (regardless of OS and target) and in other IDEs (VS 14 2015 and Clion checked) produces no errors.

You can find project that I'm trying to generate [here](https://github.com/MrJaqbq/YAGE)
(if you get missing RT_LIBRARY errors, set building glfw examples and tests to OFF in cache)

``.cmaketools.json``
```
{
  "variant": {
    "label": "Debug",
    "keywordSettings": {
      "buildType": "debug"
    },
    "description": "Emit debug information without performing optimizations"
  }
}
```

**Comment by vector-of-bool** [comment]
What CMake generator are you using?

**Comment by MrJaqbq** [comment]
``Visual Studio 14 2015``, its getting picked by default

**Comment by vector-of-bool** [comment]
Could you show me the contents of `CMakeToolsHelpers.cmake`? I've seen and solved this issue before, but apparently it has regressed somehow.

**Comment by MrJaqbq** [comment]
Here you go : [CMakeToolsHelpers.cmake](https://gist.github.com/MrJaqbq/1ca98e8d0cb0c10411287f486bd7b545)

**Comment by vector-of-bool** [comment]
Have you tweaked any of the extension's settings? If so, could I see those?

Also, if you run `delete cached build settings and reconfigure`, could you paste the CMake command shown in the output channel?

**Comment by MrJaqbq** [comment]
The only setting i've changed is 
```
    // Enable experimental target debugging features
    "cmake.experimental.enableTargetDebugging": true
```
but its value has no effect (changing it after generating with error however, has)

```
[vscode] Setting up new CMake configuration
[vscode] Executing command: cmake -Hc:/projekty/yage/engine -Bc:/Projekty/YAGE/Engine/build -Cc:\Projekty\YAGE\Engine\build\CMakeTools\InitializeCache.cmake -DCMAKE_BUILD_TYPE=Debug
loading initial cache file c:\Projekty\YAGE\Engine\build\CMakeTools\InitializeCache.cmake
-- Building for: Visual Studio 14 2015
-- The CXX compiler identification is MSVC 19.0.24215.1
```


[Full output](https://gist.github.com/MrJaqbq/265402443dbb036f0436dd0c5e8e1d5b)

**Comment by vector-of-bool** [comment]
I'll look into this again. As a workaround, subsequent configures should not produce any errors. It's an issue that CMake Tools is unable to determine the generator you are using for the first configure (which is odd). The error from cmake itself shouldn't prevent you from being able to build the project itself.

**Comment by ashmsuhsl** [comment]
I can confirm this issue remains with:

Visual Studio Code 1.8.1
CMake Tools 0.8.6
CMake 3.7.1
(plus box has Visual Studio 2015 Enterprise Update 3 installed)

Reproduced with \cmake-3.7.1\Tests\Tutorial\Step7\. Also with this:

https://github.com/cognitivewaves/CMake-VisualStudio-Example

This example builds a DLL and EXE and has a target that deposits both binaries in a folder. I was unable to debug that target.

Thank you for this VSCode extension. It is otherwise very useful.
