### ISSUE TITLE
set settings in variant

### ISSUE THREAD

**Issue by josesimoes** [vector-of-bool/vscode-cmake-tools#90]
Hi,

From the documentation I was under the impression that one could set settings on each variant (the ones that are passed to cmake as -D). Like this:

```
{
  "variant": {
    "label": "Debug",
    "keywordSettings": {
      "buildType": "debug"
    },
    "settings": {
          "OPT1" : "1",
          "OP2" : "XYZ"
      },    
    "description": "Emit debug information without performing optimizations"
  },

  "activeEnvironments": [
    "Visual C++ 14.0 - amd64_arm"
  ]
}
```

Right now I'm able to pass those by adding "cmake.configureSettings" to the settings.json under vscode directory.

I find it very useful that settings per variant exist.
Appreciate your explanation on the above and keep up the good work with this awesome extension. :)

**Comment by vector-of-bool** [comment]
That appears to be the `.cmaketools.json`. That file is generated automatically, and shouldn't be edited. Have you taken a look at [the documentation on `cmake-variants.json`](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/build_variants.md)?

**Comment by josesimoes** [comment]
You are correct on the file! I completely missed the diferences in the file name... 

I now have a cmake-variants.json file like the one bellow

```
{
    "buildType": 
    {
        "default$": "debug",
        "description$": "the build type to use",
        "debug": 
        {
            "oneWordSummary$": "Debug",
            "description$": "Emit debug information without performing optimizations",
            "buildType": "Debug",
 	    "settings": {
          	"OPT1" : "1",
          	"OP2" : "XYZ"
      	     }, 
        },
        "release": 
        {
            "oneWordSummary$": "Release",
            "description$": "Enable optimizations, omit debug info",
            "buildType": "Release"
        },

        "minsize": 
        {
            "oneWordSummary$": "MinSizeRel",
            "description$": "Optimize for smallest binary size",
            "buildType": "MinSizeRel"
        },

        "reldeb": 
        {
            "oneWordSummary$": "RelWithDebInfo",
            "description$": "Perform optimizations AND include debugging information",
            "buildType": "RelWithDebInfo"
        }
}
```

but the result is the same... I can't get those settings to be passed to cmake. Only if I add "cmake.configureSettings" to the settings.json.
I'm I missing something else again?

Thanks!

**Comment by vector-of-bool** [comment]
In your example, those options will only be passed when you have selected the `Debug` build variant, so they won't be passed with Release/Debug/MinSizeRel. You can put then into a new variant setting, like so:

~~~json
{
  "buildType": {
    "default$": "debug",
    "description$": "the build type to use",
    "debug": {
      "oneWordSummary$": "Debug",
      "description$": "Emit debug information without performing optimizations",
      "buildType": "Debug"
    },
    "release": {
      "oneWordSummary$": "Release",
      "description$": "Enable optimizations, omit debug info",
      "buildType": "Release"
    },
    "minsize": {
      "oneWordSummary$": "MinSizeRel",
      "description$": "Optimize for smallest binary size",
      "buildType": "MinSizeRel"
    },
    "reldeb": {
      "oneWordSummary$": "RelWithDebInfo",
      "description$": "Perform optimizations AND include debugging information",
      "buildType": "RelWithDebInfo"
    }
  },
  "foo": {
    "default$": "bar",
    "description$": "The build settings",
    "bar": {
      "oneWordSummary$": "Primary",
      "description$": "Primary build Settings",
      "settings": {
        "OPT1": "1",
        "OP2": "XYZ"
      }
    },
    "baz": {
      "oneWordSummary$": "Secondary",
      "description$": "Secondary build Settings",
      "settings": {
        "OPT1": "2",
        "OP2": "ABC"
      }
    }
  }
}
~~~

This will cause there to be eight variants: `Debug + Primary`, `Debug + Secondary`, `Release + Primary`, `Release + Secondary`, etc.

Note that you won't see the options you specify in the command line for CMake that is in the output window, but they are still passed to CMake using the `InitializeCache.cmake` file, which is generated by CMake Tools each time CMake is rerun.

**Comment by josesimoes** [comment]
That makes sense.
Another issue: I can't see any other options on the drop down except the usual 4 (Debug, Release, MinSizeRel and RelWithDebInfo)
I've copied exactly the code above into the cmake-variants.json files.
Is there anything else that needs to be done to (refresh?) the options that show when the cmake-variants.json content changes?

**Comment by vector-of-bool** [comment]
Where did you place the `cmake-variants.json` file? I need to clarify in the documentation: It must be placed in the root workspace directory, not in the `.vscode` directory.

**Comment by josesimoes** [comment]
Yes, I had if on the .vscode directory. Just moved it to the root and now it works as expected!

👍  for updating the documentation and clarifying this.
