### ISSUE TITLE
allow debugConfig to hold have several configurations

### ISSUE THREAD

**Issue by josesimoes** [vector-of-bool/vscode-cmake-tools#92]
The debug features is a great feature in this awesome extension.
But I'm missing something from the standard C/C++ debug: having several debug configurations.
Please make this available by allowing more than one debugConfig in the settings.json file or, even better, make debugConfig available from cmake-variants.json.

**Comment by vector-of-bool** [comment]
Sounds like a useful design. I wish that vscode allowed a more flexible API for debugging. Thanks for the suggestion!

I'm about to do some serious refactoring for supporting the new cmake-server mode. As such, a lot of enhancements will probably be placed on hold for a while until I can get a new plugin design nailed down.

## Feedback Wanted:

For all readers: What would be your preferred design for setting up debug configurations?

**Comment by josesimoes** [comment]
Suggest that you follow how it's currently implemented in the target extension. 
In the cmake-variants.json the current "debugConfig" element holds an equivalent of "launch.json" on which there is an array of "configurations".
For the UI: you read that "configurations" array and populate the " 🐞 Debug" item in the toolbar with the several "name" elements on the "configurations" array.

**Comment by letmaik** [comment]
This would be useful for specifying command-line arguments for specific debug target executables.

**Comment by vector-of-bool** [comment]
I don't think I'll do this one, since there may be a better alternative now in 0.9.4. See the notes on the `cmake.debugTargetProgramPath`, which may do what you want for this issue.
