### ISSUE TITLE
Compiler output parsed as [Link] which isn't actually a linker error.

### ISSUE THREAD

**Issue by NOhs** [vector-of-bool/vscode-cmake-tools#95]
The cmake-tools extension nicely populates the diagnostics with errors and warnings from GCC, but it also outputs some other lines that contain the word "ERROR" as linker errors, which clutter the diagnostics and are not actually linker errors.

Simple example with a type and two unused variables:

![image](https://cloud.githubusercontent.com/assets/20553080/20935254/3dfa9d70-bbde-11e6-910e-9046672262d3.png)

And the corresponding output of GCC responsible for the additional error messages:

![image](https://cloud.githubusercontent.com/assets/20553080/20935419/ee32332e-bbde-11e6-89df-0688abc0f8e6.png)

Is there a way to get rid of the fake linker errors? Can I set my own regexp like I would do in a default `tasks.json`?

**Comment by vector-of-bool** [comment]
That's a bug. I've had trouble with the linker error parser producing false positives for a while, and it's a game of whack-a-mole to stomp them all out. I'll add a test case to make sure that Make errors _are not_ parsed like this.

**Comment by NOhs** [comment]
Nice. Thanks.

**Comment by vector-of-bool** [comment]
Hey there, I've been completely missing for a while. The extension has kind of been in limbo as a wait for a CMake fix that just seems to be floating in limbo as well. I just want to let you know that I haven't forgotten about this project and that I plan on getting this fixed as soon as I can (probably the next release). I just finished a large refactor which has taken a lot of time, and I was also nervous about releasing it. Now that it's in the wild, I'll have to see if there are any detrimental affects.

Thank you for your patience!

**Comment by NOhs** [comment]
Nice!
