### ISSUE TITLE
ctest display in an editor

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#96]
this is not an issue , but just don't see how to enable (like on your screenshot) editor side displaying test results. could you explain please? of course - Catch is in use

**Comment by vector-of-bool** [comment]
It should "Just work". If it isn't, that's a bug. What process are you following to try and see the annotated test results? Could I see some example test output which is not being parsed?

**Comment by amigo421** [comment]
sorry, my mistake - just all tests were successul :) 
please close the request

**Comment by pvaibhav** [comment]
Requesting to reopen this bug, Catch integration seems to have stopped working for me. It used to work perfectly fine! Not sure what changed. I've tried both CMake Server mode and regular mode. The failing test case shows up fine in the output window, yet no annotation in the editor (line 13 in the screenshot should show FAILED).

CMake Tools v0.9.4
CMake v3.8.0
VScode 1.11.2
Catch v1.9.3 (also tried v.1.7.0, no difference).

<img width="1162" alt="screen shot 2017-05-01 at 11 38 10" src="https://cloud.githubusercontent.com/assets/234072/25576939/e1962778-2e62-11e7-9f18-3c8d3cdb37b1.png">

I've also tried another project which worked fine 'before' and that doesn't work now either.

CMakeLists.txt contents:
```
cmake_minimum_required(VERSION 3.0.0)

project(lib-cpp-math VERSION 0.1.0)
set(CMAKE_CXX_STANDARD 14)
include(CTest)
enable_testing()

add_executable(FixedSizeDelayTests
tests/catch.cpp
tests/FixedSizeDelayTests.cpp
)
add_test(FixedSizeDelayTests FixedSizeDelayTests)

add_executable(IntegralTests
tests/catch.cpp
tests/IntegralTests.cpp
)
add_test(IntegralTests IntegralTests)

add_executable(LowPassFilterTests
tests/catch.cpp
tests/LowPassFilterTests.cpp
)
add_test(LowPassFilterTests LowPassFilterTests)

add_library(cpp-math
src/PIDController.cpp
)

include_directories(cpp-math
    INTERFACE include
)

target_include_directories(FixedSizeDelayTests
    PRIVATE tests
)
target_include_directories(IntegralTests
    PRIVATE tests
)
target_include_directories(LowPassFilterTests
    PRIVATE tests
)
```

**Comment by vector-of-bool** [comment]
I'll take a look

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
